// Generated by GREEN-ECC transition-aware scheduling. Do not edit manually.
// This is a policy package; it does not implement the migration datapath.
package green_ecc_schedule_pkg;
  localparam int ECC_MODE_COUNT = 3;
  localparam int ECC_MODE_WIDTH = 2;
  localparam int ECC_SCHEDULE_EPOCHS = 12;
  localparam int ECC_MIN_DWELL_EPOCHS = 2;
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_SAFE_FALLBACK = ECC_MODE_WIDTH'(2);
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_EPOCH_MODE [0:ECC_SCHEDULE_EPOCHS-1] = '{
    ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(0), ECC_MODE_WIDTH'(2), ECC_MODE_WIDTH'(2), ECC_MODE_WIDTH'(2), ECC_MODE_WIDTH'(2), ECC_MODE_WIDTH'(2), ECC_MODE_WIDTH'(2)
  };
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_MODE_SEC_DED_64 = ECC_MODE_WIDTH'(0);
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_MODE_SEC_DAEC_64 = ECC_MODE_WIDTH'(1);
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_MODE_TAEC_64 = ECC_MODE_WIDTH'(2);
endpackage
