- name: calibration
  color: bfd4f2
  description: Calibration related tasks
- name: reliability
  color: fef2c0
  description: Reliability improvements
- name: selector
  color: f9d0c4
  description: ECC selector components
- name: telemetry
  color: d4c5f9
  description: Telemetry and logging
- name: validation
  color: c2e0c6
  description: Validation and verification
- name: docs
  color: fef2c0
  description: Documentation updates
- name: CI
  color: cfd3d7
  description: Continuous integration
