/* Generated by Yosys 0.30+48 (git sha1 b5b0b7e83, x86_64-w64-mingw32-g++ 13.1.0 -march=nocona -msahf -mtune=generic -O2 -Os) */

module gate03r_secded_pipelined_combined(clk_i, valid_i, data_i, valid_o, data_o, codeword_o, detected_o, corrected_o, uncorrectable_o);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  wire _0794_;
  wire _0795_;
  wire _0796_;
  wire _0797_;
  wire _0798_;
  wire _0799_;
  wire _0800_;
  wire _0801_;
  wire _0802_;
  wire _0803_;
  wire _0804_;
  wire _0805_;
  wire _0806_;
  wire _0807_;
  wire _0808_;
  wire _0809_;
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  wire _0815_;
  wire _0816_;
  wire _0817_;
  wire _0818_;
  wire _0819_;
  wire _0820_;
  wire _0821_;
  wire _0822_;
  wire _0823_;
  wire _0824_;
  wire _0825_;
  wire _0826_;
  wire _0827_;
  wire _0828_;
  wire _0829_;
  wire _0830_;
  wire _0831_;
  wire _0832_;
  wire _0833_;
  wire _0834_;
  wire _0835_;
  wire _0836_;
  wire _0837_;
  wire _0838_;
  wire _0839_;
  wire _0840_;
  wire _0841_;
  wire _0842_;
  wire _0843_;
  wire _0844_;
  wire _0845_;
  wire _0846_;
  wire _0847_;
  wire _0848_;
  wire _0849_;
  wire _0850_;
  wire _0851_;
  wire _0852_;
  wire _0853_;
  wire _0854_;
  wire _0855_;
  wire _0856_;
  wire _0857_;
  wire _0858_;
  wire _0859_;
  wire _0860_;
  wire _0861_;
  wire _0862_;
  wire _0863_;
  wire _0864_;
  wire _0865_;
  wire _0866_;
  wire _0867_;
  wire _0868_;
  wire _0869_;
  wire _0870_;
  wire _0871_;
  wire _0872_;
  wire _0873_;
  wire _0874_;
  wire _0875_;
  wire _0876_;
  wire _0877_;
  wire _0878_;
  wire _0879_;
  wire _0880_;
  wire _0881_;
  wire _0882_;
  wire _0883_;
  wire _0884_;
  wire _0885_;
  wire _0886_;
  wire _0887_;
  wire _0888_;
  wire _0889_;
  wire _0890_;
  wire _0891_;
  wire _0892_;
  wire _0893_;
  wire _0894_;
  wire _0895_;
  wire _0896_;
  wire _0897_;
  wire _0898_;
  wire _0899_;
  wire _0900_;
  wire _0901_;
  wire _0902_;
  wire _0903_;
  wire _0904_;
  wire _0905_;
  wire _0906_;
  wire _0907_;
  wire _0908_;
  wire _0909_;
  wire _0910_;
  wire _0911_;
  wire _0912_;
  wire _0913_;
  wire _0914_;
  wire _0915_;
  wire _0916_;
  wire _0917_;
  wire _0918_;
  wire _0919_;
  wire _0920_;
  wire _0921_;
  wire _0922_;
  wire _0923_;
  wire _0924_;
  wire _0925_;
  wire _0926_;
  wire _0927_;
  wire _0928_;
  wire _0929_;
  wire _0930_;
  wire _0931_;
  wire _0932_;
  wire _0933_;
  wire _0934_;
  wire _0935_;
  wire _0936_;
  wire _0937_;
  wire _0938_;
  wire _0939_;
  wire _0940_;
  wire _0941_;
  wire _0942_;
  wire _0943_;
  wire _0944_;
  wire _0945_;
  wire _0946_;
  wire _0947_;
  wire _0948_;
  wire _0949_;
  wire _0950_;
  wire _0951_;
  wire _0952_;
  wire _0953_;
  wire _0954_;
  wire _0955_;
  wire _0956_;
  wire _0957_;
  wire _0958_;
  wire _0959_;
  input clk_i;
  wire clk_i;
  output [71:0] codeword_o;
  wire [71:0] codeword_o;
  output corrected_o;
  wire corrected_o;
  input [63:0] data_i;
  wire [63:0] data_i;
  output [63:0] data_o;
  wire [63:0] data_o;
  wire \decoder.clk_i ;
  wire [71:0] \decoder.codeword_i ;
  wire [71:0] \decoder.corrected_d ;
  wire \decoder.corrected_flag_d ;
  reg \decoder.corrected_flag_q ;
  wire [71:0] \decoder.correction_mask_d ;
  wire [63:0] \decoder.data_d ;
  wire [31:0] \decoder.data_index ;
  wire [63:0] \decoder.data_o ;
  reg [63:0] \decoder.data_q ;
  wire \decoder.detected_d ;
  reg \decoder.detected_q ;
  wire \decoder.err_corrected_o ;
  wire \decoder.err_detected_o ;
  wire \decoder.err_uncorrectable_o ;
  wire [31:0] \decoder.error_position ;
  wire [31:0] \decoder.group_index ;
  wire [31:0] \decoder.group_offset ;
  wire \decoder.overall_mismatch_d ;
  reg \decoder.overall_mismatch_q ;
  wire [31:0] \decoder.parity_index ;
  wire [31:0] \decoder.position ;
  wire [71:0] \decoder.received_q ;
  reg \decoder.stage1_valid_q ;
  reg \decoder.stage2_valid_q ;
  wire [6:0] \decoder.syndrome_d ;
  wire [8:0] \decoder.syndrome_group[3] ;
  wire [8:0] \decoder.syndrome_group[4] ;
  wire [8:0] \decoder.syndrome_group[5] ;
  wire [8:0] \decoder.syndrome_group[6] ;
  reg [6:0] \decoder.syndrome_q ;
  reg \decoder.uncorrectable_q ;
  wire \decoder.valid_i ;
  wire \decoder.valid_o ;
  output detected_o;
  wire detected_o;
  wire \encoder.clk_i ;
  wire [71:0] \encoder.codeword_o ;
  wire [63:0] \encoder.data_i ;
  wire [31:0] \encoder.data_index ;
  wire [31:0] \encoder.group_index ;
  wire [31:0] \encoder.group_offset ;
  wire [6:0] \encoder.parity_d ;
  wire [8:0] \encoder.parity_group[3] ;
  wire [8:0] \encoder.parity_group[4] ;
  wire [8:0] \encoder.parity_group[5] ;
  wire [8:0] \encoder.parity_group[6] ;
  wire [31:0] \encoder.parity_index ;
  wire [31:0] \encoder.position ;
  wire [70:0] \encoder.positional_d ;
  reg [70:0] \encoder.positional_q ;
  reg \encoder.stage1_valid_q ;
  reg [71:0] \encoder.stage2_codeword_q ;
  reg \encoder.stage2_valid_q ;
  wire \encoder.valid_i ;
  wire \encoder.valid_o ;
  wire encoder_valid;
  output uncorrectable_o;
  wire uncorrectable_o;
  input valid_i;
  wire valid_i;
  output valid_o;
  wire valid_o;
  assign _0357_ = ~data_i[32];
  assign _0358_ = ~data_i[31];
  assign _0359_ = ~data_i[30];
  assign _0360_ = ~(data_i[27] ^ data_i[26]);
  assign _0361_ = ~(_0360_ ^ data_i[28]);
  assign _0362_ = ~(_0361_ ^ data_i[29]);
  assign _0363_ = ~(_0362_ ^ _0359_);
  assign _0364_ = ~(_0363_ ^ _0358_);
  assign _0365_ = ~(_0364_ ^ _0357_);
  assign _0366_ = ~(_0365_ ^ data_i[33]);
  assign _0367_ = ~data_i[41];
  assign _0368_ = ~data_i[40];
  assign _0369_ = ~data_i[39];
  assign _0370_ = ~data_i[38];
  assign _0371_ = ~(data_i[35] ^ data_i[34]);
  assign _0372_ = ~(_0371_ ^ data_i[36]);
  assign _0373_ = ~(_0372_ ^ data_i[37]);
  assign _0374_ = ~(_0373_ ^ _0370_);
  assign _0375_ = ~(_0374_ ^ _0369_);
  assign _0376_ = ~(_0375_ ^ _0368_);
  assign _0377_ = ~(_0376_ ^ _0367_);
  assign _0378_ = ~(_0377_ ^ _0366_);
  assign _0379_ = ~data_i[49];
  assign _0380_ = ~data_i[48];
  assign _0381_ = ~data_i[47];
  assign _0382_ = ~data_i[46];
  assign _0383_ = ~(data_i[43] ^ data_i[42]);
  assign _0384_ = ~(_0383_ ^ data_i[44]);
  assign _0385_ = ~(_0384_ ^ data_i[45]);
  assign _0386_ = ~(_0385_ ^ _0382_);
  assign _0387_ = ~(_0386_ ^ _0381_);
  assign _0388_ = ~(_0387_ ^ _0380_);
  assign _0389_ = ~(_0388_ ^ _0379_);
  assign _0390_ = ~data_i[56];
  assign _0391_ = ~data_i[55];
  assign _0392_ = ~data_i[54];
  assign _0393_ = ~(data_i[50] ^ data_i[51]);
  assign _0394_ = ~(_0393_ ^ data_i[52]);
  assign _0395_ = ~(_0394_ ^ data_i[53]);
  assign _0396_ = ~(_0395_ ^ _0392_);
  assign _0397_ = ~(_0396_ ^ _0391_);
  assign _0398_ = ~(_0397_ ^ _0390_);
  assign _0399_ = ~(_0398_ ^ _0389_);
  assign \encoder.parity_d [5] = ~(_0399_ ^ _0378_);
  assign _0400_ = ~(data_i[1] ^ data_i[0]);
  assign _0401_ = ~(_0400_ ^ data_i[3]);
  assign _0402_ = ~data_i[10];
  assign _0403_ = ~data_i[8];
  assign _0404_ = ~(data_i[6] ^ data_i[4]);
  assign _0405_ = ~(_0404_ ^ _0403_);
  assign _0406_ = ~(_0405_ ^ _0402_);
  assign _0407_ = ~(_0406_ ^ _0401_);
  assign _0408_ = ~data_i[17];
  assign _0409_ = ~data_i[15];
  assign _0410_ = ~(data_i[13] ^ data_i[11]);
  assign _0411_ = ~(_0410_ ^ _0409_);
  assign _0412_ = ~(_0411_ ^ _0408_);
  assign _0413_ = ~data_i[25];
  assign _0414_ = ~data_i[23];
  assign _0415_ = ~(data_i[21] ^ data_i[19]);
  assign _0416_ = ~(_0415_ ^ _0414_);
  assign _0417_ = ~(_0416_ ^ _0413_);
  assign _0418_ = ~(_0417_ ^ _0412_);
  assign _0419_ = ~(_0418_ ^ _0407_);
  assign _0420_ = ~(data_i[28] ^ data_i[26]);
  assign _0421_ = ~(_0420_ ^ _0359_);
  assign _0422_ = ~(_0421_ ^ _0357_);
  assign _0423_ = ~(data_i[36] ^ data_i[34]);
  assign _0424_ = ~(_0423_ ^ _0370_);
  assign _0425_ = ~(_0424_ ^ _0368_);
  assign _0426_ = ~(_0425_ ^ _0422_);
  assign _0427_ = ~(data_i[44] ^ data_i[42]);
  assign _0428_ = ~(_0427_ ^ _0382_);
  assign _0429_ = ~(_0428_ ^ _0380_);
  assign _0430_ = ~(data_i[50] ^ data_i[52]);
  assign _0431_ = ~(_0430_ ^ _0392_);
  assign _0432_ = ~(_0431_ ^ _0390_);
  assign _0433_ = ~(_0432_ ^ _0429_);
  assign _0434_ = ~(_0433_ ^ _0426_);
  assign _0435_ = ~(_0434_ ^ _0419_);
  assign _0436_ = ~data_i[63];
  assign _0437_ = ~data_i[61];
  assign _0438_ = ~(data_i[57] ^ data_i[59]);
  assign _0439_ = ~(_0438_ ^ _0437_);
  assign _0440_ = ~(_0439_ ^ _0436_);
  assign \encoder.parity_d [0] = ~(_0440_ ^ _0435_);
  assign _0441_ = ~(data_i[1] ^ data_i[2]);
  assign _0442_ = ~(_0441_ ^ data_i[3]);
  assign _0443_ = ~data_i[9];
  assign _0444_ = ~(data_i[8] ^ data_i[7]);
  assign _0445_ = ~(_0444_ ^ _0443_);
  assign _0446_ = ~(_0445_ ^ _0402_);
  assign _0447_ = ~(_0446_ ^ _0442_);
  assign _0448_ = ~data_i[16];
  assign _0449_ = ~(data_i[15] ^ data_i[14]);
  assign _0450_ = ~(_0449_ ^ _0448_);
  assign _0451_ = ~(_0450_ ^ _0408_);
  assign _0452_ = ~data_i[24];
  assign _0453_ = ~(data_i[22] ^ data_i[23]);
  assign _0454_ = ~(_0453_ ^ _0452_);
  assign _0455_ = ~(_0454_ ^ _0413_);
  assign _0456_ = ~(_0455_ ^ _0451_);
  assign _0457_ = ~(_0456_ ^ _0447_);
  assign _0458_ = ~(data_i[30] ^ data_i[29]);
  assign _0459_ = ~(_0458_ ^ _0358_);
  assign _0460_ = ~(_0459_ ^ _0357_);
  assign _0461_ = ~(data_i[37] ^ data_i[38]);
  assign _0462_ = ~(_0461_ ^ _0369_);
  assign _0463_ = ~(_0462_ ^ _0368_);
  assign _0464_ = ~(_0463_ ^ _0460_);
  assign _0465_ = ~(data_i[46] ^ data_i[45]);
  assign _0466_ = ~(_0465_ ^ _0381_);
  assign _0467_ = ~(_0466_ ^ _0380_);
  assign _0468_ = ~(data_i[54] ^ data_i[53]);
  assign _0469_ = ~(_0468_ ^ _0391_);
  assign _0470_ = ~(_0469_ ^ _0390_);
  assign _0471_ = ~(_0470_ ^ _0467_);
  assign _0472_ = ~(_0471_ ^ _0464_);
  assign _0473_ = ~(_0472_ ^ _0457_);
  assign _0474_ = ~data_i[62];
  assign _0475_ = ~(data_i[60] ^ data_i[61]);
  assign _0476_ = ~(_0475_ ^ _0474_);
  assign _0477_ = ~(_0476_ ^ _0436_);
  assign \encoder.parity_d [2] = ~(_0477_ ^ _0473_);
  assign _0478_ = ~(data_i[2] ^ data_i[0]);
  assign _0479_ = ~(_0478_ ^ data_i[3]);
  assign _0480_ = ~(data_i[6] ^ data_i[5]);
  assign _0481_ = ~(_0480_ ^ _0443_);
  assign _0482_ = ~(_0481_ ^ _0402_);
  assign _0483_ = ~(_0482_ ^ _0479_);
  assign _0484_ = ~(data_i[13] ^ data_i[12]);
  assign _0485_ = ~(_0484_ ^ _0448_);
  assign _0486_ = ~(_0485_ ^ _0408_);
  assign _0487_ = ~(data_i[21] ^ data_i[20]);
  assign _0488_ = ~(_0487_ ^ _0452_);
  assign _0489_ = ~(_0488_ ^ _0413_);
  assign _0490_ = ~(_0489_ ^ _0486_);
  assign _0491_ = ~(_0490_ ^ _0483_);
  assign _0492_ = ~(data_i[28] ^ data_i[27]);
  assign _0493_ = ~(_0492_ ^ _0358_);
  assign _0494_ = ~(_0493_ ^ _0357_);
  assign _0495_ = ~(data_i[36] ^ data_i[35]);
  assign _0496_ = ~(_0495_ ^ _0369_);
  assign _0497_ = ~(_0496_ ^ _0368_);
  assign _0498_ = ~(_0497_ ^ _0494_);
  assign _0499_ = ~(data_i[44] ^ data_i[43]);
  assign _0500_ = ~(_0499_ ^ _0381_);
  assign _0501_ = ~(_0500_ ^ _0380_);
  assign _0502_ = ~(data_i[52] ^ data_i[51]);
  assign _0503_ = ~(_0502_ ^ _0391_);
  assign _0504_ = ~(_0503_ ^ _0390_);
  assign _0505_ = ~(_0504_ ^ _0501_);
  assign _0506_ = ~(_0505_ ^ _0498_);
  assign _0507_ = ~(_0506_ ^ _0491_);
  assign _0508_ = ~(data_i[58] ^ data_i[59]);
  assign _0509_ = ~(_0508_ ^ _0474_);
  assign _0510_ = ~(_0509_ ^ _0436_);
  assign \encoder.parity_d [1] = ~(_0510_ ^ _0507_);
  assign _0511_ = ~(data_i[12] ^ data_i[11]);
  assign _0512_ = ~(_0511_ ^ data_i[13]);
  assign _0513_ = ~(_0512_ ^ data_i[14]);
  assign _0514_ = ~(_0513_ ^ _0409_);
  assign _0515_ = ~(_0514_ ^ _0448_);
  assign _0516_ = ~(_0515_ ^ _0408_);
  assign _0517_ = ~(_0516_ ^ data_i[18]);
  assign _0518_ = ~(data_i[20] ^ data_i[19]);
  assign _0519_ = ~(_0518_ ^ data_i[21]);
  assign _0520_ = ~(_0519_ ^ data_i[22]);
  assign _0521_ = ~(_0520_ ^ _0414_);
  assign _0522_ = ~(_0521_ ^ _0452_);
  assign _0523_ = ~(_0522_ ^ _0413_);
  assign _0524_ = ~(_0523_ ^ _0517_);
  assign _0525_ = ~(_0399_ ^ _0367_);
  assign \encoder.parity_d [4] = ~(_0525_ ^ _0524_);
  assign _0526_ = \encoder.positional_q [1] ^ \encoder.positional_q [0];
  assign _0527_ = ~(\encoder.positional_q [3] ^ \encoder.positional_q [2]);
  assign _0528_ = ~(_0527_ ^ _0526_);
  assign _0529_ = ~(\encoder.positional_q [5] ^ \encoder.positional_q [4]);
  assign _0530_ = ~(\encoder.positional_q [7] ^ \encoder.positional_q [6]);
  assign _0531_ = ~(_0530_ ^ _0529_);
  assign _0532_ = ~(_0531_ ^ _0528_);
  assign _0533_ = ~(\encoder.positional_q [9] ^ \encoder.positional_q [8]);
  assign _0534_ = ~(\encoder.positional_q [11] ^ \encoder.positional_q [10]);
  assign _0535_ = ~(_0534_ ^ _0533_);
  assign _0536_ = ~(\encoder.positional_q [13] ^ \encoder.positional_q [12]);
  assign _0537_ = ~(\encoder.positional_q [15] ^ \encoder.positional_q [14]);
  assign _0538_ = ~(_0537_ ^ _0536_);
  assign _0539_ = ~(_0538_ ^ _0535_);
  assign _0540_ = ~(_0539_ ^ _0532_);
  assign _0541_ = ~(\encoder.positional_q [17] ^ \encoder.positional_q [16]);
  assign _0542_ = ~(\encoder.positional_q [19] ^ \encoder.positional_q [18]);
  assign _0543_ = ~(_0542_ ^ _0541_);
  assign _0544_ = ~(\encoder.positional_q [21] ^ \encoder.positional_q [20]);
  assign _0545_ = ~(\encoder.positional_q [23] ^ \encoder.positional_q [22]);
  assign _0546_ = ~(_0545_ ^ _0544_);
  assign _0547_ = ~(_0546_ ^ _0543_);
  assign _0548_ = ~(\encoder.positional_q [25] ^ \encoder.positional_q [24]);
  assign _0549_ = ~(\encoder.positional_q [27] ^ \encoder.positional_q [26]);
  assign _0550_ = ~(_0549_ ^ _0548_);
  assign _0551_ = ~(\encoder.positional_q [29] ^ \encoder.positional_q [28]);
  assign _0552_ = ~(\encoder.positional_q [31] ^ \encoder.positional_q [30]);
  assign _0553_ = ~(_0552_ ^ _0551_);
  assign _0554_ = ~(_0553_ ^ _0550_);
  assign _0555_ = ~(_0554_ ^ _0547_);
  assign _0556_ = ~(_0555_ ^ _0540_);
  assign _0557_ = ~(\encoder.positional_q [33] ^ \encoder.positional_q [32]);
  assign _0558_ = ~(\encoder.positional_q [35] ^ \encoder.positional_q [34]);
  assign _0559_ = ~(_0558_ ^ _0557_);
  assign _0560_ = ~(\encoder.positional_q [37] ^ \encoder.positional_q [36]);
  assign _0561_ = ~(\encoder.positional_q [39] ^ \encoder.positional_q [38]);
  assign _0562_ = ~(_0561_ ^ _0560_);
  assign _0563_ = ~(_0562_ ^ _0559_);
  assign _0564_ = ~(\encoder.positional_q [41] ^ \encoder.positional_q [40]);
  assign _0565_ = ~(\encoder.positional_q [43] ^ \encoder.positional_q [42]);
  assign _0566_ = ~(_0565_ ^ _0564_);
  assign _0567_ = ~(\encoder.positional_q [45] ^ \encoder.positional_q [44]);
  assign _0568_ = ~(\encoder.positional_q [47] ^ \encoder.positional_q [46]);
  assign _0569_ = ~(_0568_ ^ _0567_);
  assign _0570_ = ~(_0569_ ^ _0566_);
  assign _0571_ = ~(_0570_ ^ _0563_);
  assign _0572_ = ~(\encoder.positional_q [49] ^ \encoder.positional_q [48]);
  assign _0573_ = ~(\encoder.positional_q [51] ^ \encoder.positional_q [50]);
  assign _0574_ = ~(_0573_ ^ _0572_);
  assign _0575_ = ~(\encoder.positional_q [53] ^ \encoder.positional_q [52]);
  assign _0576_ = ~(\encoder.positional_q [55] ^ \encoder.positional_q [54]);
  assign _0577_ = ~(_0576_ ^ _0575_);
  assign _0578_ = ~(_0577_ ^ _0574_);
  assign _0579_ = ~(\encoder.positional_q [57] ^ \encoder.positional_q [56]);
  assign _0580_ = ~(\encoder.positional_q [59] ^ \encoder.positional_q [58]);
  assign _0581_ = ~(_0580_ ^ _0579_);
  assign _0582_ = ~(\encoder.positional_q [61] ^ \encoder.positional_q [60]);
  assign _0583_ = ~(\encoder.positional_q [63] ^ \encoder.positional_q [62]);
  assign _0584_ = ~(_0583_ ^ _0582_);
  assign _0585_ = ~(_0584_ ^ _0581_);
  assign _0586_ = ~(_0585_ ^ _0578_);
  assign _0587_ = ~(_0586_ ^ _0571_);
  assign _0588_ = ~(_0587_ ^ _0556_);
  assign _0589_ = ~(\encoder.positional_q [65] ^ \encoder.positional_q [64]);
  assign _0590_ = ~(\encoder.positional_q [67] ^ \encoder.positional_q [66]);
  assign _0591_ = ~(_0590_ ^ _0589_);
  assign _0592_ = \encoder.positional_q [69] ^ \encoder.positional_q [68];
  assign _0593_ = ~(_0592_ ^ \encoder.positional_q [70]);
  assign _0594_ = ~(_0593_ ^ _0591_);
  assign _0002_ = ~(_0594_ ^ _0588_);
  assign _0595_ = ~(data_i[5] ^ data_i[4]);
  assign _0596_ = ~(_0595_ ^ data_i[6]);
  assign _0597_ = ~(_0596_ ^ data_i[7]);
  assign _0598_ = ~(_0597_ ^ _0403_);
  assign _0599_ = ~(_0598_ ^ _0443_);
  assign _0600_ = ~(_0599_ ^ data_i[10]);
  assign _0601_ = _0523_ ^ data_i[18];
  assign _0602_ = ~(_0601_ ^ _0600_);
  assign _0603_ = _0376_ ^ data_i[33];
  assign _0604_ = ~(_0398_ ^ _0379_);
  assign _0605_ = ~(_0604_ ^ _0603_);
  assign \encoder.parity_d [3] = ~(_0605_ ^ _0602_);
  assign _0606_ = ~\decoder.overall_mismatch_q ;
  assign _0607_ = ~(\decoder.syndrome_q [1] | \decoder.syndrome_q [0]);
  assign _0608_ = \decoder.syndrome_q [3] | \decoder.syndrome_q [2];
  assign _0609_ = _0607_ & ~(_0608_);
  assign _0610_ = ~\decoder.syndrome_q [6];
  assign _0611_ = \decoder.syndrome_q [5] | \decoder.syndrome_q [4];
  assign _0612_ = _0611_ | ~(_0610_);
  assign _0613_ = _0609_ & ~(_0612_);
  assign _0614_ = ~(_0613_ | _0606_);
  assign _0615_ = _0613_ & ~(_0606_);
  assign _0000_ = _0615_ | _0614_;
  assign _0616_ = ~\encoder.stage2_codeword_q [5];
  assign _0617_ = ~(\encoder.stage2_codeword_q [4] ^ \encoder.stage2_codeword_q [3]);
  assign _0618_ = ~(_0617_ ^ _0616_);
  assign _0619_ = ~(_0618_ ^ \encoder.stage2_codeword_q [6]);
  assign _0620_ = ~\encoder.stage2_codeword_q [14];
  assign _0621_ = ~\encoder.stage2_codeword_q [13];
  assign _0622_ = ~(\encoder.stage2_codeword_q [12] ^ \encoder.stage2_codeword_q [11]);
  assign _0623_ = ~(_0622_ ^ _0621_);
  assign _0624_ = ~(_0623_ ^ _0620_);
  assign _0625_ = ~(_0624_ ^ _0619_);
  assign _0626_ = ~\encoder.stage2_codeword_q [22];
  assign _0627_ = ~\encoder.stage2_codeword_q [21];
  assign _0628_ = ~(\encoder.stage2_codeword_q [20] ^ \encoder.stage2_codeword_q [19]);
  assign _0629_ = ~(_0628_ ^ _0627_);
  assign _0630_ = ~(_0629_ ^ _0626_);
  assign _0631_ = ~\encoder.stage2_codeword_q [30];
  assign _0632_ = ~\encoder.stage2_codeword_q [29];
  assign _0633_ = ~(\encoder.stage2_codeword_q [28] ^ \encoder.stage2_codeword_q [27]);
  assign _0634_ = ~(_0633_ ^ _0632_);
  assign _0635_ = ~(_0634_ ^ _0631_);
  assign _0636_ = ~(_0635_ ^ _0630_);
  assign _0637_ = ~(_0636_ ^ _0625_);
  assign _0638_ = ~\encoder.stage2_codeword_q [38];
  assign _0639_ = ~\encoder.stage2_codeword_q [37];
  assign _0640_ = ~(\encoder.stage2_codeword_q [36] ^ \encoder.stage2_codeword_q [35]);
  assign _0641_ = ~(_0640_ ^ _0639_);
  assign _0642_ = ~(_0641_ ^ _0638_);
  assign _0643_ = ~\encoder.stage2_codeword_q [46];
  assign _0644_ = ~\encoder.stage2_codeword_q [45];
  assign _0645_ = ~(\encoder.stage2_codeword_q [44] ^ \encoder.stage2_codeword_q [43]);
  assign _0646_ = ~(_0645_ ^ _0644_);
  assign _0647_ = ~(_0646_ ^ _0643_);
  assign _0648_ = ~(_0647_ ^ _0642_);
  assign _0649_ = ~\encoder.stage2_codeword_q [54];
  assign _0650_ = ~\encoder.stage2_codeword_q [53];
  assign _0651_ = ~(\encoder.stage2_codeword_q [52] ^ \encoder.stage2_codeword_q [51]);
  assign _0652_ = ~(_0651_ ^ _0650_);
  assign _0653_ = ~(_0652_ ^ _0649_);
  assign _0654_ = ~\encoder.stage2_codeword_q [62];
  assign _0655_ = ~\encoder.stage2_codeword_q [61];
  assign _0656_ = ~(\encoder.stage2_codeword_q [60] ^ \encoder.stage2_codeword_q [59]);
  assign _0657_ = ~(_0656_ ^ _0655_);
  assign _0658_ = ~(_0657_ ^ _0654_);
  assign _0659_ = ~(_0658_ ^ _0653_);
  assign _0660_ = ~(_0659_ ^ _0648_);
  assign _0661_ = ~(_0660_ ^ _0637_);
  assign _0662_ = ~\encoder.stage2_codeword_q [70];
  assign _0663_ = ~\encoder.stage2_codeword_q [69];
  assign _0664_ = ~(\encoder.stage2_codeword_q [68] ^ \encoder.stage2_codeword_q [67]);
  assign _0665_ = ~(_0664_ ^ _0663_);
  assign _0666_ = ~(_0665_ ^ _0662_);
  assign \decoder.syndrome_d [2] = ~(_0666_ ^ _0661_);
  assign _0667_ = \encoder.stage2_codeword_q [2] ^ \encoder.stage2_codeword_q [0];
  assign _0668_ = ~(_0667_ ^ \encoder.stage2_codeword_q [4]);
  assign _0669_ = ~(_0668_ ^ \encoder.stage2_codeword_q [6]);
  assign _0670_ = ~\encoder.stage2_codeword_q [12];
  assign _0671_ = ~(\encoder.stage2_codeword_q [10] ^ \encoder.stage2_codeword_q [8]);
  assign _0672_ = ~(_0671_ ^ _0670_);
  assign _0673_ = ~(_0672_ ^ _0620_);
  assign _0674_ = ~(_0673_ ^ _0669_);
  assign _0675_ = ~\encoder.stage2_codeword_q [20];
  assign _0676_ = ~(\encoder.stage2_codeword_q [18] ^ \encoder.stage2_codeword_q [16]);
  assign _0677_ = ~(_0676_ ^ _0675_);
  assign _0678_ = ~(_0677_ ^ _0626_);
  assign _0679_ = ~\encoder.stage2_codeword_q [28];
  assign _0680_ = ~(\encoder.stage2_codeword_q [26] ^ \encoder.stage2_codeword_q [24]);
  assign _0681_ = ~(_0680_ ^ _0679_);
  assign _0682_ = ~(_0681_ ^ _0631_);
  assign _0683_ = ~(_0682_ ^ _0678_);
  assign _0684_ = ~(_0683_ ^ _0674_);
  assign _0685_ = ~\encoder.stage2_codeword_q [36];
  assign _0686_ = ~(\encoder.stage2_codeword_q [34] ^ \encoder.stage2_codeword_q [32]);
  assign _0687_ = ~(_0686_ ^ _0685_);
  assign _0688_ = ~(_0687_ ^ _0638_);
  assign _0689_ = ~\encoder.stage2_codeword_q [44];
  assign _0690_ = ~(\encoder.stage2_codeword_q [42] ^ \encoder.stage2_codeword_q [40]);
  assign _0691_ = ~(_0690_ ^ _0689_);
  assign _0692_ = ~(_0691_ ^ _0643_);
  assign _0693_ = ~(_0692_ ^ _0688_);
  assign _0694_ = ~\encoder.stage2_codeword_q [52];
  assign _0695_ = ~(\encoder.stage2_codeword_q [50] ^ \encoder.stage2_codeword_q [48]);
  assign _0696_ = ~(_0695_ ^ _0694_);
  assign _0697_ = ~(_0696_ ^ _0649_);
  assign _0698_ = ~\encoder.stage2_codeword_q [60];
  assign _0699_ = ~(\encoder.stage2_codeword_q [58] ^ \encoder.stage2_codeword_q [56]);
  assign _0700_ = ~(_0699_ ^ _0698_);
  assign _0701_ = ~(_0700_ ^ _0654_);
  assign _0702_ = ~(_0701_ ^ _0697_);
  assign _0703_ = ~(_0702_ ^ _0693_);
  assign _0704_ = ~(_0703_ ^ _0684_);
  assign _0705_ = ~\encoder.stage2_codeword_q [68];
  assign _0706_ = ~(\encoder.stage2_codeword_q [66] ^ \encoder.stage2_codeword_q [64]);
  assign _0707_ = ~(_0706_ ^ _0705_);
  assign _0708_ = ~(_0707_ ^ _0662_);
  assign \decoder.syndrome_d [0] = ~(_0708_ ^ _0704_);
  assign _0709_ = ~\encoder.stage2_codeword_q [39];
  assign _0710_ = ~(\encoder.stage2_codeword_q [33] ^ \encoder.stage2_codeword_q [32]);
  assign _0711_ = ~(_0710_ ^ \encoder.stage2_codeword_q [34]);
  assign _0712_ = ~(_0711_ ^ \encoder.stage2_codeword_q [35]);
  assign _0713_ = ~(_0712_ ^ _0685_);
  assign _0714_ = ~(_0713_ ^ _0639_);
  assign _0715_ = ~(_0714_ ^ _0638_);
  assign _0716_ = ~(_0715_ ^ _0709_);
  assign _0717_ = ~\encoder.stage2_codeword_q [47];
  assign _0718_ = ~(\encoder.stage2_codeword_q [41] ^ \encoder.stage2_codeword_q [40]);
  assign _0719_ = ~(_0718_ ^ \encoder.stage2_codeword_q [42]);
  assign _0720_ = ~(_0719_ ^ \encoder.stage2_codeword_q [43]);
  assign _0721_ = ~(_0720_ ^ _0689_);
  assign _0722_ = ~(_0721_ ^ _0644_);
  assign _0723_ = ~(_0722_ ^ _0643_);
  assign _0724_ = ~(_0723_ ^ _0717_);
  assign _0725_ = ~(_0724_ ^ _0716_);
  assign _0726_ = ~\encoder.stage2_codeword_q [55];
  assign _0727_ = ~(\encoder.stage2_codeword_q [49] ^ \encoder.stage2_codeword_q [48]);
  assign _0728_ = ~(_0727_ ^ \encoder.stage2_codeword_q [50]);
  assign _0729_ = ~(_0728_ ^ \encoder.stage2_codeword_q [51]);
  assign _0730_ = ~(_0729_ ^ _0694_);
  assign _0731_ = ~(_0730_ ^ _0650_);
  assign _0732_ = ~(_0731_ ^ _0649_);
  assign _0733_ = ~(_0732_ ^ _0726_);
  assign _0734_ = ~(\encoder.stage2_codeword_q [57] ^ \encoder.stage2_codeword_q [56]);
  assign _0735_ = ~(_0734_ ^ \encoder.stage2_codeword_q [58]);
  assign _0736_ = ~(_0735_ ^ \encoder.stage2_codeword_q [59]);
  assign _0737_ = ~(_0736_ ^ _0698_);
  assign _0738_ = ~(_0737_ ^ _0655_);
  assign _0739_ = ~(_0738_ ^ _0654_);
  assign _0740_ = ~(_0739_ ^ _0733_);
  assign _0741_ = ~(_0740_ ^ _0725_);
  assign \decoder.syndrome_d [5] = ~(_0741_ ^ \encoder.stage2_codeword_q [31]);
  assign _0742_ = ~\encoder.stage2_codeword_q [23];
  assign _0743_ = ~(\encoder.stage2_codeword_q [17] ^ \encoder.stage2_codeword_q [16]);
  assign _0744_ = ~(_0743_ ^ \encoder.stage2_codeword_q [18]);
  assign _0745_ = ~(_0744_ ^ \encoder.stage2_codeword_q [19]);
  assign _0746_ = ~(_0745_ ^ _0675_);
  assign _0747_ = ~(_0746_ ^ _0627_);
  assign _0748_ = ~(_0747_ ^ _0626_);
  assign _0749_ = ~(_0748_ ^ _0742_);
  assign _0750_ = ~(\encoder.stage2_codeword_q [25] ^ \encoder.stage2_codeword_q [24]);
  assign _0751_ = ~(_0750_ ^ \encoder.stage2_codeword_q [26]);
  assign _0752_ = ~(_0751_ ^ \encoder.stage2_codeword_q [27]);
  assign _0753_ = ~(_0752_ ^ _0679_);
  assign _0754_ = ~(_0753_ ^ _0632_);
  assign _0755_ = ~(_0754_ ^ _0631_);
  assign _0756_ = ~(_0755_ ^ _0749_);
  assign _0757_ = ~(_0756_ ^ \encoder.stage2_codeword_q [15]);
  assign _0758_ = ~(_0740_ ^ _0717_);
  assign \decoder.syndrome_d [4] = ~(_0758_ ^ _0757_);
  assign _0759_ = ~(\encoder.stage2_codeword_q [2] ^ \encoder.stage2_codeword_q [1]);
  assign _0760_ = ~(_0759_ ^ _0616_);
  assign _0761_ = ~(_0760_ ^ \encoder.stage2_codeword_q [6]);
  assign _0762_ = ~(\encoder.stage2_codeword_q [10] ^ \encoder.stage2_codeword_q [9]);
  assign _0763_ = ~(_0762_ ^ _0621_);
  assign _0764_ = ~(_0763_ ^ _0620_);
  assign _0765_ = ~(_0764_ ^ _0761_);
  assign _0766_ = ~(\encoder.stage2_codeword_q [18] ^ \encoder.stage2_codeword_q [17]);
  assign _0767_ = ~(_0766_ ^ _0627_);
  assign _0768_ = ~(_0767_ ^ _0626_);
  assign _0769_ = ~(\encoder.stage2_codeword_q [26] ^ \encoder.stage2_codeword_q [25]);
  assign _0770_ = ~(_0769_ ^ _0632_);
  assign _0771_ = ~(_0770_ ^ _0631_);
  assign _0772_ = ~(_0771_ ^ _0768_);
  assign _0773_ = ~(_0772_ ^ _0765_);
  assign _0774_ = ~(\encoder.stage2_codeword_q [34] ^ \encoder.stage2_codeword_q [33]);
  assign _0775_ = ~(_0774_ ^ _0639_);
  assign _0776_ = ~(_0775_ ^ _0638_);
  assign _0777_ = ~(\encoder.stage2_codeword_q [42] ^ \encoder.stage2_codeword_q [41]);
  assign _0778_ = ~(_0777_ ^ _0644_);
  assign _0779_ = ~(_0778_ ^ _0643_);
  assign _0780_ = ~(_0779_ ^ _0776_);
  assign _0781_ = ~(\encoder.stage2_codeword_q [50] ^ \encoder.stage2_codeword_q [49]);
  assign _0782_ = ~(_0781_ ^ _0650_);
  assign _0783_ = ~(_0782_ ^ _0649_);
  assign _0784_ = ~(\encoder.stage2_codeword_q [58] ^ \encoder.stage2_codeword_q [57]);
  assign _0785_ = ~(_0784_ ^ _0655_);
  assign _0786_ = ~(_0785_ ^ _0654_);
  assign _0787_ = ~(_0786_ ^ _0783_);
  assign _0788_ = ~(_0787_ ^ _0780_);
  assign _0789_ = ~(_0788_ ^ _0773_);
  assign _0790_ = ~(\encoder.stage2_codeword_q [66] ^ \encoder.stage2_codeword_q [65]);
  assign _0791_ = ~(_0790_ ^ _0663_);
  assign _0792_ = ~(_0791_ ^ _0662_);
  assign \decoder.syndrome_d [1] = ~(_0792_ ^ _0789_);
  assign _0793_ = ~(\encoder.stage2_codeword_q [9] ^ \encoder.stage2_codeword_q [8]);
  assign _0794_ = ~(_0793_ ^ \encoder.stage2_codeword_q [10]);
  assign _0795_ = ~(_0794_ ^ \encoder.stage2_codeword_q [11]);
  assign _0796_ = ~(_0795_ ^ _0670_);
  assign _0797_ = ~(_0796_ ^ _0621_);
  assign _0798_ = ~(_0797_ ^ _0620_);
  assign _0799_ = ~(_0798_ ^ \encoder.stage2_codeword_q [7]);
  assign _0800_ = ~(_0755_ ^ _0742_);
  assign _0801_ = ~(_0800_ ^ _0799_);
  assign _0802_ = ~(_0723_ ^ _0709_);
  assign _0803_ = ~(_0739_ ^ _0726_);
  assign _0804_ = ~(_0803_ ^ _0802_);
  assign \decoder.syndrome_d [3] = ~(_0804_ ^ _0801_);
  assign _0805_ = ~(\encoder.stage2_codeword_q [65] ^ \encoder.stage2_codeword_q [64]);
  assign _0806_ = ~(_0805_ ^ \encoder.stage2_codeword_q [66]);
  assign _0807_ = ~(_0806_ ^ \encoder.stage2_codeword_q [67]);
  assign _0808_ = ~(_0807_ ^ _0705_);
  assign _0809_ = ~(_0808_ ^ _0663_);
  assign _0810_ = ~(_0809_ ^ _0662_);
  assign \decoder.syndrome_d [6] = ~(_0810_ ^ \encoder.stage2_codeword_q [63]);
  assign _0001_ = ~(_0613_ | \decoder.overall_mismatch_q );
  assign \decoder.detected_d  = ~(_0613_ & _0606_);
  assign _0811_ = ~(\decoder.syndrome_q [1] | \decoder.syndrome_q [2]);
  assign _0812_ = \decoder.syndrome_q [3] | \decoder.syndrome_q [4];
  assign _0813_ = _0811_ & ~(_0812_);
  assign _0814_ = \decoder.syndrome_q [5] | \decoder.syndrome_q [6];
  assign _0815_ = _0814_ | ~(\decoder.syndrome_q [0]);
  assign _0816_ = _0813_ & ~(_0815_);
  assign _0817_ = _0814_ | ~(_0813_);
  assign _0818_ = ~(_0817_ | _0816_);
  assign _0819_ = \decoder.syndrome_q [2] & ~(\decoder.syndrome_q [3]);
  assign _0820_ = ~(\decoder.syndrome_q [1] & \decoder.syndrome_q [0]);
  assign _0821_ = _0819_ & ~(_0820_);
  assign _0822_ = _0611_ | ~(\decoder.syndrome_q [6]);
  assign _0823_ = _0821_ & ~(_0822_);
  assign _0824_ = ~(_0821_ | \decoder.syndrome_q [3]);
  assign _0825_ = ~(_0824_ | _0611_);
  assign _0826_ = ~(_0825_ | _0611_);
  assign _0827_ = _0826_ | ~(\decoder.syndrome_q [6]);
  assign _0828_ = ~(_0827_ | _0823_);
  assign _0829_ = ~(_0828_ | _0818_);
  assign \decoder.corrected_flag_d  = _0614_ ? _0829_ : _0615_;
  assign _0830_ = ~(data_i[58] ^ data_i[57]);
  assign _0831_ = ~(_0830_ ^ data_i[59]);
  assign _0832_ = ~(_0831_ ^ data_i[60]);
  assign _0833_ = ~(_0832_ ^ _0437_);
  assign _0834_ = ~(_0833_ ^ _0474_);
  assign \encoder.parity_d [6] = ~(_0834_ ^ data_i[63]);
  assign _0835_ = ~\decoder.syndrome_q [0];
  assign _0836_ = ~(_0607_ | _0608_);
  assign _0837_ = ~(_0836_ | _0608_);
  assign _0838_ = ~(_0837_ | _0611_);
  assign _0839_ = ~(_0838_ | _0611_);
  assign _0840_ = ~(_0839_ & _0610_);
  assign _0841_ = ~(_0839_ ^ \decoder.syndrome_q [6]);
  assign _0842_ = _0837_ & ~(\decoder.syndrome_q [4]);
  assign _0843_ = ~(_0842_ ^ \decoder.syndrome_q [5]);
  assign _0844_ = _0837_ ^ \decoder.syndrome_q [4];
  assign _0845_ = _0844_ | ~(_0843_);
  assign _0846_ = _0845_ | ~(_0841_);
  assign _0847_ = _0607_ & ~(\decoder.syndrome_q [2]);
  assign _0848_ = _0847_ ^ \decoder.syndrome_q [3];
  assign _0849_ = _0607_ ^ \decoder.syndrome_q [2];
  assign _0850_ = ~(_0849_ | _0848_);
  assign _0851_ = \decoder.syndrome_q [0] & ~(\decoder.syndrome_q [1]);
  assign _0852_ = ~_0851_;
  assign _0853_ = _0852_ | ~(_0850_);
  assign _0854_ = ~(_0853_ | _0846_);
  assign _0855_ = _0854_ | ~(_0840_);
  assign _0856_ = ~(_0855_ | _0835_);
  assign _0857_ = _0820_ & ~(_0607_);
  assign _0858_ = ~(_0857_ ^ \decoder.syndrome_q [0]);
  assign _0859_ = _0856_ & ~(_0858_);
  assign _0860_ = ~(_0852_ ^ _0849_);
  assign _0861_ = _0859_ & ~(_0860_);
  assign _0862_ = ~(_0852_ | _0849_);
  assign _0863_ = _0862_ ^ _0848_;
  assign _0864_ = _0861_ & ~(_0863_);
  assign _0865_ = ~(_0853_ ^ _0844_);
  assign _0866_ = _0864_ & ~(_0865_);
  assign _0867_ = ~(_0853_ | _0844_);
  assign _0868_ = ~(_0867_ ^ _0843_);
  assign _0869_ = _0866_ & ~(_0868_);
  assign _0870_ = ~(_0853_ | _0845_);
  assign _0871_ = ~(_0870_ ^ _0841_);
  assign _0872_ = _0869_ & ~(_0871_);
  assign _0873_ = _0870_ & _0841_;
  assign _0874_ = ~(_0873_ ^ _0840_);
  assign _0875_ = _0874_ | ~(_0872_);
  assign _0876_ = _0875_ | ~(_0829_);
  assign _0877_ = _0876_ | ~(_0614_);
  assign \decoder.corrected_d [2] = ~(_0877_ ^ \decoder.received_q [2]);
  assign _0878_ = ~_0874_;
  assign _0879_ = ~_0871_;
  assign _0880_ = ~_0868_;
  assign _0881_ = ~_0865_;
  assign _0882_ = ~_0863_;
  assign _0883_ = ~_0860_;
  assign _0884_ = ~(_0858_ & _0856_);
  assign _0885_ = _0884_ | ~(_0883_);
  assign _0886_ = _0885_ | ~(_0882_);
  assign _0887_ = _0886_ | ~(_0881_);
  assign _0888_ = _0887_ | ~(_0880_);
  assign _0889_ = _0888_ | ~(_0879_);
  assign _0890_ = _0889_ | ~(_0878_);
  assign _0891_ = _0890_ | ~(_0829_);
  assign _0892_ = _0891_ | ~(_0614_);
  assign \decoder.corrected_d [4] = ~(_0892_ ^ \decoder.received_q [4]);
  assign _0893_ = ~_0614_;
  assign _0894_ = _0855_ | ~(_0835_);
  assign _0895_ = _0894_ | _0858_;
  assign _0896_ = _0895_ | ~(_0860_);
  assign _0897_ = _0896_ | _0863_;
  assign _0898_ = _0897_ | ~(_0881_);
  assign _0899_ = _0898_ | _0868_;
  assign _0900_ = _0899_ | ~(_0879_);
  assign _0901_ = _0900_ | ~(_0878_);
  assign _0902_ = _0901_ | ~(_0829_);
  assign _0903_ = _0902_ | _0893_;
  assign \decoder.corrected_d [5] = ~(_0903_ ^ \decoder.received_q [5]);
  assign _0904_ = _0883_ | ~(_0859_);
  assign _0905_ = _0904_ | ~(_0882_);
  assign _0906_ = _0905_ | ~(_0881_);
  assign _0907_ = _0906_ | ~(_0880_);
  assign _0908_ = _0907_ | ~(_0879_);
  assign _0909_ = _0908_ | ~(_0878_);
  assign _0910_ = _0909_ | ~(_0829_);
  assign _0911_ = _0910_ | ~(_0614_);
  assign \decoder.corrected_d [6] = ~(_0911_ ^ \decoder.received_q [6]);
  assign _0912_ = _0884_ | ~(_0860_);
  assign _0913_ = _0912_ | ~(_0882_);
  assign _0914_ = _0913_ | ~(_0881_);
  assign _0915_ = _0914_ | ~(_0880_);
  assign _0916_ = _0915_ | ~(_0879_);
  assign _0917_ = _0916_ | ~(_0878_);
  assign _0918_ = _0917_ | ~(_0829_);
  assign _0919_ = _0918_ | ~(_0614_);
  assign \decoder.corrected_d [8] = ~(_0919_ ^ \decoder.received_q [8]);
  assign _0920_ = _0895_ | _0860_;
  assign _0921_ = _0920_ | ~(_0863_);
  assign _0922_ = _0921_ | ~(_0881_);
  assign _0923_ = _0922_ | _0868_;
  assign _0924_ = _0923_ | ~(_0879_);
  assign _0925_ = _0924_ | ~(_0878_);
  assign _0926_ = _0925_ | ~(_0829_);
  assign _0927_ = _0926_ | _0893_;
  assign \decoder.corrected_d [9] = ~(_0927_ ^ \decoder.received_q [9]);
  assign _0928_ = _0882_ | ~(_0861_);
  assign _0929_ = _0928_ | ~(_0881_);
  assign _0930_ = _0929_ | ~(_0880_);
  assign _0931_ = _0930_ | ~(_0879_);
  assign _0932_ = _0931_ | ~(_0878_);
  assign _0933_ = _0932_ | ~(_0829_);
  assign _0934_ = _0933_ | ~(_0614_);
  assign \decoder.corrected_d [10] = ~(_0934_ ^ \decoder.received_q [10]);
  assign _0935_ = _0894_ | ~(_0858_);
  assign _0936_ = _0935_ | _0860_;
  assign _0937_ = _0936_ | ~(_0863_);
  assign _0938_ = _0937_ | ~(_0881_);
  assign _0939_ = _0938_ | _0868_;
  assign _0940_ = _0939_ | ~(_0879_);
  assign _0941_ = _0940_ | ~(_0878_);
  assign _0942_ = _0941_ | ~(_0829_);
  assign _0943_ = _0942_ | _0893_;
  assign \decoder.corrected_d [11] = ~(_0943_ ^ \decoder.received_q [11]);
  assign _0944_ = _0885_ | ~(_0863_);
  assign _0945_ = _0944_ | ~(_0881_);
  assign _0946_ = _0945_ | ~(_0880_);
  assign _0947_ = _0946_ | ~(_0879_);
  assign _0948_ = _0947_ | ~(_0878_);
  assign _0949_ = _0948_ | ~(_0829_);
  assign _0950_ = _0949_ | ~(_0614_);
  assign \decoder.corrected_d [12] = ~(_0950_ ^ \decoder.received_q [12]);
  assign _0951_ = _0896_ | ~(_0863_);
  assign _0952_ = _0951_ | ~(_0881_);
  assign _0953_ = _0952_ | _0868_;
  assign _0954_ = _0953_ | ~(_0879_);
  assign _0955_ = _0954_ | ~(_0878_);
  assign _0956_ = _0955_ | ~(_0829_);
  assign _0957_ = _0956_ | _0893_;
  assign \decoder.corrected_d [13] = ~(_0957_ ^ \decoder.received_q [13]);
  assign _0958_ = _0904_ | ~(_0863_);
  assign _0959_ = _0958_ | ~(_0881_);
  assign _0003_ = _0959_ | ~(_0880_);
  assign _0004_ = _0003_ | ~(_0879_);
  assign _0005_ = _0004_ | ~(_0878_);
  assign _0006_ = _0005_ | ~(_0829_);
  assign _0007_ = _0006_ | ~(_0614_);
  assign \decoder.corrected_d [14] = ~(_0007_ ^ \decoder.received_q [14]);
  assign _0008_ = _0912_ | ~(_0863_);
  assign _0009_ = _0008_ | ~(_0881_);
  assign _0010_ = _0009_ | ~(_0880_);
  assign _0011_ = _0010_ | ~(_0879_);
  assign _0012_ = _0011_ | ~(_0878_);
  assign _0013_ = _0012_ | ~(_0829_);
  assign _0014_ = _0013_ | ~(_0614_);
  assign \decoder.corrected_d [16] = ~(_0014_ ^ \decoder.received_q [16]);
  assign _0015_ = _0920_ | _0863_;
  assign _0016_ = _0015_ | ~(_0865_);
  assign _0017_ = _0016_ | _0868_;
  assign _0018_ = _0017_ | ~(_0879_);
  assign _0019_ = _0018_ | ~(_0878_);
  assign _0020_ = _0019_ | ~(_0829_);
  assign _0021_ = _0020_ | _0893_;
  assign \decoder.corrected_d [17] = ~(_0021_ ^ \decoder.received_q [17]);
  assign _0022_ = _0881_ | ~(_0864_);
  assign _0023_ = _0022_ | ~(_0880_);
  assign _0024_ = _0023_ | ~(_0879_);
  assign _0025_ = _0024_ | ~(_0878_);
  assign _0026_ = _0025_ | ~(_0829_);
  assign _0027_ = _0026_ | ~(_0614_);
  assign \decoder.corrected_d [18] = ~(_0027_ ^ \decoder.received_q [18]);
  assign _0028_ = _0936_ | _0863_;
  assign _0029_ = _0028_ | ~(_0865_);
  assign _0030_ = _0029_ | _0868_;
  assign _0031_ = _0030_ | ~(_0879_);
  assign _0032_ = _0031_ | ~(_0878_);
  assign _0033_ = _0032_ | ~(_0829_);
  assign _0034_ = _0033_ | _0893_;
  assign \decoder.corrected_d [19] = ~(_0034_ ^ \decoder.received_q [19]);
  assign _0035_ = _0886_ | ~(_0865_);
  assign _0036_ = _0035_ | ~(_0880_);
  assign _0037_ = _0036_ | ~(_0879_);
  assign _0038_ = _0037_ | ~(_0878_);
  assign _0039_ = _0038_ | ~(_0829_);
  assign _0040_ = _0039_ | ~(_0614_);
  assign \decoder.corrected_d [20] = ~(_0040_ ^ \decoder.received_q [20]);
  assign _0041_ = _0897_ | ~(_0865_);
  assign _0042_ = _0041_ | _0868_;
  assign _0043_ = _0042_ | ~(_0879_);
  assign _0044_ = _0043_ | ~(_0878_);
  assign _0045_ = _0044_ | ~(_0829_);
  assign _0046_ = _0045_ | _0893_;
  assign \decoder.corrected_d [21] = ~(_0046_ ^ \decoder.received_q [21]);
  assign _0047_ = _0905_ | ~(_0865_);
  assign _0048_ = _0047_ | ~(_0880_);
  assign _0049_ = _0048_ | ~(_0879_);
  assign _0050_ = _0049_ | ~(_0878_);
  assign _0051_ = _0050_ | ~(_0829_);
  assign _0052_ = _0051_ | ~(_0614_);
  assign \decoder.corrected_d [22] = ~(_0052_ ^ \decoder.received_q [22]);
  assign _0053_ = _0935_ | ~(_0860_);
  assign _0054_ = _0053_ | _0863_;
  assign _0055_ = _0054_ | ~(_0865_);
  assign _0056_ = _0055_ | _0868_;
  assign _0057_ = _0056_ | ~(_0879_);
  assign _0058_ = _0057_ | ~(_0878_);
  assign _0059_ = _0058_ | ~(_0829_);
  assign _0060_ = _0059_ | _0893_;
  assign \decoder.corrected_d [23] = ~(_0060_ ^ \decoder.received_q [23]);
  assign _0061_ = _0913_ | ~(_0865_);
  assign _0062_ = _0061_ | ~(_0880_);
  assign _0063_ = _0062_ | ~(_0879_);
  assign _0064_ = _0063_ | ~(_0878_);
  assign _0065_ = _0064_ | ~(_0829_);
  assign _0066_ = _0065_ | ~(_0614_);
  assign \decoder.corrected_d [24] = ~(_0066_ ^ \decoder.received_q [24]);
  assign _0067_ = _0921_ | ~(_0865_);
  assign _0068_ = _0067_ | _0868_;
  assign _0069_ = _0068_ | ~(_0879_);
  assign _0070_ = _0069_ | ~(_0878_);
  assign _0071_ = _0070_ | ~(_0829_);
  assign _0072_ = _0071_ | _0893_;
  assign \decoder.corrected_d [25] = ~(_0072_ ^ \decoder.received_q [25]);
  assign _0073_ = _0928_ | ~(_0865_);
  assign _0074_ = _0073_ | ~(_0880_);
  assign _0075_ = _0074_ | ~(_0879_);
  assign _0076_ = _0075_ | ~(_0878_);
  assign _0077_ = _0076_ | ~(_0829_);
  assign _0078_ = _0077_ | ~(_0614_);
  assign \decoder.corrected_d [26] = ~(_0078_ ^ \decoder.received_q [26]);
  assign _0079_ = _0937_ | ~(_0865_);
  assign _0080_ = _0079_ | _0868_;
  assign _0081_ = _0080_ | ~(_0879_);
  assign _0082_ = _0081_ | ~(_0878_);
  assign _0083_ = _0082_ | ~(_0829_);
  assign _0084_ = _0083_ | _0893_;
  assign \decoder.corrected_d [27] = ~(_0084_ ^ \decoder.received_q [27]);
  assign _0085_ = _0944_ | ~(_0865_);
  assign _0086_ = _0085_ | ~(_0880_);
  assign _0087_ = _0086_ | ~(_0879_);
  assign _0088_ = _0087_ | ~(_0878_);
  assign _0089_ = _0088_ | ~(_0829_);
  assign _0090_ = _0089_ | ~(_0614_);
  assign \decoder.corrected_d [28] = ~(_0090_ ^ \decoder.received_q [28]);
  assign _0091_ = _0951_ | ~(_0865_);
  assign _0092_ = _0091_ | _0868_;
  assign _0093_ = _0092_ | ~(_0879_);
  assign _0094_ = _0093_ | ~(_0878_);
  assign _0095_ = _0094_ | ~(_0829_);
  assign _0096_ = _0095_ | _0893_;
  assign \decoder.corrected_d [29] = ~(_0096_ ^ \decoder.received_q [29]);
  assign _0097_ = _0958_ | ~(_0865_);
  assign _0098_ = _0097_ | ~(_0880_);
  assign _0099_ = _0098_ | ~(_0879_);
  assign _0100_ = _0099_ | ~(_0878_);
  assign _0101_ = _0100_ | ~(_0829_);
  assign _0102_ = _0101_ | ~(_0614_);
  assign \decoder.corrected_d [30] = ~(_0102_ ^ \decoder.received_q [30]);
  assign _0103_ = _0008_ | ~(_0865_);
  assign _0104_ = _0103_ | ~(_0880_);
  assign _0105_ = _0104_ | ~(_0879_);
  assign _0106_ = _0105_ | ~(_0878_);
  assign _0107_ = _0106_ | ~(_0829_);
  assign _0108_ = _0107_ | ~(_0614_);
  assign \decoder.corrected_d [32] = ~(_0108_ ^ \decoder.received_q [32]);
  assign _0109_ = _0015_ | ~(_0881_);
  assign _0110_ = _0109_ | ~(_0868_);
  assign _0111_ = _0110_ | ~(_0879_);
  assign _0112_ = _0111_ | ~(_0878_);
  assign _0113_ = _0112_ | ~(_0829_);
  assign _0114_ = _0113_ | _0893_;
  assign \decoder.corrected_d [33] = ~(_0114_ ^ \decoder.received_q [33]);
  assign _0115_ = _0880_ | ~(_0866_);
  assign _0116_ = _0115_ | ~(_0879_);
  assign _0117_ = _0116_ | ~(_0878_);
  assign _0118_ = _0117_ | ~(_0829_);
  assign _0119_ = _0118_ | ~(_0614_);
  assign \decoder.corrected_d [34] = ~(_0119_ ^ \decoder.received_q [34]);
  assign _0120_ = _0028_ | ~(_0881_);
  assign _0121_ = _0120_ | ~(_0868_);
  assign _0122_ = _0121_ | ~(_0879_);
  assign _0123_ = _0122_ | ~(_0878_);
  assign _0124_ = _0123_ | ~(_0829_);
  assign _0125_ = _0124_ | _0893_;
  assign \decoder.corrected_d [35] = ~(_0125_ ^ \decoder.received_q [35]);
  assign _0126_ = _0887_ | ~(_0868_);
  assign _0127_ = _0126_ | ~(_0879_);
  assign _0128_ = _0127_ | ~(_0878_);
  assign _0129_ = _0128_ | ~(_0829_);
  assign _0130_ = _0129_ | ~(_0614_);
  assign \decoder.corrected_d [36] = ~(_0130_ ^ \decoder.received_q [36]);
  assign _0131_ = _0898_ | ~(_0868_);
  assign _0132_ = _0131_ | ~(_0879_);
  assign _0133_ = _0132_ | ~(_0878_);
  assign _0134_ = _0133_ | ~(_0829_);
  assign _0135_ = _0134_ | _0893_;
  assign \decoder.corrected_d [37] = ~(_0135_ ^ \decoder.received_q [37]);
  assign _0136_ = _0906_ | ~(_0868_);
  assign _0137_ = _0136_ | ~(_0879_);
  assign _0138_ = _0137_ | ~(_0878_);
  assign _0139_ = _0138_ | ~(_0829_);
  assign _0140_ = _0139_ | ~(_0614_);
  assign \decoder.corrected_d [38] = ~(_0140_ ^ \decoder.received_q [38]);
  assign _0141_ = _0054_ | ~(_0881_);
  assign _0142_ = _0141_ | ~(_0868_);
  assign _0143_ = _0142_ | ~(_0879_);
  assign _0144_ = _0143_ | ~(_0878_);
  assign _0145_ = _0144_ | ~(_0829_);
  assign _0146_ = _0145_ | _0893_;
  assign \decoder.corrected_d [39] = ~(_0146_ ^ \decoder.received_q [39]);
  assign _0147_ = _0914_ | ~(_0868_);
  assign _0148_ = _0147_ | ~(_0879_);
  assign _0149_ = _0148_ | ~(_0878_);
  assign _0150_ = _0149_ | ~(_0829_);
  assign _0151_ = _0150_ | ~(_0614_);
  assign \decoder.corrected_d [40] = ~(_0151_ ^ \decoder.received_q [40]);
  assign _0152_ = _0922_ | ~(_0868_);
  assign _0153_ = _0152_ | ~(_0879_);
  assign _0154_ = _0153_ | ~(_0878_);
  assign _0155_ = _0154_ | ~(_0829_);
  assign _0156_ = _0155_ | _0893_;
  assign \decoder.corrected_d [41] = ~(_0156_ ^ \decoder.received_q [41]);
  assign _0157_ = _0929_ | ~(_0868_);
  assign _0158_ = _0157_ | ~(_0879_);
  assign _0159_ = _0158_ | ~(_0878_);
  assign _0160_ = _0159_ | ~(_0829_);
  assign _0161_ = _0160_ | ~(_0614_);
  assign \decoder.corrected_d [42] = ~(_0161_ ^ \decoder.received_q [42]);
  assign _0162_ = _0938_ | ~(_0868_);
  assign _0163_ = _0162_ | ~(_0879_);
  assign _0164_ = _0163_ | ~(_0878_);
  assign _0165_ = _0164_ | ~(_0829_);
  assign _0166_ = _0165_ | _0893_;
  assign \decoder.corrected_d [43] = ~(_0166_ ^ \decoder.received_q [43]);
  assign _0167_ = _0945_ | ~(_0868_);
  assign _0168_ = _0167_ | ~(_0879_);
  assign _0169_ = _0168_ | ~(_0878_);
  assign _0170_ = _0169_ | ~(_0829_);
  assign _0171_ = _0170_ | ~(_0614_);
  assign \decoder.corrected_d [44] = ~(_0171_ ^ \decoder.received_q [44]);
  assign _0172_ = _0952_ | ~(_0868_);
  assign _0173_ = _0172_ | ~(_0879_);
  assign _0174_ = _0173_ | ~(_0878_);
  assign _0175_ = _0174_ | ~(_0829_);
  assign _0176_ = _0175_ | _0893_;
  assign \decoder.corrected_d [45] = ~(_0176_ ^ \decoder.received_q [45]);
  assign _0177_ = _0959_ | ~(_0868_);
  assign _0178_ = _0177_ | ~(_0879_);
  assign _0179_ = _0178_ | ~(_0878_);
  assign _0180_ = _0179_ | ~(_0829_);
  assign _0181_ = _0180_ | ~(_0614_);
  assign \decoder.corrected_d [46] = ~(_0181_ ^ \decoder.received_q [46]);
  assign _0182_ = _0053_ | ~(_0863_);
  assign _0183_ = _0182_ | ~(_0881_);
  assign _0184_ = _0183_ | ~(_0868_);
  assign _0185_ = _0184_ | ~(_0879_);
  assign _0186_ = _0185_ | ~(_0878_);
  assign _0187_ = _0186_ | ~(_0829_);
  assign _0188_ = _0187_ | _0893_;
  assign \decoder.corrected_d [47] = ~(_0188_ ^ \decoder.received_q [47]);
  assign _0189_ = _0009_ | ~(_0868_);
  assign _0190_ = _0189_ | ~(_0879_);
  assign _0191_ = _0190_ | ~(_0878_);
  assign _0192_ = _0191_ | ~(_0829_);
  assign _0193_ = _0192_ | ~(_0614_);
  assign \decoder.corrected_d [48] = ~(_0193_ ^ \decoder.received_q [48]);
  assign _0194_ = _0016_ | ~(_0868_);
  assign _0195_ = _0194_ | ~(_0879_);
  assign _0196_ = _0195_ | ~(_0878_);
  assign _0197_ = _0196_ | ~(_0829_);
  assign _0198_ = _0197_ | _0893_;
  assign \decoder.corrected_d [49] = ~(_0198_ ^ \decoder.received_q [49]);
  assign _0199_ = _0022_ | ~(_0868_);
  assign _0200_ = _0199_ | ~(_0879_);
  assign _0201_ = _0200_ | ~(_0878_);
  assign _0202_ = _0201_ | ~(_0829_);
  assign _0203_ = _0202_ | ~(_0614_);
  assign \decoder.corrected_d [50] = ~(_0203_ ^ \decoder.received_q [50]);
  assign _0204_ = _0029_ | ~(_0868_);
  assign _0205_ = _0204_ | ~(_0879_);
  assign _0206_ = _0205_ | ~(_0878_);
  assign _0207_ = _0206_ | ~(_0829_);
  assign _0208_ = _0207_ | _0893_;
  assign \decoder.corrected_d [51] = ~(_0208_ ^ \decoder.received_q [51]);
  assign _0209_ = _0035_ | ~(_0868_);
  assign _0210_ = _0209_ | ~(_0879_);
  assign _0211_ = _0210_ | ~(_0878_);
  assign _0212_ = _0211_ | ~(_0829_);
  assign _0213_ = _0212_ | ~(_0614_);
  assign \decoder.corrected_d [52] = ~(_0213_ ^ \decoder.received_q [52]);
  assign _0214_ = _0041_ | ~(_0868_);
  assign _0215_ = _0214_ | ~(_0879_);
  assign _0216_ = _0215_ | ~(_0878_);
  assign _0217_ = _0216_ | ~(_0829_);
  assign _0218_ = _0217_ | _0893_;
  assign \decoder.corrected_d [53] = ~(_0218_ ^ \decoder.received_q [53]);
  assign _0219_ = _0047_ | ~(_0868_);
  assign _0220_ = _0219_ | ~(_0879_);
  assign _0221_ = _0220_ | ~(_0878_);
  assign _0222_ = _0221_ | ~(_0829_);
  assign _0223_ = _0222_ | ~(_0614_);
  assign \decoder.corrected_d [54] = ~(_0223_ ^ \decoder.received_q [54]);
  assign _0224_ = _0055_ | ~(_0868_);
  assign _0225_ = _0224_ | ~(_0879_);
  assign _0226_ = _0225_ | ~(_0878_);
  assign _0227_ = _0226_ | ~(_0829_);
  assign _0228_ = _0227_ | _0893_;
  assign \decoder.corrected_d [55] = ~(_0228_ ^ \decoder.received_q [55]);
  assign _0229_ = _0061_ | ~(_0868_);
  assign _0230_ = _0229_ | ~(_0879_);
  assign _0231_ = _0230_ | ~(_0878_);
  assign _0232_ = _0231_ | ~(_0829_);
  assign _0233_ = _0232_ | ~(_0614_);
  assign \decoder.corrected_d [56] = ~(_0233_ ^ \decoder.received_q [56]);
  assign _0234_ = _0067_ | ~(_0868_);
  assign _0235_ = _0234_ | ~(_0879_);
  assign _0236_ = _0235_ | ~(_0878_);
  assign _0237_ = _0236_ | ~(_0829_);
  assign _0238_ = _0237_ | _0893_;
  assign \decoder.corrected_d [57] = ~(_0238_ ^ \decoder.received_q [57]);
  assign _0239_ = _0073_ | ~(_0868_);
  assign _0240_ = _0239_ | ~(_0879_);
  assign _0241_ = _0240_ | ~(_0878_);
  assign _0242_ = _0241_ | ~(_0829_);
  assign _0243_ = _0242_ | ~(_0614_);
  assign \decoder.corrected_d [58] = ~(_0243_ ^ \decoder.received_q [58]);
  assign _0244_ = _0079_ | ~(_0868_);
  assign _0245_ = _0244_ | ~(_0879_);
  assign _0246_ = _0245_ | ~(_0878_);
  assign _0247_ = _0246_ | ~(_0829_);
  assign _0248_ = _0247_ | _0893_;
  assign \decoder.corrected_d [59] = ~(_0248_ ^ \decoder.received_q [59]);
  assign _0249_ = _0085_ | ~(_0868_);
  assign _0250_ = _0249_ | ~(_0879_);
  assign _0251_ = _0250_ | ~(_0878_);
  assign _0252_ = _0251_ | ~(_0829_);
  assign _0253_ = _0252_ | ~(_0614_);
  assign \decoder.corrected_d [60] = ~(_0253_ ^ \decoder.received_q [60]);
  assign _0254_ = _0091_ | ~(_0868_);
  assign _0255_ = _0254_ | ~(_0879_);
  assign _0256_ = _0255_ | ~(_0878_);
  assign _0257_ = _0256_ | ~(_0829_);
  assign _0258_ = _0257_ | _0893_;
  assign \decoder.corrected_d [61] = ~(_0258_ ^ \decoder.received_q [61]);
  assign _0259_ = _0097_ | ~(_0868_);
  assign _0260_ = _0259_ | ~(_0879_);
  assign _0261_ = _0260_ | ~(_0878_);
  assign _0262_ = _0261_ | ~(_0829_);
  assign _0263_ = _0262_ | ~(_0614_);
  assign \decoder.corrected_d [62] = ~(_0263_ ^ \decoder.received_q [62]);
  assign _0264_ = _0103_ | ~(_0868_);
  assign _0265_ = _0264_ | ~(_0879_);
  assign _0266_ = _0265_ | ~(_0878_);
  assign _0267_ = _0266_ | ~(_0829_);
  assign _0268_ = _0267_ | ~(_0614_);
  assign \decoder.corrected_d [64] = ~(_0268_ ^ \decoder.received_q [64]);
  assign _0269_ = _0109_ | _0868_;
  assign _0270_ = _0269_ | _0879_;
  assign _0271_ = _0270_ | ~(_0878_);
  assign _0272_ = _0271_ | ~(_0829_);
  assign _0273_ = _0272_ | _0893_;
  assign \decoder.corrected_d [65] = ~(_0273_ ^ \decoder.received_q [65]);
  assign _0274_ = _0879_ | ~(_0869_);
  assign _0275_ = _0274_ | ~(_0878_);
  assign _0276_ = _0275_ | ~(_0829_);
  assign _0277_ = _0276_ | ~(_0614_);
  assign \decoder.corrected_d [66] = ~(_0277_ ^ \decoder.received_q [66]);
  assign _0278_ = _0120_ | _0868_;
  assign _0279_ = _0278_ | _0879_;
  assign _0280_ = _0279_ | ~(_0878_);
  assign _0281_ = _0280_ | ~(_0829_);
  assign _0282_ = _0281_ | _0893_;
  assign \decoder.corrected_d [67] = ~(_0282_ ^ \decoder.received_q [67]);
  assign _0283_ = _0888_ | ~(_0871_);
  assign _0284_ = _0283_ | ~(_0878_);
  assign _0285_ = _0284_ | ~(_0829_);
  assign _0286_ = _0285_ | ~(_0614_);
  assign \decoder.corrected_d [68] = ~(_0286_ ^ \decoder.received_q [68]);
  assign _0287_ = _0899_ | _0879_;
  assign _0288_ = _0287_ | ~(_0878_);
  assign _0289_ = _0288_ | ~(_0829_);
  assign _0290_ = _0289_ | _0893_;
  assign \decoder.corrected_d [69] = ~(_0290_ ^ \decoder.received_q [69]);
  assign _0291_ = _0907_ | ~(_0871_);
  assign _0292_ = _0291_ | ~(_0878_);
  assign _0293_ = _0292_ | ~(_0829_);
  assign _0294_ = _0293_ | ~(_0614_);
  assign \decoder.corrected_d [70] = ~(_0294_ ^ \decoder.received_q [70]);
  assign _0295_ = ~(\encoder.stage2_codeword_q [1] ^ \encoder.stage2_codeword_q [0]);
  assign _0296_ = ~(\encoder.stage2_codeword_q [3] ^ \encoder.stage2_codeword_q [2]);
  assign _0297_ = ~(_0296_ ^ _0295_);
  assign _0298_ = ~(\encoder.stage2_codeword_q [5] ^ \encoder.stage2_codeword_q [4]);
  assign _0299_ = ~(\encoder.stage2_codeword_q [7] ^ \encoder.stage2_codeword_q [6]);
  assign _0300_ = ~(_0299_ ^ _0298_);
  assign _0301_ = ~(_0300_ ^ _0297_);
  assign _0302_ = ~(\encoder.stage2_codeword_q [11] ^ \encoder.stage2_codeword_q [10]);
  assign _0303_ = ~(_0302_ ^ _0793_);
  assign _0304_ = ~(\encoder.stage2_codeword_q [13] ^ \encoder.stage2_codeword_q [12]);
  assign _0305_ = ~(\encoder.stage2_codeword_q [14] ^ \encoder.stage2_codeword_q [15]);
  assign _0306_ = ~(_0305_ ^ _0304_);
  assign _0307_ = ~(_0306_ ^ _0303_);
  assign _0308_ = ~(_0307_ ^ _0301_);
  assign _0309_ = ~(\encoder.stage2_codeword_q [19] ^ \encoder.stage2_codeword_q [18]);
  assign _0310_ = ~(_0309_ ^ _0743_);
  assign _0311_ = ~(\encoder.stage2_codeword_q [21] ^ \encoder.stage2_codeword_q [20]);
  assign _0312_ = ~(\encoder.stage2_codeword_q [23] ^ \encoder.stage2_codeword_q [22]);
  assign _0313_ = ~(_0312_ ^ _0311_);
  assign _0314_ = ~(_0313_ ^ _0310_);
  assign _0315_ = ~(\encoder.stage2_codeword_q [27] ^ \encoder.stage2_codeword_q [26]);
  assign _0316_ = ~(_0315_ ^ _0750_);
  assign _0317_ = ~(\encoder.stage2_codeword_q [29] ^ \encoder.stage2_codeword_q [28]);
  assign _0318_ = ~(\encoder.stage2_codeword_q [30] ^ \encoder.stage2_codeword_q [31]);
  assign _0319_ = ~(_0318_ ^ _0317_);
  assign _0320_ = ~(_0319_ ^ _0316_);
  assign _0321_ = ~(_0320_ ^ _0314_);
  assign _0322_ = ~(_0321_ ^ _0308_);
  assign _0323_ = ~(\encoder.stage2_codeword_q [35] ^ \encoder.stage2_codeword_q [34]);
  assign _0324_ = ~(_0323_ ^ _0710_);
  assign _0325_ = ~(\encoder.stage2_codeword_q [37] ^ \encoder.stage2_codeword_q [36]);
  assign _0326_ = ~(\encoder.stage2_codeword_q [39] ^ \encoder.stage2_codeword_q [38]);
  assign _0327_ = ~(_0326_ ^ _0325_);
  assign _0328_ = ~(_0327_ ^ _0324_);
  assign _0329_ = ~(\encoder.stage2_codeword_q [43] ^ \encoder.stage2_codeword_q [42]);
  assign _0330_ = ~(_0329_ ^ _0718_);
  assign _0331_ = ~(\encoder.stage2_codeword_q [45] ^ \encoder.stage2_codeword_q [44]);
  assign _0332_ = ~(\encoder.stage2_codeword_q [46] ^ \encoder.stage2_codeword_q [47]);
  assign _0333_ = ~(_0332_ ^ _0331_);
  assign _0334_ = ~(_0333_ ^ _0330_);
  assign _0335_ = ~(_0334_ ^ _0328_);
  assign _0336_ = ~(\encoder.stage2_codeword_q [51] ^ \encoder.stage2_codeword_q [50]);
  assign _0337_ = ~(_0336_ ^ _0727_);
  assign _0338_ = ~(\encoder.stage2_codeword_q [53] ^ \encoder.stage2_codeword_q [52]);
  assign _0339_ = ~(\encoder.stage2_codeword_q [55] ^ \encoder.stage2_codeword_q [54]);
  assign _0340_ = ~(_0339_ ^ _0338_);
  assign _0341_ = ~(_0340_ ^ _0337_);
  assign _0342_ = ~(\encoder.stage2_codeword_q [59] ^ \encoder.stage2_codeword_q [58]);
  assign _0343_ = ~(_0342_ ^ _0734_);
  assign _0344_ = ~(\encoder.stage2_codeword_q [61] ^ \encoder.stage2_codeword_q [60]);
  assign _0345_ = ~(\encoder.stage2_codeword_q [63] ^ \encoder.stage2_codeword_q [62]);
  assign _0346_ = ~(_0345_ ^ _0344_);
  assign _0347_ = ~(_0346_ ^ _0343_);
  assign _0348_ = ~(_0347_ ^ _0341_);
  assign _0349_ = ~(_0348_ ^ _0335_);
  assign _0350_ = ~(_0349_ ^ _0322_);
  assign _0351_ = ~(\encoder.stage2_codeword_q [67] ^ \encoder.stage2_codeword_q [66]);
  assign _0352_ = ~(_0351_ ^ _0805_);
  assign _0353_ = ~(\encoder.stage2_codeword_q [69] ^ \encoder.stage2_codeword_q [68]);
  assign _0354_ = ~(_0353_ ^ _0662_);
  assign _0355_ = ~(_0354_ ^ _0352_);
  assign _0356_ = ~(_0355_ ^ _0350_);
  assign \decoder.overall_mismatch_d  = ~(_0356_ ^ \encoder.stage2_codeword_q [71]);
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [0] <= \encoder.positional_q [0];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [1] <= \encoder.positional_q [1];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [2] <= \encoder.positional_q [2];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [3] <= \encoder.positional_q [3];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [4] <= \encoder.positional_q [4];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [5] <= \encoder.positional_q [5];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [6] <= \encoder.positional_q [6];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [7] <= \encoder.positional_q [7];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [8] <= \encoder.positional_q [8];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [9] <= \encoder.positional_q [9];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [10] <= \encoder.positional_q [10];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [11] <= \encoder.positional_q [11];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [12] <= \encoder.positional_q [12];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [13] <= \encoder.positional_q [13];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [14] <= \encoder.positional_q [14];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [15] <= \encoder.positional_q [15];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [16] <= \encoder.positional_q [16];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [17] <= \encoder.positional_q [17];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [18] <= \encoder.positional_q [18];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [19] <= \encoder.positional_q [19];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [20] <= \encoder.positional_q [20];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [21] <= \encoder.positional_q [21];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [22] <= \encoder.positional_q [22];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [23] <= \encoder.positional_q [23];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [24] <= \encoder.positional_q [24];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [25] <= \encoder.positional_q [25];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [26] <= \encoder.positional_q [26];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [27] <= \encoder.positional_q [27];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [28] <= \encoder.positional_q [28];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [29] <= \encoder.positional_q [29];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [30] <= \encoder.positional_q [30];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [31] <= \encoder.positional_q [31];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [32] <= \encoder.positional_q [32];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [33] <= \encoder.positional_q [33];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [34] <= \encoder.positional_q [34];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [35] <= \encoder.positional_q [35];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [36] <= \encoder.positional_q [36];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [37] <= \encoder.positional_q [37];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [38] <= \encoder.positional_q [38];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [39] <= \encoder.positional_q [39];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [40] <= \encoder.positional_q [40];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [41] <= \encoder.positional_q [41];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [42] <= \encoder.positional_q [42];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [43] <= \encoder.positional_q [43];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [44] <= \encoder.positional_q [44];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [45] <= \encoder.positional_q [45];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [46] <= \encoder.positional_q [46];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [47] <= \encoder.positional_q [47];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [48] <= \encoder.positional_q [48];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [49] <= \encoder.positional_q [49];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [50] <= \encoder.positional_q [50];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [51] <= \encoder.positional_q [51];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [52] <= \encoder.positional_q [52];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [53] <= \encoder.positional_q [53];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [54] <= \encoder.positional_q [54];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [55] <= \encoder.positional_q [55];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [56] <= \encoder.positional_q [56];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [57] <= \encoder.positional_q [57];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [58] <= \encoder.positional_q [58];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [59] <= \encoder.positional_q [59];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [60] <= \encoder.positional_q [60];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [61] <= \encoder.positional_q [61];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [62] <= \encoder.positional_q [62];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [63] <= \encoder.positional_q [63];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [64] <= \encoder.positional_q [64];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [65] <= \encoder.positional_q [65];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [66] <= \encoder.positional_q [66];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [67] <= \encoder.positional_q [67];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [68] <= \encoder.positional_q [68];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [69] <= \encoder.positional_q [69];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [70] <= \encoder.positional_q [70];
  always @(posedge clk_i)
    \encoder.stage2_codeword_q [71] <= _0002_;
  always @(posedge clk_i)
    \encoder.stage2_valid_q  <= \encoder.stage1_valid_q ;
  always @(posedge clk_i)
    \encoder.stage1_valid_q  <= valid_i;
  always @(posedge clk_i)
    \encoder.positional_q [0] <= \encoder.parity_d [0];
  always @(posedge clk_i)
    \encoder.positional_q [1] <= \encoder.parity_d [1];
  always @(posedge clk_i)
    \encoder.positional_q [2] <= data_i[0];
  always @(posedge clk_i)
    \encoder.positional_q [3] <= \encoder.parity_d [2];
  always @(posedge clk_i)
    \encoder.positional_q [4] <= data_i[1];
  always @(posedge clk_i)
    \encoder.positional_q [5] <= data_i[2];
  always @(posedge clk_i)
    \encoder.positional_q [6] <= data_i[3];
  always @(posedge clk_i)
    \encoder.positional_q [7] <= \encoder.parity_d [3];
  always @(posedge clk_i)
    \encoder.positional_q [8] <= data_i[4];
  always @(posedge clk_i)
    \encoder.positional_q [9] <= data_i[5];
  always @(posedge clk_i)
    \encoder.positional_q [10] <= data_i[6];
  always @(posedge clk_i)
    \encoder.positional_q [11] <= data_i[7];
  always @(posedge clk_i)
    \encoder.positional_q [12] <= data_i[8];
  always @(posedge clk_i)
    \encoder.positional_q [13] <= data_i[9];
  always @(posedge clk_i)
    \encoder.positional_q [14] <= data_i[10];
  always @(posedge clk_i)
    \encoder.positional_q [15] <= \encoder.parity_d [4];
  always @(posedge clk_i)
    \encoder.positional_q [16] <= data_i[11];
  always @(posedge clk_i)
    \encoder.positional_q [17] <= data_i[12];
  always @(posedge clk_i)
    \encoder.positional_q [18] <= data_i[13];
  always @(posedge clk_i)
    \encoder.positional_q [19] <= data_i[14];
  always @(posedge clk_i)
    \encoder.positional_q [20] <= data_i[15];
  always @(posedge clk_i)
    \encoder.positional_q [21] <= data_i[16];
  always @(posedge clk_i)
    \encoder.positional_q [22] <= data_i[17];
  always @(posedge clk_i)
    \encoder.positional_q [23] <= data_i[18];
  always @(posedge clk_i)
    \encoder.positional_q [24] <= data_i[19];
  always @(posedge clk_i)
    \encoder.positional_q [25] <= data_i[20];
  always @(posedge clk_i)
    \encoder.positional_q [26] <= data_i[21];
  always @(posedge clk_i)
    \encoder.positional_q [27] <= data_i[22];
  always @(posedge clk_i)
    \encoder.positional_q [28] <= data_i[23];
  always @(posedge clk_i)
    \encoder.positional_q [29] <= data_i[24];
  always @(posedge clk_i)
    \encoder.positional_q [30] <= data_i[25];
  always @(posedge clk_i)
    \encoder.positional_q [31] <= \encoder.parity_d [5];
  always @(posedge clk_i)
    \encoder.positional_q [32] <= data_i[26];
  always @(posedge clk_i)
    \encoder.positional_q [33] <= data_i[27];
  always @(posedge clk_i)
    \encoder.positional_q [34] <= data_i[28];
  always @(posedge clk_i)
    \encoder.positional_q [35] <= data_i[29];
  always @(posedge clk_i)
    \encoder.positional_q [36] <= data_i[30];
  always @(posedge clk_i)
    \encoder.positional_q [37] <= data_i[31];
  always @(posedge clk_i)
    \encoder.positional_q [38] <= data_i[32];
  always @(posedge clk_i)
    \encoder.positional_q [39] <= data_i[33];
  always @(posedge clk_i)
    \encoder.positional_q [40] <= data_i[34];
  always @(posedge clk_i)
    \encoder.positional_q [41] <= data_i[35];
  always @(posedge clk_i)
    \encoder.positional_q [42] <= data_i[36];
  always @(posedge clk_i)
    \encoder.positional_q [43] <= data_i[37];
  always @(posedge clk_i)
    \encoder.positional_q [44] <= data_i[38];
  always @(posedge clk_i)
    \encoder.positional_q [45] <= data_i[39];
  always @(posedge clk_i)
    \encoder.positional_q [46] <= data_i[40];
  always @(posedge clk_i)
    \encoder.positional_q [47] <= data_i[41];
  always @(posedge clk_i)
    \encoder.positional_q [48] <= data_i[42];
  always @(posedge clk_i)
    \encoder.positional_q [49] <= data_i[43];
  always @(posedge clk_i)
    \encoder.positional_q [50] <= data_i[44];
  always @(posedge clk_i)
    \encoder.positional_q [51] <= data_i[45];
  always @(posedge clk_i)
    \encoder.positional_q [52] <= data_i[46];
  always @(posedge clk_i)
    \encoder.positional_q [53] <= data_i[47];
  always @(posedge clk_i)
    \encoder.positional_q [54] <= data_i[48];
  always @(posedge clk_i)
    \encoder.positional_q [55] <= data_i[49];
  always @(posedge clk_i)
    \encoder.positional_q [56] <= data_i[50];
  always @(posedge clk_i)
    \encoder.positional_q [57] <= data_i[51];
  always @(posedge clk_i)
    \encoder.positional_q [58] <= data_i[52];
  always @(posedge clk_i)
    \encoder.positional_q [59] <= data_i[53];
  always @(posedge clk_i)
    \encoder.positional_q [60] <= data_i[54];
  always @(posedge clk_i)
    \encoder.positional_q [61] <= data_i[55];
  always @(posedge clk_i)
    \encoder.positional_q [62] <= data_i[56];
  always @(posedge clk_i)
    \encoder.positional_q [63] <= \encoder.parity_d [6];
  always @(posedge clk_i)
    \encoder.positional_q [64] <= data_i[57];
  always @(posedge clk_i)
    \encoder.positional_q [65] <= data_i[58];
  always @(posedge clk_i)
    \encoder.positional_q [66] <= data_i[59];
  always @(posedge clk_i)
    \encoder.positional_q [67] <= data_i[60];
  always @(posedge clk_i)
    \encoder.positional_q [68] <= data_i[61];
  always @(posedge clk_i)
    \encoder.positional_q [69] <= data_i[62];
  always @(posedge clk_i)
    \encoder.positional_q [70] <= data_i[63];
  always @(posedge clk_i)
    if (_0000_) \decoder.uncorrectable_q  <= 1'h0;
    else \decoder.uncorrectable_q  <= _0001_;
  always @(posedge clk_i)
    \decoder.stage1_valid_q  <= \encoder.stage2_valid_q ;
  always @(posedge clk_i)
    \decoder.stage2_valid_q  <= \decoder.stage1_valid_q ;
  always @(posedge clk_i)
    \decoder.syndrome_q [0] <= \decoder.syndrome_d [0];
  always @(posedge clk_i)
    \decoder.syndrome_q [1] <= \decoder.syndrome_d [1];
  always @(posedge clk_i)
    \decoder.syndrome_q [2] <= \decoder.syndrome_d [2];
  always @(posedge clk_i)
    \decoder.syndrome_q [3] <= \decoder.syndrome_d [3];
  always @(posedge clk_i)
    \decoder.syndrome_q [4] <= \decoder.syndrome_d [4];
  always @(posedge clk_i)
    \decoder.syndrome_q [5] <= \decoder.syndrome_d [5];
  always @(posedge clk_i)
    \decoder.syndrome_q [6] <= \decoder.syndrome_d [6];
  always @(posedge clk_i)
    \decoder.overall_mismatch_q  <= \decoder.overall_mismatch_d ;
  reg \decoder.received_q_reg[2] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[2]  <= \encoder.stage2_codeword_q [2];
  assign \decoder.received_q [2] = \decoder.received_q_reg[2] ;
  reg \decoder.received_q_reg[4] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[4]  <= \encoder.stage2_codeword_q [4];
  assign \decoder.received_q [4] = \decoder.received_q_reg[4] ;
  reg \decoder.received_q_reg[5] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[5]  <= \encoder.stage2_codeword_q [5];
  assign \decoder.received_q [5] = \decoder.received_q_reg[5] ;
  reg \decoder.received_q_reg[6] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[6]  <= \encoder.stage2_codeword_q [6];
  assign \decoder.received_q [6] = \decoder.received_q_reg[6] ;
  reg \decoder.received_q_reg[8] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[8]  <= \encoder.stage2_codeword_q [8];
  assign \decoder.received_q [8] = \decoder.received_q_reg[8] ;
  reg \decoder.received_q_reg[9] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[9]  <= \encoder.stage2_codeword_q [9];
  assign \decoder.received_q [9] = \decoder.received_q_reg[9] ;
  reg \decoder.received_q_reg[10] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[10]  <= \encoder.stage2_codeword_q [10];
  assign \decoder.received_q [10] = \decoder.received_q_reg[10] ;
  reg \decoder.received_q_reg[11] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[11]  <= \encoder.stage2_codeword_q [11];
  assign \decoder.received_q [11] = \decoder.received_q_reg[11] ;
  reg \decoder.received_q_reg[12] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[12]  <= \encoder.stage2_codeword_q [12];
  assign \decoder.received_q [12] = \decoder.received_q_reg[12] ;
  reg \decoder.received_q_reg[13] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[13]  <= \encoder.stage2_codeword_q [13];
  assign \decoder.received_q [13] = \decoder.received_q_reg[13] ;
  reg \decoder.received_q_reg[14] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[14]  <= \encoder.stage2_codeword_q [14];
  assign \decoder.received_q [14] = \decoder.received_q_reg[14] ;
  reg \decoder.received_q_reg[16] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[16]  <= \encoder.stage2_codeword_q [16];
  assign \decoder.received_q [16] = \decoder.received_q_reg[16] ;
  reg \decoder.received_q_reg[17] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[17]  <= \encoder.stage2_codeword_q [17];
  assign \decoder.received_q [17] = \decoder.received_q_reg[17] ;
  reg \decoder.received_q_reg[18] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[18]  <= \encoder.stage2_codeword_q [18];
  assign \decoder.received_q [18] = \decoder.received_q_reg[18] ;
  reg \decoder.received_q_reg[19] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[19]  <= \encoder.stage2_codeword_q [19];
  assign \decoder.received_q [19] = \decoder.received_q_reg[19] ;
  reg \decoder.received_q_reg[20] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[20]  <= \encoder.stage2_codeword_q [20];
  assign \decoder.received_q [20] = \decoder.received_q_reg[20] ;
  reg \decoder.received_q_reg[21] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[21]  <= \encoder.stage2_codeword_q [21];
  assign \decoder.received_q [21] = \decoder.received_q_reg[21] ;
  reg \decoder.received_q_reg[22] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[22]  <= \encoder.stage2_codeword_q [22];
  assign \decoder.received_q [22] = \decoder.received_q_reg[22] ;
  reg \decoder.received_q_reg[23] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[23]  <= \encoder.stage2_codeword_q [23];
  assign \decoder.received_q [23] = \decoder.received_q_reg[23] ;
  reg \decoder.received_q_reg[24] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[24]  <= \encoder.stage2_codeword_q [24];
  assign \decoder.received_q [24] = \decoder.received_q_reg[24] ;
  reg \decoder.received_q_reg[25] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[25]  <= \encoder.stage2_codeword_q [25];
  assign \decoder.received_q [25] = \decoder.received_q_reg[25] ;
  reg \decoder.received_q_reg[26] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[26]  <= \encoder.stage2_codeword_q [26];
  assign \decoder.received_q [26] = \decoder.received_q_reg[26] ;
  reg \decoder.received_q_reg[27] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[27]  <= \encoder.stage2_codeword_q [27];
  assign \decoder.received_q [27] = \decoder.received_q_reg[27] ;
  reg \decoder.received_q_reg[28] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[28]  <= \encoder.stage2_codeword_q [28];
  assign \decoder.received_q [28] = \decoder.received_q_reg[28] ;
  reg \decoder.received_q_reg[29] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[29]  <= \encoder.stage2_codeword_q [29];
  assign \decoder.received_q [29] = \decoder.received_q_reg[29] ;
  reg \decoder.received_q_reg[30] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[30]  <= \encoder.stage2_codeword_q [30];
  assign \decoder.received_q [30] = \decoder.received_q_reg[30] ;
  reg \decoder.received_q_reg[32] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[32]  <= \encoder.stage2_codeword_q [32];
  assign \decoder.received_q [32] = \decoder.received_q_reg[32] ;
  reg \decoder.received_q_reg[33] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[33]  <= \encoder.stage2_codeword_q [33];
  assign \decoder.received_q [33] = \decoder.received_q_reg[33] ;
  reg \decoder.received_q_reg[34] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[34]  <= \encoder.stage2_codeword_q [34];
  assign \decoder.received_q [34] = \decoder.received_q_reg[34] ;
  reg \decoder.received_q_reg[35] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[35]  <= \encoder.stage2_codeword_q [35];
  assign \decoder.received_q [35] = \decoder.received_q_reg[35] ;
  reg \decoder.received_q_reg[36] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[36]  <= \encoder.stage2_codeword_q [36];
  assign \decoder.received_q [36] = \decoder.received_q_reg[36] ;
  reg \decoder.received_q_reg[37] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[37]  <= \encoder.stage2_codeword_q [37];
  assign \decoder.received_q [37] = \decoder.received_q_reg[37] ;
  reg \decoder.received_q_reg[38] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[38]  <= \encoder.stage2_codeword_q [38];
  assign \decoder.received_q [38] = \decoder.received_q_reg[38] ;
  reg \decoder.received_q_reg[39] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[39]  <= \encoder.stage2_codeword_q [39];
  assign \decoder.received_q [39] = \decoder.received_q_reg[39] ;
  reg \decoder.received_q_reg[40] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[40]  <= \encoder.stage2_codeword_q [40];
  assign \decoder.received_q [40] = \decoder.received_q_reg[40] ;
  reg \decoder.received_q_reg[41] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[41]  <= \encoder.stage2_codeword_q [41];
  assign \decoder.received_q [41] = \decoder.received_q_reg[41] ;
  reg \decoder.received_q_reg[42] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[42]  <= \encoder.stage2_codeword_q [42];
  assign \decoder.received_q [42] = \decoder.received_q_reg[42] ;
  reg \decoder.received_q_reg[43] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[43]  <= \encoder.stage2_codeword_q [43];
  assign \decoder.received_q [43] = \decoder.received_q_reg[43] ;
  reg \decoder.received_q_reg[44] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[44]  <= \encoder.stage2_codeword_q [44];
  assign \decoder.received_q [44] = \decoder.received_q_reg[44] ;
  reg \decoder.received_q_reg[45] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[45]  <= \encoder.stage2_codeword_q [45];
  assign \decoder.received_q [45] = \decoder.received_q_reg[45] ;
  reg \decoder.received_q_reg[46] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[46]  <= \encoder.stage2_codeword_q [46];
  assign \decoder.received_q [46] = \decoder.received_q_reg[46] ;
  reg \decoder.received_q_reg[47] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[47]  <= \encoder.stage2_codeword_q [47];
  assign \decoder.received_q [47] = \decoder.received_q_reg[47] ;
  reg \decoder.received_q_reg[48] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[48]  <= \encoder.stage2_codeword_q [48];
  assign \decoder.received_q [48] = \decoder.received_q_reg[48] ;
  reg \decoder.received_q_reg[49] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[49]  <= \encoder.stage2_codeword_q [49];
  assign \decoder.received_q [49] = \decoder.received_q_reg[49] ;
  reg \decoder.received_q_reg[50] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[50]  <= \encoder.stage2_codeword_q [50];
  assign \decoder.received_q [50] = \decoder.received_q_reg[50] ;
  reg \decoder.received_q_reg[51] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[51]  <= \encoder.stage2_codeword_q [51];
  assign \decoder.received_q [51] = \decoder.received_q_reg[51] ;
  reg \decoder.received_q_reg[52] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[52]  <= \encoder.stage2_codeword_q [52];
  assign \decoder.received_q [52] = \decoder.received_q_reg[52] ;
  reg \decoder.received_q_reg[53] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[53]  <= \encoder.stage2_codeword_q [53];
  assign \decoder.received_q [53] = \decoder.received_q_reg[53] ;
  reg \decoder.received_q_reg[54] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[54]  <= \encoder.stage2_codeword_q [54];
  assign \decoder.received_q [54] = \decoder.received_q_reg[54] ;
  reg \decoder.received_q_reg[55] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[55]  <= \encoder.stage2_codeword_q [55];
  assign \decoder.received_q [55] = \decoder.received_q_reg[55] ;
  reg \decoder.received_q_reg[56] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[56]  <= \encoder.stage2_codeword_q [56];
  assign \decoder.received_q [56] = \decoder.received_q_reg[56] ;
  reg \decoder.received_q_reg[57] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[57]  <= \encoder.stage2_codeword_q [57];
  assign \decoder.received_q [57] = \decoder.received_q_reg[57] ;
  reg \decoder.received_q_reg[58] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[58]  <= \encoder.stage2_codeword_q [58];
  assign \decoder.received_q [58] = \decoder.received_q_reg[58] ;
  reg \decoder.received_q_reg[59] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[59]  <= \encoder.stage2_codeword_q [59];
  assign \decoder.received_q [59] = \decoder.received_q_reg[59] ;
  reg \decoder.received_q_reg[60] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[60]  <= \encoder.stage2_codeword_q [60];
  assign \decoder.received_q [60] = \decoder.received_q_reg[60] ;
  reg \decoder.received_q_reg[61] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[61]  <= \encoder.stage2_codeword_q [61];
  assign \decoder.received_q [61] = \decoder.received_q_reg[61] ;
  reg \decoder.received_q_reg[62] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[62]  <= \encoder.stage2_codeword_q [62];
  assign \decoder.received_q [62] = \decoder.received_q_reg[62] ;
  reg \decoder.received_q_reg[64] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[64]  <= \encoder.stage2_codeword_q [64];
  assign \decoder.received_q [64] = \decoder.received_q_reg[64] ;
  reg \decoder.received_q_reg[65] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[65]  <= \encoder.stage2_codeword_q [65];
  assign \decoder.received_q [65] = \decoder.received_q_reg[65] ;
  reg \decoder.received_q_reg[66] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[66]  <= \encoder.stage2_codeword_q [66];
  assign \decoder.received_q [66] = \decoder.received_q_reg[66] ;
  reg \decoder.received_q_reg[67] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[67]  <= \encoder.stage2_codeword_q [67];
  assign \decoder.received_q [67] = \decoder.received_q_reg[67] ;
  reg \decoder.received_q_reg[68] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[68]  <= \encoder.stage2_codeword_q [68];
  assign \decoder.received_q [68] = \decoder.received_q_reg[68] ;
  reg \decoder.received_q_reg[69] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[69]  <= \encoder.stage2_codeword_q [69];
  assign \decoder.received_q [69] = \decoder.received_q_reg[69] ;
  reg \decoder.received_q_reg[70] ;
  always @(posedge clk_i)
    \decoder.received_q_reg[70]  <= \encoder.stage2_codeword_q [70];
  assign \decoder.received_q [70] = \decoder.received_q_reg[70] ;
  always @(posedge clk_i)
    \decoder.data_q [0] <= \decoder.corrected_d [2];
  always @(posedge clk_i)
    \decoder.data_q [1] <= \decoder.corrected_d [4];
  always @(posedge clk_i)
    \decoder.data_q [2] <= \decoder.corrected_d [5];
  always @(posedge clk_i)
    \decoder.data_q [3] <= \decoder.corrected_d [6];
  always @(posedge clk_i)
    \decoder.data_q [4] <= \decoder.corrected_d [8];
  always @(posedge clk_i)
    \decoder.data_q [5] <= \decoder.corrected_d [9];
  always @(posedge clk_i)
    \decoder.data_q [6] <= \decoder.corrected_d [10];
  always @(posedge clk_i)
    \decoder.data_q [7] <= \decoder.corrected_d [11];
  always @(posedge clk_i)
    \decoder.data_q [8] <= \decoder.corrected_d [12];
  always @(posedge clk_i)
    \decoder.data_q [9] <= \decoder.corrected_d [13];
  always @(posedge clk_i)
    \decoder.data_q [10] <= \decoder.corrected_d [14];
  always @(posedge clk_i)
    \decoder.data_q [11] <= \decoder.corrected_d [16];
  always @(posedge clk_i)
    \decoder.data_q [12] <= \decoder.corrected_d [17];
  always @(posedge clk_i)
    \decoder.data_q [13] <= \decoder.corrected_d [18];
  always @(posedge clk_i)
    \decoder.data_q [14] <= \decoder.corrected_d [19];
  always @(posedge clk_i)
    \decoder.data_q [15] <= \decoder.corrected_d [20];
  always @(posedge clk_i)
    \decoder.data_q [16] <= \decoder.corrected_d [21];
  always @(posedge clk_i)
    \decoder.data_q [17] <= \decoder.corrected_d [22];
  always @(posedge clk_i)
    \decoder.data_q [18] <= \decoder.corrected_d [23];
  always @(posedge clk_i)
    \decoder.data_q [19] <= \decoder.corrected_d [24];
  always @(posedge clk_i)
    \decoder.data_q [20] <= \decoder.corrected_d [25];
  always @(posedge clk_i)
    \decoder.data_q [21] <= \decoder.corrected_d [26];
  always @(posedge clk_i)
    \decoder.data_q [22] <= \decoder.corrected_d [27];
  always @(posedge clk_i)
    \decoder.data_q [23] <= \decoder.corrected_d [28];
  always @(posedge clk_i)
    \decoder.data_q [24] <= \decoder.corrected_d [29];
  always @(posedge clk_i)
    \decoder.data_q [25] <= \decoder.corrected_d [30];
  always @(posedge clk_i)
    \decoder.data_q [26] <= \decoder.corrected_d [32];
  always @(posedge clk_i)
    \decoder.data_q [27] <= \decoder.corrected_d [33];
  always @(posedge clk_i)
    \decoder.data_q [28] <= \decoder.corrected_d [34];
  always @(posedge clk_i)
    \decoder.data_q [29] <= \decoder.corrected_d [35];
  always @(posedge clk_i)
    \decoder.data_q [30] <= \decoder.corrected_d [36];
  always @(posedge clk_i)
    \decoder.data_q [31] <= \decoder.corrected_d [37];
  always @(posedge clk_i)
    \decoder.data_q [32] <= \decoder.corrected_d [38];
  always @(posedge clk_i)
    \decoder.data_q [33] <= \decoder.corrected_d [39];
  always @(posedge clk_i)
    \decoder.data_q [34] <= \decoder.corrected_d [40];
  always @(posedge clk_i)
    \decoder.data_q [35] <= \decoder.corrected_d [41];
  always @(posedge clk_i)
    \decoder.data_q [36] <= \decoder.corrected_d [42];
  always @(posedge clk_i)
    \decoder.data_q [37] <= \decoder.corrected_d [43];
  always @(posedge clk_i)
    \decoder.data_q [38] <= \decoder.corrected_d [44];
  always @(posedge clk_i)
    \decoder.data_q [39] <= \decoder.corrected_d [45];
  always @(posedge clk_i)
    \decoder.data_q [40] <= \decoder.corrected_d [46];
  always @(posedge clk_i)
    \decoder.data_q [41] <= \decoder.corrected_d [47];
  always @(posedge clk_i)
    \decoder.data_q [42] <= \decoder.corrected_d [48];
  always @(posedge clk_i)
    \decoder.data_q [43] <= \decoder.corrected_d [49];
  always @(posedge clk_i)
    \decoder.data_q [44] <= \decoder.corrected_d [50];
  always @(posedge clk_i)
    \decoder.data_q [45] <= \decoder.corrected_d [51];
  always @(posedge clk_i)
    \decoder.data_q [46] <= \decoder.corrected_d [52];
  always @(posedge clk_i)
    \decoder.data_q [47] <= \decoder.corrected_d [53];
  always @(posedge clk_i)
    \decoder.data_q [48] <= \decoder.corrected_d [54];
  always @(posedge clk_i)
    \decoder.data_q [49] <= \decoder.corrected_d [55];
  always @(posedge clk_i)
    \decoder.data_q [50] <= \decoder.corrected_d [56];
  always @(posedge clk_i)
    \decoder.data_q [51] <= \decoder.corrected_d [57];
  always @(posedge clk_i)
    \decoder.data_q [52] <= \decoder.corrected_d [58];
  always @(posedge clk_i)
    \decoder.data_q [53] <= \decoder.corrected_d [59];
  always @(posedge clk_i)
    \decoder.data_q [54] <= \decoder.corrected_d [60];
  always @(posedge clk_i)
    \decoder.data_q [55] <= \decoder.corrected_d [61];
  always @(posedge clk_i)
    \decoder.data_q [56] <= \decoder.corrected_d [62];
  always @(posedge clk_i)
    \decoder.data_q [57] <= \decoder.corrected_d [64];
  always @(posedge clk_i)
    \decoder.data_q [58] <= \decoder.corrected_d [65];
  always @(posedge clk_i)
    \decoder.data_q [59] <= \decoder.corrected_d [66];
  always @(posedge clk_i)
    \decoder.data_q [60] <= \decoder.corrected_d [67];
  always @(posedge clk_i)
    \decoder.data_q [61] <= \decoder.corrected_d [68];
  always @(posedge clk_i)
    \decoder.data_q [62] <= \decoder.corrected_d [69];
  always @(posedge clk_i)
    \decoder.data_q [63] <= \decoder.corrected_d [70];
  always @(posedge clk_i)
    \decoder.detected_q  <= \decoder.detected_d ;
  always @(posedge clk_i)
    \decoder.corrected_flag_q  <= \decoder.corrected_flag_d ;
  assign codeword_o = \encoder.stage2_codeword_q ;
  assign corrected_o = \decoder.corrected_flag_q ;
  assign data_o = \decoder.data_q ;
  assign \decoder.clk_i  = clk_i;
  assign \decoder.codeword_i  = \encoder.stage2_codeword_q ;
  assign \decoder.corrected_d [71] = 1'hx;
  assign \decoder.correction_mask_d [71] = 1'hx;
  assign \decoder.data_d  = { \decoder.corrected_d [70:64], \decoder.corrected_d [62:32], \decoder.corrected_d [30:16], \decoder.corrected_d [14:8], \decoder.corrected_d [6:4], \decoder.corrected_d [2] };
  assign \decoder.data_index  = 32'd64;
  assign \decoder.data_o  = \decoder.data_q ;
  assign \decoder.err_corrected_o  = \decoder.corrected_flag_q ;
  assign \decoder.err_detected_o  = \decoder.detected_q ;
  assign \decoder.err_uncorrectable_o  = \decoder.uncorrectable_q ;
  assign \decoder.error_position  = { 25'h0000000, \decoder.syndrome_q  };
  assign \decoder.group_index  = 32'd9;
  assign \decoder.group_offset  = 32'd8;
  assign \decoder.parity_index  = 32'd7;
  assign \decoder.position  = 32'd72;
  assign \decoder.received_q [71] = 1'hx;
  assign { \decoder.syndrome_group[3] [8], \decoder.syndrome_group[3] [6], \decoder.syndrome_group[3] [4], \decoder.syndrome_group[3] [2], \decoder.syndrome_group[3] [0] } = { 1'h0, \encoder.stage2_codeword_q [55], \encoder.stage2_codeword_q [39], \encoder.stage2_codeword_q [23], \encoder.stage2_codeword_q [7] };
  assign { \decoder.syndrome_group[4] [8:7], \decoder.syndrome_group[4] [5:3], \decoder.syndrome_group[4] [1:0] } = { 1'h0, \decoder.syndrome_group[3] [7], \encoder.stage2_codeword_q [47], 1'h0, \decoder.syndrome_group[3] [3], \encoder.stage2_codeword_q [15], 1'h0 };
  assign { \decoder.syndrome_group[5] [8:6], \decoder.syndrome_group[5] [3:0] } = { 1'h0, \decoder.syndrome_group[3] [7], \decoder.syndrome_group[4] [6], \encoder.stage2_codeword_q [31], 3'h0 };
  assign \decoder.syndrome_group[6] [7:0] = { \encoder.stage2_codeword_q [63], 7'h00 };
  assign \decoder.valid_i  = \encoder.stage2_valid_q ;
  assign \decoder.valid_o  = \decoder.stage2_valid_q ;
  assign detected_o = \decoder.detected_q ;
  assign \encoder.clk_i  = clk_i;
  assign \encoder.codeword_o  = \encoder.stage2_codeword_q ;
  assign \encoder.data_i  = data_i;
  assign \encoder.data_index  = 32'd64;
  assign \encoder.group_index  = 32'd9;
  assign \encoder.group_offset  = 32'd8;
  assign { \encoder.parity_group[3] [8], \encoder.parity_group[3] [6], \encoder.parity_group[3] [4], \encoder.parity_group[3] [2], \encoder.parity_group[3] [0] } = { 1'h0, data_i[49], data_i[33], data_i[18], 1'h0 };
  assign { \encoder.parity_group[4] [8:7], \encoder.parity_group[4] [5:3], \encoder.parity_group[4] [1:0] } = { 1'h0, \encoder.parity_group[3] [7], data_i[41], 1'h0, \encoder.parity_group[3] [3], 2'h0 };
  assign { \encoder.parity_group[5] [8:6], \encoder.parity_group[5] [3:0] } = { 1'h0, \encoder.parity_group[3] [7], \encoder.parity_group[4] [6], 4'h0 };
  assign \encoder.parity_group[6]  = { \encoder.parity_d [6], 8'h00 };
  assign \encoder.parity_index  = 32'd7;
  assign \encoder.position  = 32'd72;
  assign \encoder.positional_d  = { data_i[63:57], \encoder.parity_d [6], data_i[56:26], \encoder.parity_d [5], data_i[25:11], \encoder.parity_d [4], data_i[10:4], \encoder.parity_d [3], data_i[3:1], \encoder.parity_d [2], data_i[0], \encoder.parity_d [1:0] };
  assign \encoder.valid_i  = valid_i;
  assign \encoder.valid_o  = \encoder.stage2_valid_q ;
  assign encoder_valid = \encoder.stage2_valid_q ;
  assign uncorrectable_o = \decoder.uncorrectable_q ;
  assign valid_o = \decoder.stage2_valid_q ;
endmodule
