/* Generated by Yosys 0.30+48 (git sha1 b5b0b7e83, x86_64-w64-mingw32-g++ 13.1.0 -march=nocona -msahf -mtune=generic -O2 -Os) */

module secded_pipelined_72_64_v1_encoder(clk_i, valid_i, data_i, valid_o, codeword_o);
  wire [71:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  input clk_i;
  wire clk_i;
  output [71:0] codeword_o;
  wire [71:0] codeword_o;
  input [63:0] data_i;
  wire [63:0] data_i;
  wire [31:0] data_index;
  wire [31:0] group_index;
  wire [31:0] group_offset;
  wire [6:0] parity_d;
  wire [7:0] \parity_group[3] ;
  wire [6:0] \parity_group[4] ;
  wire [8:0] \parity_group[5] ;
  wire [8:0] \parity_group[6] ;
  wire [31:0] parity_index;
  wire [31:0] position;
  wire [70:0] positional_d;
  reg [70:0] positional_q;
  reg stage1_valid_q;
  reg [71:0] stage2_codeword_q;
  reg stage2_valid_q;
  input valid_i;
  wire valid_i;
  output valid_o;
  wire valid_o;
  assign _001_ = ~(data_i[1] ^ data_i[0]);
  assign _002_ = ~(_001_ ^ data_i[3]);
  assign _003_ = ~data_i[10];
  assign _004_ = ~data_i[8];
  assign _005_ = ~(data_i[6] ^ data_i[4]);
  assign _006_ = ~(_005_ ^ _004_);
  assign _007_ = ~(_006_ ^ _003_);
  assign _008_ = ~(_007_ ^ _002_);
  assign _009_ = ~data_i[17];
  assign _010_ = ~data_i[15];
  assign _011_ = ~(data_i[13] ^ data_i[11]);
  assign _012_ = ~(_011_ ^ _010_);
  assign _013_ = ~(_012_ ^ _009_);
  assign _014_ = ~data_i[25];
  assign _015_ = ~data_i[23];
  assign _016_ = ~(data_i[21] ^ data_i[19]);
  assign _017_ = ~(_016_ ^ _015_);
  assign _018_ = ~(_017_ ^ _014_);
  assign _019_ = ~(_018_ ^ _013_);
  assign _020_ = ~(_019_ ^ _008_);
  assign _021_ = ~data_i[32];
  assign _022_ = ~data_i[30];
  assign _023_ = ~(data_i[28] ^ data_i[26]);
  assign _024_ = ~(_023_ ^ _022_);
  assign _025_ = ~(_024_ ^ _021_);
  assign _026_ = ~data_i[40];
  assign _027_ = ~data_i[38];
  assign _028_ = ~(data_i[36] ^ data_i[34]);
  assign _029_ = ~(_028_ ^ _027_);
  assign _030_ = ~(_029_ ^ _026_);
  assign _031_ = ~(_030_ ^ _025_);
  assign _032_ = ~data_i[48];
  assign _033_ = ~data_i[46];
  assign _034_ = ~(data_i[44] ^ data_i[42]);
  assign _035_ = ~(_034_ ^ _033_);
  assign _036_ = ~(_035_ ^ _032_);
  assign _037_ = ~data_i[56];
  assign _038_ = ~data_i[54];
  assign _039_ = ~(data_i[52] ^ data_i[50]);
  assign _040_ = ~(_039_ ^ _038_);
  assign _041_ = ~(_040_ ^ _037_);
  assign _042_ = ~(_041_ ^ _036_);
  assign _043_ = ~(_042_ ^ _031_);
  assign _044_ = ~(_043_ ^ _020_);
  assign _045_ = ~data_i[63];
  assign _046_ = ~data_i[61];
  assign _047_ = ~(data_i[59] ^ data_i[57]);
  assign _048_ = ~(_047_ ^ _046_);
  assign _049_ = ~(_048_ ^ _045_);
  assign parity_d[0] = ~(_049_ ^ _044_);
  assign _050_ = ~(data_i[2] ^ data_i[0]);
  assign _051_ = ~(_050_ ^ data_i[3]);
  assign _052_ = ~data_i[9];
  assign _053_ = ~(data_i[6] ^ data_i[5]);
  assign _054_ = ~(_053_ ^ _052_);
  assign _055_ = ~(_054_ ^ _003_);
  assign _056_ = ~(_055_ ^ _051_);
  assign _057_ = ~data_i[16];
  assign _058_ = ~(data_i[12] ^ data_i[13]);
  assign _059_ = ~(_058_ ^ _057_);
  assign _060_ = ~(_059_ ^ _009_);
  assign _061_ = ~data_i[24];
  assign _062_ = ~(data_i[20] ^ data_i[21]);
  assign _063_ = ~(_062_ ^ _061_);
  assign _064_ = ~(_063_ ^ _014_);
  assign _065_ = ~(_064_ ^ _060_);
  assign _066_ = ~(_065_ ^ _056_);
  assign _067_ = ~data_i[31];
  assign _068_ = ~(data_i[27] ^ data_i[28]);
  assign _069_ = ~(_068_ ^ _067_);
  assign _070_ = ~(_069_ ^ _021_);
  assign _071_ = ~data_i[39];
  assign _072_ = ~(data_i[35] ^ data_i[36]);
  assign _073_ = ~(_072_ ^ _071_);
  assign _074_ = ~(_073_ ^ _026_);
  assign _075_ = ~(_074_ ^ _070_);
  assign _076_ = ~data_i[47];
  assign _077_ = ~(data_i[43] ^ data_i[44]);
  assign _078_ = ~(_077_ ^ _076_);
  assign _079_ = ~(_078_ ^ _032_);
  assign _080_ = ~data_i[55];
  assign _081_ = ~(data_i[52] ^ data_i[51]);
  assign _082_ = ~(_081_ ^ _080_);
  assign _083_ = ~(_082_ ^ _037_);
  assign _084_ = ~(_083_ ^ _079_);
  assign _085_ = ~(_084_ ^ _075_);
  assign _086_ = ~(_085_ ^ _066_);
  assign _087_ = ~data_i[62];
  assign _088_ = ~(data_i[59] ^ data_i[58]);
  assign _089_ = ~(_088_ ^ _087_);
  assign _090_ = ~(_089_ ^ _045_);
  assign parity_d[1] = ~(_090_ ^ _086_);
  assign _091_ = ~(data_i[2] ^ data_i[1]);
  assign _092_ = ~(_091_ ^ data_i[3]);
  assign _093_ = ~(data_i[7] ^ data_i[8]);
  assign _094_ = ~(_093_ ^ _052_);
  assign _095_ = ~(_094_ ^ _003_);
  assign _096_ = ~(_095_ ^ _092_);
  assign _097_ = ~(data_i[14] ^ data_i[15]);
  assign _098_ = ~(_097_ ^ _057_);
  assign _099_ = ~(_098_ ^ _009_);
  assign _100_ = ~(data_i[22] ^ data_i[23]);
  assign _101_ = ~(_100_ ^ _061_);
  assign _102_ = ~(_101_ ^ _014_);
  assign _103_ = ~(_102_ ^ _099_);
  assign _104_ = ~(_103_ ^ _096_);
  assign _105_ = ~(data_i[29] ^ data_i[30]);
  assign _106_ = ~(_105_ ^ _067_);
  assign _107_ = ~(_106_ ^ _021_);
  assign _108_ = ~(data_i[37] ^ data_i[38]);
  assign _109_ = ~(_108_ ^ _071_);
  assign _110_ = ~(_109_ ^ _026_);
  assign _111_ = ~(_110_ ^ _107_);
  assign _112_ = ~(data_i[45] ^ data_i[46]);
  assign _113_ = ~(_112_ ^ _076_);
  assign _114_ = ~(_113_ ^ _032_);
  assign _115_ = ~(data_i[53] ^ data_i[54]);
  assign _116_ = ~(_115_ ^ _080_);
  assign _117_ = ~(_116_ ^ _037_);
  assign _118_ = ~(_117_ ^ _114_);
  assign _119_ = ~(_118_ ^ _111_);
  assign _120_ = ~(_119_ ^ _104_);
  assign _121_ = ~(data_i[60] ^ data_i[61]);
  assign _122_ = ~(_121_ ^ _087_);
  assign _123_ = ~(_122_ ^ _045_);
  assign parity_d[2] = ~(_123_ ^ _120_);
  assign _124_ = ~(data_i[5] ^ data_i[4]);
  assign _125_ = ~(_124_ ^ data_i[6]);
  assign _126_ = ~(_125_ ^ data_i[7]);
  assign _127_ = ~(_126_ ^ _004_);
  assign _128_ = ~(_127_ ^ _052_);
  assign _129_ = ~(_128_ ^ data_i[10]);
  assign _130_ = ~(data_i[20] ^ data_i[19]);
  assign _131_ = ~(_130_ ^ data_i[21]);
  assign _132_ = ~(_131_ ^ data_i[22]);
  assign _133_ = ~(_132_ ^ _015_);
  assign _134_ = ~(_133_ ^ _061_);
  assign _135_ = ~(_134_ ^ data_i[25]);
  assign _136_ = ~(_135_ ^ data_i[18]);
  assign _137_ = ~(_136_ ^ _129_);
  assign _138_ = ~data_i[33];
  assign _139_ = ~(data_i[35] ^ data_i[34]);
  assign _140_ = ~(_139_ ^ data_i[36]);
  assign _141_ = ~(_140_ ^ data_i[37]);
  assign _142_ = ~(_141_ ^ _027_);
  assign _143_ = ~(_142_ ^ _071_);
  assign _144_ = ~(_143_ ^ _026_);
  assign _145_ = ~(_144_ ^ _138_);
  assign _146_ = ~data_i[49];
  assign _147_ = ~(data_i[51] ^ data_i[50]);
  assign _148_ = ~(_147_ ^ data_i[52]);
  assign _149_ = ~(_148_ ^ data_i[53]);
  assign _150_ = ~(_149_ ^ _038_);
  assign _151_ = ~(_150_ ^ _080_);
  assign _152_ = ~(_151_ ^ _037_);
  assign _153_ = ~(_152_ ^ _146_);
  assign _154_ = ~(_153_ ^ _145_);
  assign parity_d[3] = ~(_154_ ^ _137_);
  assign _155_ = ~(data_i[12] ^ data_i[11]);
  assign _156_ = ~(_155_ ^ data_i[13]);
  assign _157_ = ~(_156_ ^ data_i[14]);
  assign _158_ = ~(_157_ ^ _010_);
  assign _159_ = ~(_158_ ^ _057_);
  assign _160_ = ~(_159_ ^ data_i[17]);
  assign _161_ = ~(_160_ ^ data_i[18]);
  assign _162_ = ~(_161_ ^ _135_);
  assign _163_ = ~(data_i[43] ^ data_i[42]);
  assign _164_ = ~(_163_ ^ data_i[44]);
  assign _165_ = ~(_164_ ^ data_i[45]);
  assign _166_ = ~(_165_ ^ _033_);
  assign _167_ = ~(_166_ ^ _076_);
  assign _168_ = ~(_167_ ^ _032_);
  assign _169_ = ~(_168_ ^ _146_);
  assign _170_ = _169_ ^ _152_;
  assign _171_ = ~(_170_ ^ data_i[41]);
  assign parity_d[4] = ~(_171_ ^ _162_);
  assign _172_ = ~(data_i[27] ^ data_i[26]);
  assign _173_ = ~(_172_ ^ data_i[28]);
  assign _174_ = ~(_173_ ^ data_i[29]);
  assign _175_ = ~(_174_ ^ _022_);
  assign _176_ = ~(_175_ ^ _067_);
  assign _177_ = ~(_176_ ^ _021_);
  assign _178_ = ~(_177_ ^ _138_);
  assign _179_ = _144_ ^ data_i[41];
  assign _180_ = ~(_179_ ^ _178_);
  assign parity_d[5] = ~(_180_ ^ _170_);
  assign _181_ = positional_q[1] ^ positional_q[0];
  assign _182_ = ~(positional_q[3] ^ positional_q[2]);
  assign _183_ = ~(_182_ ^ _181_);
  assign _184_ = ~(positional_q[5] ^ positional_q[4]);
  assign _185_ = ~(positional_q[7] ^ positional_q[6]);
  assign _186_ = ~(_185_ ^ _184_);
  assign _187_ = ~(_186_ ^ _183_);
  assign _188_ = ~(positional_q[9] ^ positional_q[8]);
  assign _189_ = ~(positional_q[11] ^ positional_q[10]);
  assign _190_ = ~(_189_ ^ _188_);
  assign _191_ = ~(positional_q[13] ^ positional_q[12]);
  assign _192_ = ~(positional_q[15] ^ positional_q[14]);
  assign _193_ = ~(_192_ ^ _191_);
  assign _194_ = ~(_193_ ^ _190_);
  assign _195_ = ~(_194_ ^ _187_);
  assign _196_ = ~(positional_q[17] ^ positional_q[16]);
  assign _197_ = ~(positional_q[19] ^ positional_q[18]);
  assign _198_ = ~(_197_ ^ _196_);
  assign _199_ = ~(positional_q[21] ^ positional_q[20]);
  assign _200_ = ~(positional_q[23] ^ positional_q[22]);
  assign _201_ = ~(_200_ ^ _199_);
  assign _202_ = ~(_201_ ^ _198_);
  assign _203_ = ~(positional_q[25] ^ positional_q[24]);
  assign _204_ = ~(positional_q[27] ^ positional_q[26]);
  assign _205_ = ~(_204_ ^ _203_);
  assign _206_ = ~(positional_q[29] ^ positional_q[28]);
  assign _207_ = ~(positional_q[31] ^ positional_q[30]);
  assign _208_ = ~(_207_ ^ _206_);
  assign _209_ = ~(_208_ ^ _205_);
  assign _210_ = ~(_209_ ^ _202_);
  assign _211_ = ~(_210_ ^ _195_);
  assign _212_ = ~(positional_q[33] ^ positional_q[32]);
  assign _213_ = ~(positional_q[35] ^ positional_q[34]);
  assign _214_ = ~(_213_ ^ _212_);
  assign _215_ = ~(positional_q[37] ^ positional_q[36]);
  assign _216_ = ~(positional_q[39] ^ positional_q[38]);
  assign _217_ = ~(_216_ ^ _215_);
  assign _218_ = ~(_217_ ^ _214_);
  assign _219_ = ~(positional_q[41] ^ positional_q[40]);
  assign _220_ = ~(positional_q[43] ^ positional_q[42]);
  assign _221_ = ~(_220_ ^ _219_);
  assign _222_ = ~(positional_q[45] ^ positional_q[44]);
  assign _223_ = ~(positional_q[47] ^ positional_q[46]);
  assign _224_ = ~(_223_ ^ _222_);
  assign _225_ = ~(_224_ ^ _221_);
  assign _226_ = ~(_225_ ^ _218_);
  assign _227_ = ~(positional_q[49] ^ positional_q[48]);
  assign _228_ = ~(positional_q[51] ^ positional_q[50]);
  assign _229_ = ~(_228_ ^ _227_);
  assign _230_ = ~(positional_q[53] ^ positional_q[52]);
  assign _231_ = ~(positional_q[55] ^ positional_q[54]);
  assign _232_ = ~(_231_ ^ _230_);
  assign _233_ = ~(_232_ ^ _229_);
  assign _234_ = ~(positional_q[57] ^ positional_q[56]);
  assign _235_ = ~(positional_q[59] ^ positional_q[58]);
  assign _236_ = ~(_235_ ^ _234_);
  assign _237_ = ~(positional_q[61] ^ positional_q[60]);
  assign _238_ = ~(positional_q[63] ^ positional_q[62]);
  assign _239_ = ~(_238_ ^ _237_);
  assign _240_ = ~(_239_ ^ _236_);
  assign _241_ = ~(_240_ ^ _233_);
  assign _242_ = ~(_241_ ^ _226_);
  assign _243_ = ~(_242_ ^ _211_);
  assign _244_ = ~(positional_q[65] ^ positional_q[64]);
  assign _245_ = ~(positional_q[67] ^ positional_q[66]);
  assign _246_ = ~(_245_ ^ _244_);
  assign _247_ = positional_q[69] ^ positional_q[68];
  assign _248_ = ~(_247_ ^ positional_q[70]);
  assign _249_ = ~(_248_ ^ _246_);
  assign _000_[71] = ~(_249_ ^ _243_);
  assign _250_ = ~(data_i[58] ^ data_i[57]);
  assign _251_ = ~(_250_ ^ data_i[59]);
  assign _252_ = ~(_251_ ^ data_i[60]);
  assign _253_ = ~(_252_ ^ _046_);
  assign _254_ = ~(_253_ ^ _087_);
  assign parity_d[6] = ~(_254_ ^ data_i[63]);
  always @(posedge clk_i)
    stage2_codeword_q[0] <= positional_q[0];
  always @(posedge clk_i)
    stage2_codeword_q[1] <= positional_q[1];
  always @(posedge clk_i)
    stage2_codeword_q[2] <= positional_q[2];
  always @(posedge clk_i)
    stage2_codeword_q[3] <= positional_q[3];
  always @(posedge clk_i)
    stage2_codeword_q[4] <= positional_q[4];
  always @(posedge clk_i)
    stage2_codeword_q[5] <= positional_q[5];
  always @(posedge clk_i)
    stage2_codeword_q[6] <= positional_q[6];
  always @(posedge clk_i)
    stage2_codeword_q[7] <= positional_q[7];
  always @(posedge clk_i)
    stage2_codeword_q[8] <= positional_q[8];
  always @(posedge clk_i)
    stage2_codeword_q[9] <= positional_q[9];
  always @(posedge clk_i)
    stage2_codeword_q[10] <= positional_q[10];
  always @(posedge clk_i)
    stage2_codeword_q[11] <= positional_q[11];
  always @(posedge clk_i)
    stage2_codeword_q[12] <= positional_q[12];
  always @(posedge clk_i)
    stage2_codeword_q[13] <= positional_q[13];
  always @(posedge clk_i)
    stage2_codeword_q[14] <= positional_q[14];
  always @(posedge clk_i)
    stage2_codeword_q[15] <= positional_q[15];
  always @(posedge clk_i)
    stage2_codeword_q[16] <= positional_q[16];
  always @(posedge clk_i)
    stage2_codeword_q[17] <= positional_q[17];
  always @(posedge clk_i)
    stage2_codeword_q[18] <= positional_q[18];
  always @(posedge clk_i)
    stage2_codeword_q[19] <= positional_q[19];
  always @(posedge clk_i)
    stage2_codeword_q[20] <= positional_q[20];
  always @(posedge clk_i)
    stage2_codeword_q[21] <= positional_q[21];
  always @(posedge clk_i)
    stage2_codeword_q[22] <= positional_q[22];
  always @(posedge clk_i)
    stage2_codeword_q[23] <= positional_q[23];
  always @(posedge clk_i)
    stage2_codeword_q[24] <= positional_q[24];
  always @(posedge clk_i)
    stage2_codeword_q[25] <= positional_q[25];
  always @(posedge clk_i)
    stage2_codeword_q[26] <= positional_q[26];
  always @(posedge clk_i)
    stage2_codeword_q[27] <= positional_q[27];
  always @(posedge clk_i)
    stage2_codeword_q[28] <= positional_q[28];
  always @(posedge clk_i)
    stage2_codeword_q[29] <= positional_q[29];
  always @(posedge clk_i)
    stage2_codeword_q[30] <= positional_q[30];
  always @(posedge clk_i)
    stage2_codeword_q[31] <= positional_q[31];
  always @(posedge clk_i)
    stage2_codeword_q[32] <= positional_q[32];
  always @(posedge clk_i)
    stage2_codeword_q[33] <= positional_q[33];
  always @(posedge clk_i)
    stage2_codeword_q[34] <= positional_q[34];
  always @(posedge clk_i)
    stage2_codeword_q[35] <= positional_q[35];
  always @(posedge clk_i)
    stage2_codeword_q[36] <= positional_q[36];
  always @(posedge clk_i)
    stage2_codeword_q[37] <= positional_q[37];
  always @(posedge clk_i)
    stage2_codeword_q[38] <= positional_q[38];
  always @(posedge clk_i)
    stage2_codeword_q[39] <= positional_q[39];
  always @(posedge clk_i)
    stage2_codeword_q[40] <= positional_q[40];
  always @(posedge clk_i)
    stage2_codeword_q[41] <= positional_q[41];
  always @(posedge clk_i)
    stage2_codeword_q[42] <= positional_q[42];
  always @(posedge clk_i)
    stage2_codeword_q[43] <= positional_q[43];
  always @(posedge clk_i)
    stage2_codeword_q[44] <= positional_q[44];
  always @(posedge clk_i)
    stage2_codeword_q[45] <= positional_q[45];
  always @(posedge clk_i)
    stage2_codeword_q[46] <= positional_q[46];
  always @(posedge clk_i)
    stage2_codeword_q[47] <= positional_q[47];
  always @(posedge clk_i)
    stage2_codeword_q[48] <= positional_q[48];
  always @(posedge clk_i)
    stage2_codeword_q[49] <= positional_q[49];
  always @(posedge clk_i)
    stage2_codeword_q[50] <= positional_q[50];
  always @(posedge clk_i)
    stage2_codeword_q[51] <= positional_q[51];
  always @(posedge clk_i)
    stage2_codeword_q[52] <= positional_q[52];
  always @(posedge clk_i)
    stage2_codeword_q[53] <= positional_q[53];
  always @(posedge clk_i)
    stage2_codeword_q[54] <= positional_q[54];
  always @(posedge clk_i)
    stage2_codeword_q[55] <= positional_q[55];
  always @(posedge clk_i)
    stage2_codeword_q[56] <= positional_q[56];
  always @(posedge clk_i)
    stage2_codeword_q[57] <= positional_q[57];
  always @(posedge clk_i)
    stage2_codeword_q[58] <= positional_q[58];
  always @(posedge clk_i)
    stage2_codeword_q[59] <= positional_q[59];
  always @(posedge clk_i)
    stage2_codeword_q[60] <= positional_q[60];
  always @(posedge clk_i)
    stage2_codeword_q[61] <= positional_q[61];
  always @(posedge clk_i)
    stage2_codeword_q[62] <= positional_q[62];
  always @(posedge clk_i)
    stage2_codeword_q[63] <= positional_q[63];
  always @(posedge clk_i)
    stage2_codeword_q[64] <= positional_q[64];
  always @(posedge clk_i)
    stage2_codeword_q[65] <= positional_q[65];
  always @(posedge clk_i)
    stage2_codeword_q[66] <= positional_q[66];
  always @(posedge clk_i)
    stage2_codeword_q[67] <= positional_q[67];
  always @(posedge clk_i)
    stage2_codeword_q[68] <= positional_q[68];
  always @(posedge clk_i)
    stage2_codeword_q[69] <= positional_q[69];
  always @(posedge clk_i)
    stage2_codeword_q[70] <= positional_q[70];
  always @(posedge clk_i)
    stage2_codeword_q[71] <= _000_[71];
  always @(posedge clk_i)
    stage2_valid_q <= stage1_valid_q;
  always @(posedge clk_i)
    stage1_valid_q <= valid_i;
  always @(posedge clk_i)
    positional_q[0] <= parity_d[0];
  always @(posedge clk_i)
    positional_q[1] <= parity_d[1];
  always @(posedge clk_i)
    positional_q[2] <= data_i[0];
  always @(posedge clk_i)
    positional_q[3] <= parity_d[2];
  always @(posedge clk_i)
    positional_q[4] <= data_i[1];
  always @(posedge clk_i)
    positional_q[5] <= data_i[2];
  always @(posedge clk_i)
    positional_q[6] <= data_i[3];
  always @(posedge clk_i)
    positional_q[7] <= parity_d[3];
  always @(posedge clk_i)
    positional_q[8] <= data_i[4];
  always @(posedge clk_i)
    positional_q[9] <= data_i[5];
  always @(posedge clk_i)
    positional_q[10] <= data_i[6];
  always @(posedge clk_i)
    positional_q[11] <= data_i[7];
  always @(posedge clk_i)
    positional_q[12] <= data_i[8];
  always @(posedge clk_i)
    positional_q[13] <= data_i[9];
  always @(posedge clk_i)
    positional_q[14] <= data_i[10];
  always @(posedge clk_i)
    positional_q[15] <= parity_d[4];
  always @(posedge clk_i)
    positional_q[16] <= data_i[11];
  always @(posedge clk_i)
    positional_q[17] <= data_i[12];
  always @(posedge clk_i)
    positional_q[18] <= data_i[13];
  always @(posedge clk_i)
    positional_q[19] <= data_i[14];
  always @(posedge clk_i)
    positional_q[20] <= data_i[15];
  always @(posedge clk_i)
    positional_q[21] <= data_i[16];
  always @(posedge clk_i)
    positional_q[22] <= data_i[17];
  always @(posedge clk_i)
    positional_q[23] <= data_i[18];
  always @(posedge clk_i)
    positional_q[24] <= data_i[19];
  always @(posedge clk_i)
    positional_q[25] <= data_i[20];
  always @(posedge clk_i)
    positional_q[26] <= data_i[21];
  always @(posedge clk_i)
    positional_q[27] <= data_i[22];
  always @(posedge clk_i)
    positional_q[28] <= data_i[23];
  always @(posedge clk_i)
    positional_q[29] <= data_i[24];
  always @(posedge clk_i)
    positional_q[30] <= data_i[25];
  always @(posedge clk_i)
    positional_q[31] <= parity_d[5];
  always @(posedge clk_i)
    positional_q[32] <= data_i[26];
  always @(posedge clk_i)
    positional_q[33] <= data_i[27];
  always @(posedge clk_i)
    positional_q[34] <= data_i[28];
  always @(posedge clk_i)
    positional_q[35] <= data_i[29];
  always @(posedge clk_i)
    positional_q[36] <= data_i[30];
  always @(posedge clk_i)
    positional_q[37] <= data_i[31];
  always @(posedge clk_i)
    positional_q[38] <= data_i[32];
  always @(posedge clk_i)
    positional_q[39] <= data_i[33];
  always @(posedge clk_i)
    positional_q[40] <= data_i[34];
  always @(posedge clk_i)
    positional_q[41] <= data_i[35];
  always @(posedge clk_i)
    positional_q[42] <= data_i[36];
  always @(posedge clk_i)
    positional_q[43] <= data_i[37];
  always @(posedge clk_i)
    positional_q[44] <= data_i[38];
  always @(posedge clk_i)
    positional_q[45] <= data_i[39];
  always @(posedge clk_i)
    positional_q[46] <= data_i[40];
  always @(posedge clk_i)
    positional_q[47] <= data_i[41];
  always @(posedge clk_i)
    positional_q[48] <= data_i[42];
  always @(posedge clk_i)
    positional_q[49] <= data_i[43];
  always @(posedge clk_i)
    positional_q[50] <= data_i[44];
  always @(posedge clk_i)
    positional_q[51] <= data_i[45];
  always @(posedge clk_i)
    positional_q[52] <= data_i[46];
  always @(posedge clk_i)
    positional_q[53] <= data_i[47];
  always @(posedge clk_i)
    positional_q[54] <= data_i[48];
  always @(posedge clk_i)
    positional_q[55] <= data_i[49];
  always @(posedge clk_i)
    positional_q[56] <= data_i[50];
  always @(posedge clk_i)
    positional_q[57] <= data_i[51];
  always @(posedge clk_i)
    positional_q[58] <= data_i[52];
  always @(posedge clk_i)
    positional_q[59] <= data_i[53];
  always @(posedge clk_i)
    positional_q[60] <= data_i[54];
  always @(posedge clk_i)
    positional_q[61] <= data_i[55];
  always @(posedge clk_i)
    positional_q[62] <= data_i[56];
  always @(posedge clk_i)
    positional_q[63] <= parity_d[6];
  always @(posedge clk_i)
    positional_q[64] <= data_i[57];
  always @(posedge clk_i)
    positional_q[65] <= data_i[58];
  always @(posedge clk_i)
    positional_q[66] <= data_i[59];
  always @(posedge clk_i)
    positional_q[67] <= data_i[60];
  always @(posedge clk_i)
    positional_q[68] <= data_i[61];
  always @(posedge clk_i)
    positional_q[69] <= data_i[62];
  always @(posedge clk_i)
    positional_q[70] <= data_i[63];
  assign _000_[70:0] = positional_q;
  assign codeword_o = stage2_codeword_q;
  assign data_index = 32'd64;
  assign group_index = 32'd9;
  assign group_offset = 32'd8;
  assign { \parity_group[3] [6], \parity_group[3] [4], \parity_group[3] [2], \parity_group[3] [0] } = { data_i[49], data_i[33], data_i[18], 1'h0 };
  assign { \parity_group[4] [5:3], \parity_group[4] [1:0] } = { data_i[41], 1'h0, \parity_group[3] [3], 2'h0 };
  assign { \parity_group[5] [8:6], \parity_group[5] [3:0] } = { 1'h0, \parity_group[3] [7], \parity_group[4] [6], 4'h0 };
  assign \parity_group[6]  = { parity_d[6], 8'h00 };
  assign parity_index = 32'd7;
  assign position = 32'd72;
  assign positional_d = { data_i[63:57], parity_d[6], data_i[56:26], parity_d[5], data_i[25:11], parity_d[4], data_i[10:4], parity_d[3], data_i[3:1], parity_d[2], data_i[0], parity_d[1:0] };
  assign valid_o = stage2_valid_q;
endmodule
