[pytest]
testpaths = tests
addopts = -p no:tmpdir
norecursedirs =
    .git
    build
    __pycache__
    pytest-cache-files-*
    tests/.tmp_golden
    tests/fixtures/tmp
    tests/fixtures/local_tmp
    tests/fixtures/pytest_tmp
