// Generated by GREEN-ECC architecture DSE. Do not edit manually.
package green_ecc_config_pkg;
  localparam int ECC_MODE_COUNT = 5;
  localparam int ECC_MODE_WIDTH = 3;
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_SAFE_FALLBACK = ECC_MODE_WIDTH'(0);
  localparam string ECC_METADATA_PROTECTION = "triplicated";

  typedef enum logic [ECC_MODE_WIDTH-1:0] {
    ECC_MODE_SEC_DED_64 = ECC_MODE_WIDTH'(0),
    ECC_MODE_SEC_DAEC_64 = ECC_MODE_WIDTH'(1),
    ECC_MODE_TAEC_64 = ECC_MODE_WIDTH'(2),
    ECC_MODE_BCH_63_51_T2 = ECC_MODE_WIDTH'(3),
    ECC_MODE_POLAR_64_48_SC = ECC_MODE_WIDTH'(4)
  } ecc_mode_e;

  localparam int ECC_N [0:ECC_MODE_COUNT-1] = '{72, 73, 75, 63, 64};
  localparam int ECC_K [0:ECC_MODE_COUNT-1] = '{64, 64, 64, 51, 48};

  // Scenario-to-mode policy generated by exact Pareto filtering and declared preferences.
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_POLICY_HEAVY_FAULT_REGIME = ECC_MODE_WIDTH'(2);
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_POLICY_MODERATE_HIGH_CARBON = ECC_MODE_WIDTH'(3);
  localparam logic [ECC_MODE_WIDTH-1:0] ECC_POLICY_MODERATE_LOW_CARBON = ECC_MODE_WIDTH'(3);
endpackage
