"""Deployment overheads and generated hardware configuration artifacts."""

from __future__ import annotations

import math
from pathlib import Path
from typing import Mapping, Sequence

from .types import ECCConfiguration, Scenario


def fit_to_mission_failure_probability(fit: float, lifetime_hours: float) -> float:
    if fit < 0 or lifetime_hours < 0:
        raise ValueError("FIT and lifetime_hours must be non-negative")
    return 1.0 - math.exp(-fit * lifetime_hours / 1.0e9)


def record_energy_j(record: Mapping[str, object]) -> float:
    return 3.6e6 * sum(
        float(record.get(field, 0.0) or 0.0)
        for field in ("E_dyn_kWh", "E_leak_kWh", "E_scrub_kWh")
    )


def reconfiguration_overhead(
    *,
    old_record: Mapping[str, object],
    new_record: Mapping[str, object],
    scenario: Scenario,
    container_bits: int,
    control_energy_j_per_transition: float | None,
) -> dict:
    transitions = max(scenario.workload.decision_epochs - 1, 0)
    migrated_per_transition = scenario.workload.migrated_words_per_transition
    migrated_total = transitions * migrated_per_transition
    if transitions == 0 or migrated_total == 0:
        return {
            "transitions": transitions,
            "migrated_words_total": migrated_total,
            "energy_j_total": 0.0,
            "latency_ns_total": 0.0,
            "temporary_capacity_bits": 0,
            "amortized_energy_j_per_access": 0.0,
            "model": "no transitions requested",
        }

    old_per_access = record_energy_j(old_record) / scenario.workload.total_accesses
    new_per_access = record_energy_j(new_record) / scenario.workload.total_accesses
    migration_energy = migrated_total * (old_per_access + new_per_access)
    control_energy = (
        transitions * control_energy_j_per_transition
        if control_energy_j_per_transition is not None
        else None
    )
    total_energy = migration_energy + control_energy if control_energy is not None else None

    memory_latency_known = (
        scenario.memory_read_latency_ns is not None
        and scenario.memory_write_latency_ns is not None
    )
    if memory_latency_known:
        per_word_latency = (
            float(scenario.memory_read_latency_ns)
            + float(old_record["latency_ns"])
            + float(new_record["latency_ns"])
            + float(scenario.memory_write_latency_ns)
        )
        latency_total = migrated_total * per_word_latency
    else:
        latency_total = None

    return {
        "transitions": transitions,
        "migrated_words_per_transition": migrated_per_transition,
        "migrated_words_total": migrated_total,
        "old_read_decode_energy_j_per_word_proxy": old_per_access,
        "new_encode_write_energy_j_per_word_proxy": new_per_access,
        "migration_energy_j": migration_energy,
        "control_energy_j": control_energy,
        "energy_j_total": total_energy,
        "latency_ns_total": latency_total,
        "temporary_capacity_bits": migrated_per_transition * container_bits,
        "amortized_energy_j_per_access": (
            total_energy / scenario.workload.total_accesses if total_energy is not None else None
        ),
        "model": (
            "N_migrated * (legacy old per-access energy + legacy new per-access energy) + control; "
            "read/decode and encode/write are not separable in current legacy energy records."
        ),
    }


def emit_systemverilog_package(
    path: Path,
    *,
    package_name: str,
    candidates: Sequence[ECCConfiguration],
    safe_fallback_config_id: str,
    scenario_modes: Mapping[str, str],
    metadata_protection: str,
) -> None:
    ids = [item.config_id for item in candidates]
    if safe_fallback_config_id not in ids:
        raise ValueError("Safe fallback must be one of the configured ECC modes")
    mode_width = max(1, math.ceil(math.log2(len(candidates))))
    fallback_index = ids.index(safe_fallback_config_id)
    lines = [
        "// Generated by GREEN-ECC architecture DSE. Do not edit manually.",
        f"package {package_name};",
        f"  localparam int ECC_MODE_COUNT = {len(candidates)};",
        f"  localparam int ECC_MODE_WIDTH = {mode_width};",
        f"  localparam logic [ECC_MODE_WIDTH-1:0] ECC_SAFE_FALLBACK = ECC_MODE_WIDTH'({fallback_index});",
        f'  localparam string ECC_METADATA_PROTECTION = "{metadata_protection}";',
        "",
        "  typedef enum logic [ECC_MODE_WIDTH-1:0] {",
    ]
    enum_lines = []
    for index, item in enumerate(candidates):
        name = "ECC_MODE_" + "".join(ch if ch.isalnum() else "_" for ch in item.config_id.upper())
        comma = "," if index + 1 < len(candidates) else ""
        enum_lines.append(f"    {name} = ECC_MODE_WIDTH'({index}){comma}")
    lines.extend(enum_lines)
    lines.extend(
        [
            "  } ecc_mode_e;",
            "",
            "  localparam int ECC_N [0:ECC_MODE_COUNT-1] = '{"
            + ", ".join(str(item.n) for item in candidates)
            + "};",
            "  localparam int ECC_K [0:ECC_MODE_COUNT-1] = '{"
            + ", ".join(str(item.k) for item in candidates)
            + "};",
            "",
            "  // Scenario-to-mode policy generated by exact Pareto filtering and declared preferences.",
        ]
    )
    for scenario_id, config_id in sorted(scenario_modes.items()):
        mode_index = ids.index(config_id)
        safe_name = "".join(ch if ch.isalnum() else "_" for ch in scenario_id.upper())
        lines.append(
            f"  localparam logic [ECC_MODE_WIDTH-1:0] ECC_POLICY_{safe_name} = ECC_MODE_WIDTH'({mode_index});"
        )
    lines.extend(["endpackage", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
