"""Reproducible transition-aware ECC scheduling and co-design study."""

from __future__ import annotations

from dataclasses import replace
import csv
import hashlib
import json
import math
from pathlib import Path
import random
import subprocess
import time
from typing import Mapping, Sequence

import jsonschema

from visualization_runtime import configure_matplotlib_cache

configure_matplotlib_cache()
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from .break_even import break_even_horizon
from .granularity import evaluate_granularity
from .hysteresis import hysteresis_schedule
from .schedule_explain import (
    compact_policy_table,
    compare_schedule_to_static,
    count_avoided_transitions,
    schedule_stability,
    waterfall_terms_with_continuing_overhead,
)
from .break_even import overhead_ratio
from .scheduling import (
    EpochModeCost,
    ScheduleResult,
    best_static_schedule,
    build_epoch_costs,
    exact_dynamic_programming,
    fault_lookup_schedule,
    greedy_schedule,
    robust_dynamic_programming,
    snapshot_oracle_schedule,
)
from .traces import ScenarioTrace, generate_synthetic_trace, load_traces
from .transitions import (
    ArchitectureDesign,
    ECCOperatingMode,
    TransitionCost,
    TransitionModel,
)


OKABE_ITO = ["#0072B2", "#E69F00", "#009E73", "#D55E00", "#CC79A7", "#56B4E9", "#F0E442"]


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n", encoding="utf-8")


def _write_csv(path: Path, rows: Sequence[Mapping[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields = list(rows[0])
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def _write_schedule_package(
    path: Path,
    *,
    modes: Sequence[str],
    schedule: Sequence[str],
    safe_fallback: str,
    minimum_dwell_epochs: int,
) -> None:
    if safe_fallback not in modes:
        raise ValueError("safe fallback must be present in schedule mode table")
    width = max(1, math.ceil(math.log2(len(modes))))
    indices = [modes.index(mode) for mode in schedule]
    lines = [
        "// Generated by GREEN-ECC transition-aware scheduling. Do not edit manually.",
        "// This is a policy package; it does not implement the migration datapath.",
        "package green_ecc_schedule_pkg;",
        f"  localparam int ECC_MODE_COUNT = {len(modes)};",
        f"  localparam int ECC_MODE_WIDTH = {width};",
        f"  localparam int ECC_SCHEDULE_EPOCHS = {len(schedule)};",
        f"  localparam int ECC_MIN_DWELL_EPOCHS = {minimum_dwell_epochs};",
        f"  localparam logic [ECC_MODE_WIDTH-1:0] ECC_SAFE_FALLBACK = ECC_MODE_WIDTH'({modes.index(safe_fallback)});",
        "  localparam logic [ECC_MODE_WIDTH-1:0] ECC_EPOCH_MODE [0:ECC_SCHEDULE_EPOCHS-1] = '{",
        "    " + ", ".join(f"ECC_MODE_WIDTH'({index})" for index in indices),
        "  };",
    ]
    for index, mode in enumerate(modes):
        token = "".join(character if character.isalnum() else "_" for character in mode.upper())
        lines.append(f"  localparam logic [ECC_MODE_WIDTH-1:0] ECC_MODE_{token} = ECC_MODE_WIDTH'({index});")
    lines.extend(["endpackage", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def _save_publication_figure(fig, svg_path: Path) -> None:
    """Write the authoritative vector figure plus a raster QA companion."""

    fig.savefig(svg_path)
    fig.savefig(svg_path.with_suffix(".png"), dpi=180)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _repository_state(repo_root: Path) -> tuple[str | None, bool]:
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=repo_root, check=True,
            capture_output=True, text=True, timeout=10,
        ).stdout.strip()
        dirty = bool(
            subprocess.run(
                ["git", "status", "--porcelain"], cwd=repo_root, check=True,
                capture_output=True, text=True, timeout=10,
            ).stdout.strip()
        )
        return commit, dirty
    except (OSError, subprocess.SubprocessError):
        return None, True


def _validate_input(payload: Mapping[str, object], repo_root: Path) -> None:
    required = {
        "schema_version", "study_id", "model_status", "modes", "designs",
        "transition_costs", "policy", "trace_generators", "uncertainty_samples",
    }
    missing = sorted(required - set(payload))
    if missing:
        raise ValueError(f"transition scheduling config missing: {', '.join(missing)}")
    if int(payload["schema_version"]) != 1:
        raise ValueError("unsupported transition scheduling schema version")
    composite_schema = json.loads(
        (repo_root / "schemas" / "transition-schedule-config.schema.json").read_text(
            encoding="utf-8"
        )
    )
    jsonschema.validate(payload, composite_schema)
    for key, schema_name in (
        ("transition_costs", "transition-cost-matrix.schema.json"),
        ("policy", "scheduling-policy.schema.json"),
    ):
        schema = json.loads((repo_root / "schemas" / schema_name).read_text(encoding="utf-8"))
        jsonschema.validate(payload[key], schema)


def _transition_lookup(
    model: TransitionModel, design: ArchitectureDesign, trace: ScenarioTrace
):
    def lookup(index: int, old: str, new: str) -> TransitionCost:
        return model.evaluate(from_ecc=old, to_ecc=new, design=design, epoch=trace.epochs[index])

    return lookup


def _policy_max_transitions(policy: Mapping[str, object], epoch_count: int) -> int | None:
    limits = []
    if policy.get("maximum_transitions") is not None:
        limits.append(int(policy["maximum_transitions"]))
    if policy.get("maximum_switch_rate_per_epoch") is not None:
        limits.append(math.floor(float(policy["maximum_switch_rate_per_epoch"]) * epoch_count))
    return min(limits) if limits else None


def _apply_certificate_gate(
    *,
    trace: ScenarioTrace,
    costs: Sequence[Mapping[str, EpochModeCost]],
    gate: Mapping[str, object] | None,
    envelopes: Sequence[Mapping[str, object]],
) -> tuple[dict[str, EpochModeCost], ...]:
    """Make out-of-envelope modes infeasible before any scheduling policy runs."""

    if not gate or not bool(gate.get("enabled", False)):
        return tuple(dict(row) for row in costs)
    by_mode = {str(item["mode_id"]): item for item in envelopes}
    radius_key = str(gate.get("epoch_radius_uncertainty_key", "ambiguity_radius"))
    required_type = str(gate["ambiguity_type"])
    maximum_sdc = float(gate["maximum_sdc"])
    support_by_regime = {
        str(key): str(value)
        for key, value in dict(gate.get("support_id_by_fault_regime", {})).items()
    }
    output = []
    for epoch, row in zip(trace.epochs, costs):
        observed_radius = epoch.uncertainty.get(radius_key)
        gated_row = {}
        for mode, item in row.items():
            envelope = by_mode.get(mode)
            reasons = []
            if envelope is None:
                reasons.append("certificate_gate:mode_not_registered")
            else:
                current_support = support_by_regime.get(epoch.fault_regime)
                if current_support is None:
                    reasons.append("certificate_gate:current_support_identifier_missing")
                elif current_support != str(envelope.get("support_identifier", "")):
                    reasons.append("certificate_gate:error_support_not_contained")
                if str(envelope["ambiguity_type"]) != required_type:
                    reasons.append("certificate_gate:ambiguity_type_mismatch")
                if observed_radius is None:
                    reasons.append("certificate_gate:epoch_confidence_radius_missing")
                elif float(observed_radius) > float(envelope["certified_radius"]) + 1e-15:
                    reasons.append("certificate_gate:confidence_region_outside_envelope")
                if float(envelope["maximum_certified_sdc"]) > maximum_sdc + 1e-15:
                    reasons.append("certificate_gate:sdc_limit_exceeded")
                if epoch.fault_regime not in set(envelope.get("supported_fault_regimes", [])):
                    reasons.append("certificate_gate:fault_regime_not_supported")
                if not str(envelope.get("certificate_identifier", "")):
                    reasons.append("certificate_gate:certificate_identifier_missing")
            if reasons:
                gated_row[mode] = replace(
                    item,
                    feasible=False,
                    feasibility_probability=0.0,
                    violations=tuple(item.violations) + tuple(reasons),
                )
            else:
                gated_row[mode] = item
        output.append(gated_row)
    return tuple(output)


def _run_design(
    *,
    trace: ScenarioTrace,
    modes: Mapping[str, ECCOperatingMode],
    design: ArchitectureDesign,
    transition_model: TransitionModel,
    policy: Mapping[str, object],
    certificate_gate: Mapping[str, object] | None = None,
    certificate_envelopes: Sequence[Mapping[str, object]] = (),
) -> tuple[dict[str, ScheduleResult], tuple[dict[str, EpochModeCost], ...]]:
    objective = str(policy["objective"])
    maximum_transitions = _policy_max_transitions(policy, len(trace.epochs))
    costs = build_epoch_costs(
        trace,
        modes,
        design,
        objective=objective,
        area_limit_mm2=(
            float(policy["area_limit_mm2"])
            if policy.get("area_limit_mm2") is not None
            else None
        ),
    )
    costs = _apply_certificate_gate(
        trace=trace,
        costs=costs,
        gate=certificate_gate,
        envelopes=certificate_envelopes,
    )
    lookup = _transition_lookup(transition_model, design, trace)
    static = best_static_schedule(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
    )
    results: dict[str, ScheduleResult] = {"best_static": static}
    if design.architecture_mode != "adaptive":
        return results, costs
    results["snapshot_oracle"] = snapshot_oracle_schedule(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
    )
    results["greedy"] = greedy_schedule(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
    )
    results["fault_regime_lookup"] = fault_lookup_schedule(
        trace=trace,
        lookup=dict(policy["fault_regime_lookup"]),
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
        safe_fallback=str(policy["safe_fallback_ecc"]),
    )
    results["transition_aware_dp"] = exact_dynamic_programming(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
        min_dwell_epochs=int(policy["minimum_dwell_epochs"]),
        max_transitions=maximum_transitions,
    )
    results["robust_transition_aware"] = robust_dynamic_programming(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
        chance_constraint_epsilon=float(policy["chance_constraint_epsilon"]),
        risk_aversion_z=float(policy["risk_aversion_z"]),
        min_dwell_epochs=int(policy["minimum_dwell_epochs"]),
        max_transitions=maximum_transitions,
    )
    results["robust_hysteresis"] = hysteresis_schedule(
        epoch_costs=costs,
        transition_lookup=lookup,
        design=design,
        objective=objective,
        prediction_horizon_epochs=int(policy["prediction_horizon_epochs"]),
        min_dwell_epochs=int(policy["minimum_dwell_epochs"]),
        minimum_benefit_margin=float(policy["minimum_benefit_margin"]),
        max_transitions=maximum_transitions,
        confidence_threshold=float(policy["confidence_threshold"]),
        uncertainty_z=float(policy["risk_aversion_z"]),
        safe_fallback=str(policy["safe_fallback_ecc"]),
    )
    return results, costs


def _best_result(items: Sequence[tuple[str, ScheduleResult]]) -> tuple[str, ScheduleResult] | None:
    feasible = [(name, item) for name, item in items if item.status == "ok" and item.total_objective is not None]
    return min(feasible, key=lambda value: (float(value[1].total_objective), value[0])) if feasible else None


def _transition_break_even(
    *,
    result: ScheduleResult,
    costs: Sequence[Mapping[str, EpochModeCost]],
    lookup,
    objective: str,
) -> list[dict]:
    output = []
    for index in range(1, len(result.path)):
        old = result.path[index - 1]
        new = result.path[index]
        if old == new:
            continue
        old_cost = costs[index][old]
        new_cost = costs[index][new]
        transition = lookup(index, old, new)
        if objective == "lifecycle_energy_j":
            old_per_access = (
                float(old_cost.operational_energy_j) / max(1, int(old_cost.cost_breakdown.get("accesses", 0) or 1))
                if old_cost.operational_energy_j is not None
                else None
            )
            new_per_access = (
                float(new_cost.operational_energy_j) / max(1, int(new_cost.cost_breakdown.get("accesses", 0) or 1))
                if new_cost.operational_energy_j is not None
                else None
            )
        else:
            accesses = max(1, int(old_cost.cost_breakdown.get("accesses", 0) or 1))
            old_per_access = (
                float(old_cost.operational_carbon_kgco2e) / accesses
                if old_cost.operational_carbon_kgco2e is not None
                else None
            )
            new_per_access = (
                float(new_cost.operational_carbon_kgco2e) / accesses
                if new_cost.operational_carbon_kgco2e is not None
                else None
            )
        # Within an already-instantiated adaptive design, continuing MUX/control
        # overhead is common to both states and cancels. Architecture adoption
        # overhead is handled separately in the fixed-vs-adaptive comparison.
        one_time = transition.objective_cost(objective)
        break_even = break_even_horizon(
            current_cost_per_access=old_per_access,
            new_cost_per_access=new_per_access,
            continuing_adaptive_overhead_per_access=0.0,
            one_time_transition_cost=one_time,
            feasible=transition.allowed,
            units=("J and J/access" if objective == "lifecycle_energy_j" else "kgCO2e and kgCO2e/access"),
        )
        output.append(
            {
                "epoch_index": index,
                "from_ecc": old,
                "to_ecc": new,
                "transition": transition.to_dict(),
                "break_even": break_even.to_dict(),
            }
        )
    return output


def _continuing_adaptability_overhead(
    result: ScheduleResult,
    costs: Sequence[Mapping[str, EpochModeCost]],
    objective: str,
) -> float | None:
    field = (
        "continuing_adaptability_energy_j"
        if objective == "lifecycle_energy_j"
        else "continuing_adaptability_carbon_kgco2e"
    )
    total = 0.0
    for index, mode in enumerate(result.path):
        value = costs[index][mode].cost_breakdown.get(field)
        if value is None:
            return None
        total += float(value)
    return total


def _uncertainty_study(
    *,
    nominal_costs: Sequence[Mapping[str, EpochModeCost]],
    transition_lookup,
    design: ArchitectureDesign,
    objective: str,
    samples: int,
    seed: int,
    min_dwell: int,
    max_transitions: int | None,
    reference: ScheduleResult,
) -> dict:
    rng = random.Random(seed)
    paths = []
    reference_regrets = []
    reference_feasible = 0
    beneficial = 0
    for _ in range(samples):
        sampled = []
        for costs in nominal_costs:
            row = {}
            for mode, cost in costs.items():
                relative = cost.objective_std * math.sqrt(3.0) / abs(float(cost.objective_cost or 1.0))
                factor = rng.uniform(max(0.0, 1.0 - relative), 1.0 + relative)
                row[mode] = replace(
                    cost,
                    objective_cost=(
                        float(cost.objective_cost) * factor if cost.objective_cost is not None else None
                    ),
                    feasible=(cost.feasible and rng.random() <= cost.feasibility_probability),
                )
            sampled.append(row)
        optimum = exact_dynamic_programming(
            epoch_costs=sampled,
            transition_lookup=transition_lookup,
            design=design,
            objective=objective,
            min_dwell_epochs=min_dwell,
            max_transitions=max_transitions,
            policy_name="uncertainty_sample_optimum",
        )
        static = best_static_schedule(
            epoch_costs=sampled,
            transition_lookup=transition_lookup,
            design=design,
            objective=objective,
        )
        if optimum.status == "ok":
            paths.append(optimum.path)
            if static.status == "ok" and float(optimum.total_objective) < float(static.total_objective):
                beneficial += 1
        if reference.path:
            from .scheduling import evaluate_path

            evaluated = evaluate_path(
                policy_name="reference_under_sample",
                path=reference.path,
                epoch_costs=sampled,
                transition_lookup=transition_lookup,
                design=design,
                objective=objective,
                theoretical_complexity="fixed path evaluation",
            )
            if evaluated.status == "ok" and optimum.status == "ok":
                reference_feasible += 1
                reference_regrets.append(float(evaluated.total_objective) - float(optimum.total_objective))
    reference_regrets.sort()
    p95_index = max(0, math.ceil(0.95 * len(reference_regrets)) - 1) if reference_regrets else 0
    stability = schedule_stability(paths)
    return {
        "samples": samples,
        "seed": seed,
        "distribution": "independent uniform objective intervals plus Bernoulli chance-feasibility draws",
        "probability_reference_schedule_feasible": reference_feasible / samples,
        "probability_switching_beneficial_vs_same_design_static": beneficial / samples,
        "reference_regret_mean": (
            sum(reference_regrets) / len(reference_regrets) if reference_regrets else None
        ),
        "reference_regret_p95": reference_regrets[p95_index] if reference_regrets else None,
        "schedule_stability": stability,
    }


def _dummy_scalability_benchmark() -> list[dict]:
    rows = []
    for epochs in (8, 32, 128):
        for mode_count in (2, 4, 8, 16):
            names = tuple(f"m{index}" for index in range(mode_count))
            costs = []
            for epoch in range(epochs):
                costs.append(
                    {
                        name: EpochModeCost(
                            epoch_id=f"e{epoch}", mode_id=name, ecc_id=name, design_id="benchmark",
                            objective_cost=1.0 + ((epoch + index) % mode_count) / mode_count,
                            operational_energy_j=1.0, operational_carbon_kgco2e=1e-7,
                            latency_ns=1.0, fit=1.0, area_mm2=1.0, feasible=True,
                            feasibility_probability=1.0, objective_std=0.0,
                            constraint_margins={}, violations=(), cost_breakdown={},
                        )
                        for index, name in enumerate(names)
                    }
                )
            design = ArchitectureDesign(
                design_id="benchmark", architecture_mode="adaptive", topology="abstract",
                granularity="whole_memory", supported_eccs=names, metadata_protection="none",
                total_words=1, adaptability_energy_j_per_access=0.0,
                metadata_lookup_energy_j_per_access=0.0, controller_energy_j_per_decision=0.0,
                inactive_engine_leakage_w=0.0, area_mm2=1.0, embodied_carbon_kgco2e=0.0,
                implementation_energy_j=0.0, provenance={"source": "test_fixture"},
            )

            def lookup(index: int, old: str, new: str) -> TransitionCost:
                return TransitionCost(old, new, True, 0.05 if old != new else 0.0, 0.0, 0.0, 0, 0, "test_fixture")

            started = time.perf_counter()
            result = exact_dynamic_programming(
                epoch_costs=costs, transition_lookup=lookup, design=design,
                objective="lifecycle_energy_j", min_dwell_epochs=1,
            )
            rows.append(
                {
                    "epochs": epochs,
                    "modes": mode_count,
                    "runtime_seconds": time.perf_counter() - started,
                    "status": result.status,
                    "theoretical_time": epochs * mode_count * mode_count,
                    "theoretical_memory": epochs * mode_count,
                }
            )
    return rows


def _plot_results(outdir: Path, report: Mapping[str, object]) -> dict[str, str]:
    figures = outdir / "figures"
    figures.mkdir(parents=True, exist_ok=True)
    trace_results = dict(report["trace_results"])
    takeaways: dict[str, str] = {}

    # 1. Architecture comparison for the one-time transition trace.
    selected_trace = trace_results.get("one_time_sbu_to_mbu") or next(iter(trace_results.values()))
    designs = dict(selected_trace["design_results"])
    labels, totals = [], []
    for design_id, value in designs.items():
        result = value["decision_result"]
        if result["status"] == "ok":
            labels.append(design_id)
            totals.append(result["total_objective"])
    fig, ax = plt.subplots(figsize=(8.2, 4.2))
    ax.bar(range(len(labels)), totals, color=[OKABE_ITO[i % len(OKABE_ITO)] for i in range(len(labels))])
    ax.set_xticks(range(len(labels)), labels, rotation=28, ha="right")
    ax.set_ylabel(report["objective"])
    ax.set_title("Fixed, configurable, and adaptive design decisions")
    ax.grid(axis="y", alpha=0.25)
    fig.tight_layout()
    _save_publication_figure(fig, figures / "architecture_mode_comparison.svg")
    plt.close(fig)
    winner = selected_trace["joint_decision"]["design_id"]
    takeaways["architecture_mode_comparison.svg"] = f"For the selected long transition trace, {winner} minimizes the configured lifecycle objective."

    # 2. Formal decision flow.
    fig, ax = plt.subplots(figsize=(9.0, 2.7))
    ax.axis("off")
    boxes = ["Ordered trace", "Hard constraints", "Epoch + transition costs", "Exact DP / robust hysteresis", "Deployable schedule"]
    for index, label in enumerate(boxes):
        x = 0.02 + index * 0.195
        ax.add_patch(plt.Rectangle((x, 0.35), 0.16, 0.3, facecolor=OKABE_ITO[index], alpha=0.85))
        ax.text(x + 0.08, 0.5, label, ha="center", va="center", fontsize=9, color="white", wrap=True)
        if index + 1 < len(boxes):
            ax.annotate("", xy=(x + 0.19, 0.5), xytext=(x + 0.16, 0.5), arrowprops={"arrowstyle": "->"})
    ax.set_title("Transition-aware GREEN-ECC decision sequence")
    fig.tight_layout()
    _save_publication_figure(fig, figures / "scheduling_formulation.svg")
    plt.close(fig)
    takeaways["scheduling_formulation.svg"] = "Hard feasibility is applied before lifecycle scheduling; no default scalar reliability/latency trade-off is used."

    # 3. Policy timelines on the trace with the clearest paradox, if present.
    paradoxes = list(report["hypotheses"]["H1_adaptation_paradox"]["cases"])
    timeline_trace_id = (
        paradoxes[0]["trace_id"]
        if paradoxes
        else (
            "short_noisy_fluctuations"
            if "short_noisy_fluctuations" in trace_results
            else next(iter(trace_results))
        )
    )
    timeline_trace = trace_results[timeline_trace_id]
    adaptive_id = timeline_trace["best_adaptive_design_id"]
    policies = timeline_trace["design_results"][adaptive_id]["policies"]
    policy_names = [name for name in ("best_static", "snapshot_oracle", "greedy", "transition_aware_dp", "robust_hysteresis") if name in policies]
    modes = sorted({mode for name in policy_names for mode in policies[name]["path"]})
    mode_index = {mode: index for index, mode in enumerate(modes)}
    fig, ax = plt.subplots(figsize=(9.0, 4.4))
    for row, name in enumerate(policy_names):
        path = policies[name]["path"]
        ax.step(range(len(path)), [mode_index[item] + row * 0.08 for item in path], where="post", label=name, color=OKABE_ITO[row])
    ax.set_yticks(range(len(modes)), modes)
    ax.set_xlabel("Epoch")
    ax.set_title(f"ECC schedules on {timeline_trace_id}")
    ax.legend(ncol=2, fontsize=8)
    ax.grid(alpha=0.2)
    fig.tight_layout()
    _save_publication_figure(fig, figures / "policy_timeline.svg")
    plt.close(fig)
    takeaways["policy_timeline.svg"] = "Snapshot decisions can oscillate; transition-aware and hysteretic policies retain modes when the forecast saving cannot repay switching."

    # 4. Break-even regime map from generated sweep.
    sweep = report["regime_sweep"]
    x_values = sweep["transition_energy_multipliers"]
    y_values = sweep["epoch_accesses"]
    matrix = sweep["adaptive_beneficial"]
    fig, ax = plt.subplots(figsize=(7.0, 4.6))
    image = ax.imshow(matrix, aspect="auto", origin="lower", cmap=ListedColormap(["#D55E00", "#009E73"]), vmin=0, vmax=1)
    ax.set_xticks(range(len(x_values)), x_values)
    ax.set_yticks(range(len(y_values)), [f"{value/1e6:g}M" for value in y_values])
    ax.set_xlabel("Transition-energy multiplier")
    ax.set_ylabel("Accesses per epoch")
    ax.set_title("Break-even regime: adaptive (green) versus fixed (orange)")
    fig.colorbar(image, ax=ax, ticks=[0, 1], label="Adaptive beneficial")
    fig.tight_layout()
    _save_publication_figure(fig, figures / "break_even_regime_map.svg")
    plt.close(fig)
    takeaways["break_even_regime_map.svg"] = "Longer epochs amortize migration; increasing transition cost contracts the adaptive region."

    # 5. Granularity/design regime matrix.
    first_designs = next(iter(trace_results.values()))["design_results"]
    adaptive_designs = sorted(
        design_id
        for design_id, value in first_designs.items()
        if value["design"]["architecture_mode"] == "adaptive"
    )
    trace_ids = list(trace_results)
    values = []
    for trace_id in trace_ids:
        row = []
        static_total = trace_results[trace_id]["best_fixed"]["total_objective"]
        for design_id in adaptive_designs:
            result = trace_results[trace_id]["design_results"].get(design_id, {}).get("decision_result")
            row.append((static_total - result["total_objective"]) / static_total if result and result["status"] == "ok" else math.nan)
        values.append(row)
    fig, ax = plt.subplots(figsize=(8.0, 5.2))
    image = ax.imshow(values, aspect="auto", cmap="RdYlGn", vmin=-0.2, vmax=0.2)
    ax.set_xticks(range(len(adaptive_designs)), adaptive_designs, rotation=25, ha="right")
    ax.set_yticks(range(len(trace_ids)), trace_ids)
    ax.set_title("Net objective saving versus best fixed design")
    fig.colorbar(image, ax=ax, label="Fractional saving")
    fig.tight_layout()
    _save_publication_figure(fig, figures / "topology_granularity_regime.svg")
    plt.close(fig)
    takeaways["topology_granularity_regime.svg"] = "Finer granularity helps only when reduced migration exceeds its metadata and access overhead."

    # 6. Waterfall for strongest adaptive win or paradox if no win.
    candidates = [value for value in trace_results.values() if value["waterfall"]["status"] == "ok"]
    selected = max(candidates, key=lambda item: item["waterfall"]["net_saving"]) if candidates else None
    if selected:
        waterfall = selected["waterfall"]
        vals = [
            waterfall["gross_operational_saving"],
            -waterfall["continuing_adaptability_overhead"],
            -waterfall["transition_overhead"],
            -waterfall["incremental_implementation_overhead"],
            waterfall["net_saving"],
        ]
        fig, ax = plt.subplots(figsize=(7.2, 4.2))
        ax.bar(range(5), vals, color=[OKABE_ITO[2], OKABE_ITO[4], OKABE_ITO[3], OKABE_ITO[1], OKABE_ITO[0]])
        ax.axhline(0, color="black", linewidth=0.8)
        ax.set_xticks(
            range(5),
            ["Gross saving", "Continuing\nadaptability", "Migration", "Implementation", "Net saving"],
        )
        ax.set_ylabel(report["objective"])
        ax.set_title("Gross benefit and complete adaptability overhead")
        fig.tight_layout()
        _save_publication_figure(fig, figures / "benefit_waterfall.svg")
        plt.close(fig)
        takeaways["benefit_waterfall.svg"] = "Net benefit is reported only after transition and allocated architecture overhead are subtracted."

    # 7. Robustness versus regret.
    xs, ys, annotations = [], [], []
    for trace_id, value in trace_results.items():
        uncertainty = value.get("uncertainty")
        if uncertainty and uncertainty["reference_regret_mean"] is not None:
            xs.append(uncertainty["probability_reference_schedule_feasible"])
            ys.append(uncertainty["reference_regret_mean"])
            annotations.append(trace_id)
    grouped: dict[tuple[float, float], list[str]] = {}
    for x, y, label in zip(xs, ys, annotations):
        grouped.setdefault((round(x, 5), round(y, 8)), []).append(label)
    fig, ax = plt.subplots(figsize=(7.2, 4.5))
    for (x, y), labels_at_point in grouped.items():
        ax.scatter([x], [y], color=OKABE_ITO[0], s=45 + 12 * (len(labels_at_point) - 1))
        label = labels_at_point[0] if len(labels_at_point) == 1 else f"{len(labels_at_point)} traces"
        ax.annotate(label, (x, y), fontsize=8, xytext=(4, 4), textcoords="offset points")
    ax.set_xlabel("Probability nominal DP schedule remains feasible")
    ax.set_ylabel("Mean regret under perturbation")
    ax.set_title("Schedule robustness versus regret")
    ax.grid(alpha=0.2)
    fig.tight_layout()
    _save_publication_figure(fig, figures / "robustness_regret.svg")
    plt.close(fig)
    takeaways["robustness_regret.svg"] = "High nominal savings do not imply stable decisions; uncertainty is reported separately from nominal optimality."

    # 8. Scaling.
    fig, ax = plt.subplots(figsize=(7.4, 4.5))
    for modes in sorted({row["modes"] for row in report["scalability"]}):
        subset = [row for row in report["scalability"] if row["modes"] == modes]
        ax.plot([row["epochs"] for row in subset], [row["runtime_seconds"] for row in subset], marker="o", label=f"M={modes}")
    ax.set_xlabel("Epochs T")
    ax.set_ylabel("Observed runtime (s)")
    ax.set_title("Exact scheduling scalability")
    ax.legend()
    ax.grid(alpha=0.2)
    fig.tight_layout()
    _save_publication_figure(fig, figures / "scheduler_scalability.svg")
    plt.close(fig)
    takeaways["scheduler_scalability.svg"] = "Measured growth follows the expected dependence on both epochs and squared mode count."
    return takeaways


def _regime_sweep(
    *,
    payload: Mapping[str, object],
    modes: Mapping[str, ECCOperatingMode],
    designs: Sequence[ArchitectureDesign],
    transition_model: TransitionModel,
    policy: Mapping[str, object],
) -> dict:
    accesses_values = [int(value) for value in dict(payload.get("sweeps", {})).get("epoch_accesses", [1_000_000, 10_000_000, 100_000_000])]
    transition_multipliers = [float(value) for value in dict(payload.get("sweeps", {})).get("transition_energy_multipliers", [0.0, 1.0, 2.0])]
    matrix = []
    for accesses in accesses_values:
        row = []
        trace = generate_synthetic_trace({
            "family": "one_time_sbu_to_mbu", "seed": 1900, "epoch_count": 12,
            "accesses_per_epoch": accesses,
        })
        fixed_results = []
        for design in designs:
            if design.architecture_mode == "fixed":
                results, _ = _run_design(trace=trace, modes=modes, design=design, transition_model=transition_model, policy=policy)
                fixed_results.append((design.design_id, results["best_static"]))
        best_fixed = _best_result(fixed_results)
        for multiplier in transition_multipliers:
            adaptive_results = []
            for design in designs:
                if design.architecture_mode != "adaptive":
                    continue
                results, costs = _run_design(trace=trace, modes=modes, design=design, transition_model=transition_model, policy=policy)
                nominal = results["transition_aware_dp"]
                if nominal.status != "ok":
                    continue
                # Re-optimize with a multiplicative transition sensitivity; no
                # PPA value is inferred from the multiplier.
                base_lookup = _transition_lookup(transition_model, design, trace)

                def scaled_lookup(index: int, old: str, new: str) -> TransitionCost:
                    item = base_lookup(index, old, new)
                    return replace(
                        item,
                        energy_j=(item.energy_j * multiplier if item.energy_j is not None else None),
                        carbon_kgco2e=(item.carbon_kgco2e * multiplier if item.carbon_kgco2e is not None else None),
                    )

                result = exact_dynamic_programming(
                    epoch_costs=costs, transition_lookup=scaled_lookup, design=design,
                    objective=str(policy["objective"]), min_dwell_epochs=int(policy["minimum_dwell_epochs"]),
                    max_transitions=_policy_max_transitions(policy, len(trace.epochs)),
                )
                adaptive_results.append((design.design_id, result))
            best_adaptive = _best_result(adaptive_results)
            row.append(
                int(
                    bool(best_fixed and best_adaptive)
                    and float(best_adaptive[1].total_objective) < float(best_fixed[1].total_objective)
                )
            )
        matrix.append(row)
    return {
        "trace_family": "one_time_sbu_to_mbu",
        "model_status": "normalized synthetic sensitivity",
        "epoch_accesses": accesses_values,
        "transition_energy_multipliers": transition_multipliers,
        "adaptive_beneficial": matrix,
    }


def _write_findings(path: Path, report: Mapping[str, object], takeaways: Mapping[str, str]) -> None:
    h1 = report["hypotheses"]["H1_adaptation_paradox"]
    h2 = report["hypotheses"]["H2_break_even"]
    h3 = report["hypotheses"]["H3_topology_changes"]
    h4 = report["hypotheses"]["H4_granularity_region"]
    h5 = report["hypotheses"]["H5_robust_hysteresis"]
    lines = [
        "# Transition-aware GREEN-ECC findings",
        "",
        "> All numerical architecture points in this example are synthetic physical-unit sensitivity inputs, not synthesized or measured SRAM results.",
        "",
        f"- Objective: `{report['objective']}`",
        f"- Traces: {len(report['trace_results'])}",
        f"- H1 adaptation paradox: {h1['status']} ({len(h1['cases'])} cases)",
        f"- H2 measurable break-even region: {h2['status']}",
        f"- H3 topology changes with trace: {h3['status']}",
        f"- H4 bounded granularity benefit: {h4['status']}",
        f"- H5 hysteresis suppresses switches: {h5['status']}",
        "",
        "## Joint decisions",
        "",
        "| Trace | Architecture | Design | Policy | Total | Best fixed | Net saving |",
        "|---|---|---|---|---:|---:|---:|",
    ]
    for trace_id, value in report["trace_results"].items():
        joint = value["joint_decision"]
        static = value["best_fixed"]
        comparison = value["joint_vs_fixed"]
        lines.append(
            f"| {trace_id} | {joint['architecture_mode']} | {joint['design_id']} | {joint['policy']} | "
            f"{joint['total_objective']:.6g} | {static['total_objective']:.6g} | {comparison['net_saving']:.6g} |"
        )
    lines.extend(["", "## Figure takeaways", ""])
    for filename, takeaway in takeaways.items():
        lines.append(f"- `{filename}`: {takeaway}")
    lines.extend(
        [
            "",
            "## Validation boundary",
            "",
            "The scheduler, equations, schemas, and comparisons are executable. The default experiment is a transparent synthetic sensitivity study because no Liberty, synthesis, STA, SPICE, measured transition energy, or controller characterization is present. Threshold regions are supported; technology-specific superiority is not.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def run_transition_schedule(config_path: Path, outdir: Path, *, repo_root: Path) -> dict:
    started = time.perf_counter()
    config_path = config_path.resolve()
    outdir = outdir.resolve()
    payload = json.loads(config_path.read_text(encoding="utf-8"))
    _validate_input(payload, repo_root)
    modes = {item.ecc_id: item for item in (ECCOperatingMode.from_mapping(raw) for raw in payload["modes"])}
    designs = tuple(ArchitectureDesign.from_mapping(raw) for raw in payload["designs"])
    for design in designs:
        missing = sorted(set(design.supported_eccs) - set(modes))
        if missing:
            raise ValueError(f"design {design.design_id} references unknown ECCs: {missing}")
    trace_payload = dict(payload)
    inline_traces = list(payload.get("traces", []))
    external_trace_paths = []
    for raw_path in payload.get("trace_files", []):
        path = Path(str(raw_path))
        if not path.is_absolute():
            path = config_path.parent / path
        path = path.resolve()
        external_trace_paths.append(path)
        inline_traces.append(json.loads(path.read_text(encoding="utf-8")))
    trace_payload["traces"] = inline_traces
    traces = load_traces(trace_payload)
    transition_model = TransitionModel(payload["transition_costs"])
    policy = dict(payload["policy"])
    certificate_gate = dict(payload.get("certificate_gate", {})) or None
    certificate_envelopes = tuple(dict(item) for item in payload.get("certificate_envelopes", []))
    objective = str(policy["objective"])
    data_dir = outdir / "data"
    trace_dir = outdir / "traces"
    deployment_dir = outdir / "deployment"
    for directory in (outdir, data_dir, trace_dir, deployment_dir):
        directory.mkdir(parents=True, exist_ok=True)

    trace_results: dict[str, dict] = {}
    adaptation_paradoxes = []
    adaptive_wins = []
    topology_winners = set()
    granularity_winners = set()
    hysteresis_avoided: dict[str, int] = {}
    adaptive_granularity_by_trace: dict[str, str] = {}
    for trace_index, trace in enumerate(traces):
        trace_payload = trace.to_dict()
        trace_schema = json.loads((repo_root / "schemas" / "scenario-trace.schema.json").read_text(encoding="utf-8"))
        jsonschema.validate(trace_payload, trace_schema)
        _write_json(trace_dir / f"{trace.trace_id}.json", trace_payload)
        design_results: dict[str, dict] = {}
        design_objects: dict[str, tuple[dict[str, ScheduleResult], tuple[dict[str, EpochModeCost], ...]]] = {}
        fixed_candidates = []
        adaptive_candidates = []
        joint_candidates = []
        for design in designs:
            results, costs = _run_design(
                trace=trace,
                modes=modes,
                design=design,
                transition_model=transition_model,
                policy=policy,
                certificate_gate=certificate_gate,
                certificate_envelopes=certificate_envelopes,
            )
            design_objects[design.design_id] = (results, costs)
            if design.architecture_mode == "adaptive":
                decision = results["transition_aware_dp"]
                adaptive_candidates.append((design.design_id, decision))
            else:
                decision = results["best_static"]
            if design.architecture_mode == "fixed":
                fixed_candidates.append((design.design_id, decision))
            joint_candidates.append((design.design_id, decision))
            representative_epoch = trace.epochs[0]
            logical_granularity = evaluate_granularity(
                granularity=design.granularity,
                total_words=min(design.total_words, representative_epoch.active_words),
                active_region_fraction=representative_epoch.active_region_fraction,
                mode_count=len(design.supported_eccs),
                metadata_protection=design.metadata_protection,
                bank_count=design.bank_count,
                page_words=design.page_words,
                mux_replication_regions=design.mux_replication_regions,
                physical_word_selection_credible=design.physical_word_selection_credible,
            )
            if logical_granularity.get("feasible"):
                logical_granularity["mux_2to1_cells_total"] = (
                    int(logical_granularity["mux_replication_regions"])
                    * design.mux_2to1_cells_per_replica
                )
            design_results[design.design_id] = {
                "design": design.to_dict(),
                "granularity_accounting": logical_granularity,
                "decision_policy": (
                    "transition_aware_dp" if design.architecture_mode == "adaptive" else "best_static"
                ),
                "decision_result": decision.to_dict(),
                "policies": {name: item.to_dict() for name, item in results.items()},
                "epoch_costs": [
                    {mode: item.to_dict() for mode, item in row.items()} for row in costs
                ],
            }
        best_fixed = _best_result(fixed_candidates)
        best_adaptive = _best_result(adaptive_candidates)
        joint = _best_result(joint_candidates)
        if best_fixed is None or joint is None:
            raise ValueError(f"trace {trace.trace_id} has no feasible fixed/joint decision")
        joint_design = next(item for item in designs if item.design_id == joint[0])
        joint_policy = "transition_aware_dp" if joint_design.architecture_mode == "adaptive" else "best_static"
        topology_winners.add(joint_design.topology)
        granularity_winners.add(joint_design.granularity)
        joint_comparison = compare_schedule_to_static(joint[1], best_fixed[1])
        best_adaptive_id = best_adaptive[0] if best_adaptive else None
        if best_adaptive:
            best_adaptive_design = next(item for item in designs if item.design_id == best_adaptive[0])
            granularity_winners.add(best_adaptive_design.granularity)
            adaptive_granularity_by_trace[trace.trace_id] = best_adaptive_design.granularity
        waterfall = {"status": "unavailable"}
        regime_ratios = {
            "rho_transition": {"status": "unavailable", "ratio": None, "beneficial": None},
            "rho_adaptive": {"status": "unavailable", "ratio": None, "beneficial": None},
        }
        break_even = []
        uncertainty = None
        if best_adaptive:
            adaptive_design = next(item for item in designs if item.design_id == best_adaptive[0])
            adaptive_results, adaptive_costs = design_objects[best_adaptive[0]]
            lookup = _transition_lookup(transition_model, adaptive_design, trace)
            continuing_overhead = _continuing_adaptability_overhead(
                best_adaptive[1], adaptive_costs, objective
            )
            if continuing_overhead is not None:
                waterfall = waterfall_terms_with_continuing_overhead(
                    best_adaptive[1], best_fixed[1], continuing_overhead
                )
                if waterfall["status"] == "ok":
                    gross = float(waterfall["gross_operational_saving"])
                    transition_overhead = float(waterfall["transition_overhead"])
                    implementation_overhead = float(
                        waterfall["incremental_implementation_overhead"]
                    )
                    regime_ratios = {
                        "rho_transition": overhead_ratio(transition_overhead, gross),
                        "rho_adaptive": overhead_ratio(
                            continuing_overhead + transition_overhead + implementation_overhead,
                            gross,
                        ),
                        "interpretation": "adaptation is net beneficial only below one; ratios use complete physical-unit overhead and are not ranking scores",
                    }
            break_even = _transition_break_even(
                result=best_adaptive[1], costs=adaptive_costs, lookup=lookup, objective=objective
            )
            uncertainty = _uncertainty_study(
                nominal_costs=adaptive_costs,
                transition_lookup=lookup,
                design=adaptive_design,
                objective=objective,
                samples=int(payload["uncertainty_samples"]),
                seed=int(payload.get("uncertainty_seed", 1723)) + trace_index,
                min_dwell=int(policy["minimum_dwell_epochs"]),
                max_transitions=_policy_max_transitions(policy, len(trace.epochs)),
                reference=adaptive_results["robust_transition_aware"],
            )
            snapshot = adaptive_results["snapshot_oracle"]
            dp = adaptive_results["transition_aware_dp"]
            hysteresis = adaptive_results["robust_hysteresis"]
            avoided = count_avoided_transitions(snapshot, dp)
            hysteresis_avoided[trace.trace_id] = count_avoided_transitions(snapshot, hysteresis) or 0
            if (
                snapshot.status == "ok"
                and float(snapshot.total_objective) > float(best_fixed[1].total_objective)
                and snapshot.transitions > 0
                and dp.status == "ok"
                and dp.transitions < snapshot.transitions
            ):
                adaptation_paradoxes.append(
                    {
                        "trace_id": trace.trace_id,
                        "design_id": best_adaptive[0],
                        "snapshot_total": snapshot.total_objective,
                        "best_fixed_total": best_fixed[1].total_objective,
                        "transition_aware_total": dp.total_objective,
                        "snapshot_transitions": snapshot.transitions,
                        "transition_aware_transitions": dp.transitions,
                        "avoided_transitions": avoided,
                    }
                )
            if best_adaptive[1].status == "ok" and float(best_adaptive[1].total_objective) < float(best_fixed[1].total_objective):
                adaptive_wins.append(
                    {
                        "trace_id": trace.trace_id,
                        "design_id": best_adaptive[0],
                        **compare_schedule_to_static(best_adaptive[1], best_fixed[1]),
                        "waterfall": waterfall,
                    }
                )
        trace_results[trace.trace_id] = {
            "trace": trace_payload,
            "design_results": design_results,
            "best_fixed": {"design_id": best_fixed[0], **best_fixed[1].to_dict()},
            "best_adaptive_design_id": best_adaptive_id,
            "joint_decision": {
                "design_id": joint[0],
                "architecture_mode": joint_design.architecture_mode,
                "topology": joint_design.topology,
                "granularity": joint_design.granularity,
                "policy": joint_policy,
                **joint[1].to_dict(),
            },
            "joint_vs_fixed": joint_comparison,
            "waterfall": waterfall,
            "regime_ratios": regime_ratios,
            "break_even_transitions": break_even,
            "uncertainty": uncertainty,
        }

    regime_sweep = _regime_sweep(
        payload=payload,
        modes=modes,
        designs=designs,
        transition_model=transition_model,
        policy=policy,
    )
    h2_cells = sum(sum(row) for row in regime_sweep["adaptive_beneficial"])
    total_cells = len(regime_sweep["epoch_accesses"]) * len(regime_sweep["transition_energy_multipliers"])
    hypotheses = {
        "H1_adaptation_paradox": {
            "status": "supported_in_synthetic_sensitivity" if adaptation_paradoxes else "not_observed",
            "cases": adaptation_paradoxes,
        },
        "H2_break_even": {
            "status": "supported_in_synthetic_sensitivity" if 0 < h2_cells < total_cells else "inconclusive",
            "adaptive_cells": h2_cells,
            "fixed_cells": total_cells - h2_cells,
        },
        "H3_topology_changes": {
            "status": "supported_in_synthetic_sensitivity" if len(topology_winners) > 1 else "not_observed",
            "winning_topologies": sorted(topology_winners),
        },
        "H4_granularity_region": {
            "status": "supported_in_synthetic_sensitivity" if len(granularity_winners) > 1 else "inconclusive",
            "winning_granularities": sorted(granularity_winners),
            "best_adaptive_granularity_by_trace": adaptive_granularity_by_trace,
            "word_level_status": "excluded_without_credible_physical_metadata_and_routing_characterization",
        },
        "H5_robust_hysteresis": {
            "status": "conditionally_supported_in_synthetic_sensitivity" if any(value > 0 for value in hysteresis_avoided.values()) else "not_observed",
            "transition_reduction_vs_snapshot_by_trace": hysteresis_avoided,
        },
    }
    scalability = _dummy_scalability_benchmark()
    primary_trace_id = "one_time_sbu_to_mbu" if "one_time_sbu_to_mbu" in trace_results else next(iter(trace_results))
    primary = trace_results[primary_trace_id]
    deployment_policy = {
        "schema_version": 1,
        "trace_id": primary_trace_id,
        "design_id": primary["joint_decision"]["design_id"],
        "architecture_mode": primary["joint_decision"]["architecture_mode"],
        "topology": primary["joint_decision"]["topology"],
        "granularity": primary["joint_decision"]["granularity"],
        "epoch_modes": primary["joint_decision"]["path"],
        "timeline": primary["joint_decision"]["timeline"],
        "safe_fallback_ecc": policy["safe_fallback_ecc"],
        "minimum_dwell_epochs": policy["minimum_dwell_epochs"],
        "prediction_horizon_epochs": policy["prediction_horizon_epochs"],
        "minimum_benefit_margin": policy["minimum_benefit_margin"],
        "maximum_transitions": policy["maximum_transitions"],
        "maximum_switch_rate_per_epoch": policy.get("maximum_switch_rate_per_epoch"),
        "confidence_threshold": policy["confidence_threshold"],
        "transition_sequence": [
            "stable", "quiesce", "read_old_format", "decode", "re_encode",
            "write_new_format", "verify", "commit_protected_mode", "resume",
        ],
        "recovery": "force safe fallback after failed verification; complete migration datapath is not implemented",
        "certificate_gate": {
            "enabled": bool(certificate_gate and certificate_gate.get("enabled", False)),
            "configuration": certificate_gate,
            "registered_envelopes": list(certificate_envelopes),
            "rule": "a mode is infeasible unless ambiguity type, support identifier, radius, regime, and SDC limit are contained in its registered certificate",
        },
    }
    register_map = {
        "ECC_EPOCH_INDEX": {"offset": "0x00", "access": "RW", "description": "current policy epoch"},
        "ECC_REQUESTED_MODE": {"offset": "0x04", "access": "RO", "description": "scheduled mode"},
        "ECC_ACTIVE_MODE": {"offset": "0x08", "access": "RO", "description": "committed protected mode"},
        "ECC_TRANSITION_COMMAND": {"offset": "0x0C", "access": "WO", "description": "request/abort transition"},
        "ECC_TRANSITION_STATE": {"offset": "0x10", "access": "RO", "description": "sequencer state"},
        "ECC_BENEFIT_MARGIN": {"offset": "0x14", "access": "RO", "description": "configured physical-unit threshold"},
        "ECC_CONFIDENCE_MIN": {"offset": "0x18", "access": "RO", "description": "minimum switch confidence"},
        "ECC_SAFETY_ENVELOPE_ID": {"offset": "0x1C", "access": "RO", "description": "active SafeForge certificate identifier digest"},
        "ECC_ENVELOPE_VALID": {"offset": "0x20", "access": "RO", "description": "current confidence region is inside active certificate"},
        "ECC_CERTIFIED_FALLBACK": {"offset": "0x24", "access": "RO", "description": "fallback selected after certificate gate rejection"},
    }
    repository_commit, repository_dirty = _repository_state(repo_root)
    source_paths = [
        repo_root / "architecture" / name
        for name in (
            "traces.py", "transitions.py", "scheduling.py", "break_even.py", "hysteresis.py",
            "granularity.py", "schedule_explain.py", "schedule_pipeline.py",
        )
    ] + [
        repo_root / "schemas" / name
        for name in (
            "scenario-trace.schema.json", "transition-cost-matrix.schema.json",
            "scheduling-policy.schema.json", "schedule-result.schema.json",
            "transition-schedule-config.schema.json",
        )
    ] + [
        repo_root / "asic" / "rtl" / "common" / "green_ecc_transition_controller.sv",
        repo_root / "eccsim.py",
        config_path,
        *external_trace_paths,
    ]
    def source_label(path: Path) -> str:
        try:
            return str(path.relative_to(repo_root)).replace("\\", "/")
        except ValueError:
            return str(path)

    source_hashes = {source_label(path): _sha256(path) for path in source_paths}
    source_tree_sha256 = hashlib.sha256(
        json.dumps(source_hashes, sort_keys=True).encode("utf-8")
    ).hexdigest()
    run_id = hashlib.sha256(
        (_sha256(config_path) + source_tree_sha256).encode("utf-8")
    ).hexdigest()[:16]
    report = {
        "schema_version": 1,
        "study_id": str(payload["study_id"]),
        "objective": objective,
        "validation_level": str(payload["model_status"]),
        "trace_results": trace_results,
        "joint_decisions": {
            trace_id: value["joint_decision"] for trace_id, value in trace_results.items()
        },
        "hypotheses": hypotheses,
        "regime_sweep": regime_sweep,
        "scalability": scalability,
        "deployment_policy": deployment_policy,
        "provenance": {
            "repository_commit": repository_commit,
            "repository_dirty": repository_dirty,
            "input_config": str(config_path),
            "input_config_sha256": _sha256(config_path),
            "source_tree_sha256": source_tree_sha256,
            "result_run_id": run_id,
            "random_seeds": [trace.seed for trace in traces] + [int(payload.get("uncertainty_seed", 1723))],
            "metric_status": "synthetic physical-unit sensitivity; no synthesis or measurement claim",
        },
    }
    takeaways = _plot_results(outdir, report)
    report["figure_takeaways"] = takeaways
    _write_json(data_dir / "schedule_result.json", report)
    _write_json(data_dir / "policy_comparison.json", {
        trace_id: {
            design_id: compact_policy_table({name: ScheduleResult(**item) for name, item in value["policies"].items()})
            for design_id, value in trace["design_results"].items()
        }
        for trace_id, trace in trace_results.items()
    })
    _write_json(data_dir / "hypothesis_results.json", hypotheses)
    _write_json(data_dir / "regime_sweep.json", regime_sweep)
    _write_json(data_dir / "scalability.json", scalability)
    _write_json(data_dir / "figure_takeaways.json", takeaways)
    _write_json(
        data_dir / "granularity_comparison.json",
        {
            trace_id: {
                design_id: value["granularity_accounting"]
                for design_id, value in trace["design_results"].items()
            }
            for trace_id, trace in trace_results.items()
        },
    )
    _write_json(
        data_dir / "robustness.json",
        {trace_id: trace["uncertainty"] for trace_id, trace in trace_results.items()},
    )
    joint_schedule_rows = []
    design_summary_rows = []
    break_even_rows = []
    for trace_id, trace in trace_results.items():
        joint = trace["joint_decision"]
        for event in joint["timeline"]:
            joint_schedule_rows.append(
                {
                    "trace_id": trace_id,
                    "epoch_index": event["epoch_index"],
                    "epoch_id": event["epoch_id"],
                    "design_id": joint["design_id"],
                    "architecture_mode": joint["architecture_mode"],
                    "topology": joint["topology"],
                    "granularity": joint["granularity"],
                    "ecc_id": event["ecc_id"],
                    "epoch_objective": event["epoch_objective"],
                    "transition_objective": event["transition_objective"],
                    "fit": event["fit"],
                    "latency_ns": event["latency_ns"],
                    "feasibility_probability": event["feasibility_probability"],
                    "reason": event["reason"],
                }
            )
        for design_id, value in trace["design_results"].items():
            decision = value["decision_result"]
            design_summary_rows.append(
                {
                    "trace_id": trace_id,
                    "design_id": design_id,
                    "architecture_mode": value["design"]["architecture_mode"],
                    "topology": value["design"]["topology"],
                    "granularity": value["design"]["granularity"],
                    "policy": value["decision_policy"],
                    "status": decision["status"],
                    "total_objective": decision["total_objective"],
                    "epoch_objective": decision["epoch_objective"],
                    "transition_objective": decision["transition_objective"],
                    "transitions": decision["transitions"],
                }
            )
        for item in trace["break_even_transitions"]:
            break_even_rows.append(
                {
                    "trace_id": trace_id,
                    "epoch_index": item["epoch_index"],
                    "from_ecc": item["from_ecc"],
                    "to_ecc": item["to_ecc"],
                    "status": item["break_even"]["status"],
                    "horizon_accesses": item["break_even"]["horizon_accesses"],
                    "one_time_cost": item["break_even"]["one_time_cost"],
                    "net_improvement_per_access": item["break_even"]["net_improvement_per_access"],
                    "units": item["break_even"]["units"],
                }
            )
    _write_csv(data_dir / "joint_schedule.csv", joint_schedule_rows)
    _write_csv(data_dir / "design_comparison.csv", design_summary_rows)
    _write_csv(data_dir / "break_even.csv", break_even_rows)
    _write_json(deployment_dir / "transition_policy.json", deployment_policy)
    _write_json(deployment_dir / "schedule_register_map.json", register_map)
    _write_schedule_package(
        deployment_dir / "green_ecc_schedule_pkg.sv",
        modes=list(modes),
        schedule=deployment_policy["epoch_modes"],
        safe_fallback=str(policy["safe_fallback_ecc"]),
        minimum_dwell_epochs=int(policy["minimum_dwell_epochs"]),
    )
    _write_json(outdir / "resolved_config.json", payload)
    _write_findings(outdir / "findings.md", report, takeaways)
    result_schema = json.loads((repo_root / "schemas" / "schedule-result.schema.json").read_text(encoding="utf-8"))
    jsonschema.validate(report, result_schema)

    generated = [path for path in outdir.rglob("*") if path.is_file() and path.name != "result_manifest.json"]
    manifest = {
        "manifest_version": 1,
        "result_run_id": run_id,
        "repository_commit": repository_commit,
        "repository_dirty": repository_dirty,
        "input_config": str(config_path),
        "input_config_sha256": _sha256(config_path),
        "source_tree_sha256": source_tree_sha256,
        "source_files": source_hashes,
        "generated_trace_sources": {
            trace.trace_id: {"source": trace.source, "seed": trace.seed, "generator": trace.generator}
            for trace in traces
        },
        "files": {
            str(path.relative_to(outdir)).replace("\\", "/"): _sha256(path)
            for path in sorted(generated)
        },
        "reproduction_command": f"python eccsim.py schedule --config {config_path} --outdir {outdir}",
        "observed_runtime_seconds": time.perf_counter() - started,
    }
    _write_json(outdir / "result_manifest.json", manifest)
    return {
        "study_id": report["study_id"],
        "objective": objective,
        "trace_count": len(traces),
        "hypotheses": hypotheses,
        "result_run_id": run_id,
        "observed_runtime_seconds": manifest["observed_runtime_seconds"],
        "output_directory": str(outdir),
    }
