// Exact shortened primitive BCH(78,64,t=2) implementation for Gate 03R.
// This file is independent of the repository's rejected degree-12 cyclic RTL.

module bch_78_64_t2_v1_encoder (
  input  logic [63:0] data_i,
  output logic [77:0] codeword_o
);
  localparam logic [14:0] G_POLY = 15'b101010001111101;
  logic [77:0] work;
  integer dividend_index, coefficient_index;

  // The encoder depends only on data_i; the explicit sensitivity list also
  // prevents loop-temporary re-entry in conservative event simulators.
  always @(data_i) begin
    work = '0;
    work[77:14] = data_i;
    for (dividend_index = 77; dividend_index >= 14; dividend_index = dividend_index - 1) begin
      if (work[dividend_index]) begin
        for (coefficient_index = 0; coefficient_index <= 14; coefficient_index = coefficient_index + 1)
          work[dividend_index-coefficient_index] =
            work[dividend_index-coefficient_index] ^ G_POLY[14-coefficient_index];
      end
    end
    codeword_o = {work[13:0], data_i};
  end
endmodule

module bch_78_64_t2_v1_decoder (
  input  logic [77:0] codeword_i,
  output logic [63:0] data_o,
  output logic [77:0] corrected_codeword_o,
  output logic [27:0] syndrome_o,
  output logic [77:0] correction_mask_o,
  output logic        err_detected_o,
  output logic        err_corrected_o,
  output logic        err_uncorrectable_o
);
  logic [27:0] received_syndrome, corrected_syndrome;
  logic [6:0] s1, s3, s1_squared, s1_cubed, sigma2;
  logic [6:0] location_value, locator_value;
  logic [77:0] candidate_mask, candidate_codeword;
  integer position, root_count;

  function automatic logic [6:0] gf_mul(input logic [6:0] left, input logic [6:0] right);
    logic [7:0] a;
    logic [6:0] b;
    logic [6:0] result;
    integer bit_index;
    begin
      a = {1'b0, left};
      b = right;
      result = '0;
      for (bit_index = 0; bit_index < 7; bit_index = bit_index + 1) begin
        if (b[0]) result = result ^ a[6:0];
        b = b >> 1;
        a = a << 1;
        if (a[7]) a = a ^ 8'h83;
      end
      gf_mul = result;
    end
  endfunction

  function automatic logic [6:0] gf_inverse(input logic [6:0] value);
    logic [6:0] result, base;
    integer bit_index;
    begin
      result = 7'd1;
      base = value;
      for (bit_index = 0; bit_index < 7; bit_index = bit_index + 1) begin
        if ((126 >> bit_index) & 1) result = gf_mul(result, base);
        base = gf_mul(base, base);
      end
      gf_inverse = value == 0 ? 7'd0 : result;
    end
  endfunction

  // Frozen shortened-coordinate constants independently regenerated by
  // scripts/gate03r/verify_bch_identity.py.
  function automatic logic [27:0] coordinate_syndrome(input integer canonical_position);
    begin
      case (canonical_position)
        7'd0: coordinate_syndrome = 28'h0f54885;
        7'd1: coordinate_syndrome = 28'he09e20a;
        7'd2: coordinate_syndrome = 28'h24f8b14;
        7'd3: coordinate_syndrome = 28'h4dd6c28;
        7'd4: coordinate_syndrome = 28'hd887350;
        7'd5: coordinate_syndrome = 28'hae38ea3;
        7'd6: coordinate_syndrome = 28'hddc3a46;
        7'd7: coordinate_syndrome = 28'hee26a8f;
        7'd8: coordinate_syndrome = 28'hc52291e;
        7'd9: coordinate_syndrome = 28'h693273c;
        7'd10: coordinate_syndrome = 28'h95b1f78;
        7'd11: coordinate_syndrome = 28'h77abdf3;
        7'd12: coordinate_syndrome = 28'h736b4e5;
        7'd13: coordinate_syndrome = 28'h337d0c9;
        7'd14: coordinate_syndrome = 28'h2bdc391;
        7'd15: coordinate_syndrome = 28'hacc4e22;
        7'd16: coordinate_syndrome = 28'hfc37844;
        7'd17: coordinate_syndrome = 28'he3a228b;
        7'd18: coordinate_syndrome = 28'h0528916;
        7'd19: coordinate_syndrome = 28'h417242c;
        7'd20: coordinate_syndrome = 28'h19bd358;
        7'd21: coordinate_syndrome = 28'h87c8db3;
        7'd22: coordinate_syndrome = 28'h5067666;
        7'd23: coordinate_syndrome = 28'h1f2dacf;
        7'd24: coordinate_syndrome = 28'he752b9d;
        7'd25: coordinate_syndrome = 28'h44bed3a;
        7'd26: coordinate_syndrome = 28'h59fb774;
        7'd27: coordinate_syndrome = 28'h9fe5eeb;
        7'd28: coordinate_syndrome = 28'hd707bd5;
        7'd29: coordinate_syndrome = 28'h4e12ca9;
        7'd30: coordinate_syndrome = 28'hf883152;
        7'd31: coordinate_syndrome = 28'ha2186a7;
        7'd32: coordinate_syndrome = 28'h1cc1a4e;
        7'd33: coordinate_syndrome = 28'hc61699f;
        7'd34: coordinate_syndrome = 28'h48a253e;
        7'd35: coordinate_syndrome = 28'h991977c;
        7'd36: coordinate_syndrome = 28'hb6f1dfb;
        7'd37: coordinate_syndrome = 28'h5b977f5;
        7'd38: coordinate_syndrome = 28'hbe89ce9;
        7'd39: coordinate_syndrome = 28'hda5b3d1;
        7'd40: coordinate_syndrome = 28'h8eccca1;
        7'd41: coordinate_syndrome = 28'hd077242;
        7'd42: coordinate_syndrome = 28'h2faca87;
        7'd43: coordinate_syndrome = 28'hed4aa0e;
        7'd44: coordinate_syndrome = 28'he47eb1c;
        7'd45: coordinate_syndrome = 28'h65eef38;
        7'd46: coordinate_syndrome = 28'h5547f70;
        7'd47: coordinate_syndrome = 28'h5e1fee3;
        7'd48: coordinate_syndrome = 28'hfee38c5;
        7'd49: coordinate_syndrome = 28'hc316089;
        7'd50: coordinate_syndrome = 28'h0890112;
        7'd51: coordinate_syndrome = 28'h8098424;
        7'd52: coordinate_syndrome = 28'h30d9048;
        7'd53: coordinate_syndrome = 28'h0ad4193;
        7'd54: coordinate_syndrome = 28'ha0b4626;
        7'd55: coordinate_syndrome = 28'h3db984c;
        7'd56: coordinate_syndrome = 28'hcbea19b;
        7'd57: coordinate_syndrome = 28'h8964536;
        7'd58: coordinate_syndrome = 28'hb11d46c;
        7'd59: coordinate_syndrome = 28'h3ad11db;
        7'd60: coordinate_syndrome = 28'haa947b5;
        7'd61: coordinate_syndrome = 28'h9cb9e6a;
        7'd62: coordinate_syndrome = 28'hf7db9d7;
        7'd63: coordinate_syndrome = 28'h42e64ad;
        7'd64: coordinate_syndrome = 28'h0204081;
        7'd65: coordinate_syndrome = 28'h2020202;
        7'd66: coordinate_syndrome = 28'h0d00804;
        7'd67: coordinate_syndrome = 28'hc032008;
        7'd68: coordinate_syndrome = 28'h2980310;
        7'd69: coordinate_syndrome = 28'h8c28c20;
        7'd70: coordinate_syndrome = 28'hf143040;
        7'd71: coordinate_syndrome = 28'h223c283;
        7'd72: coordinate_syndrome = 28'h2de0a06;
        7'd73: coordinate_syndrome = 28'hcd2680c;
        7'd74: coordinate_syndrome = 28'he912318;
        7'd75: coordinate_syndrome = 28'ha4b0f30;
        7'd76: coordinate_syndrome = 28'h7d9bc60;
        7'd77: coordinate_syndrome = 28'hd2eb2c3;
        default: coordinate_syndrome = 28'd0;
      endcase
    end
  endfunction

  function automatic logic [6:0] location_element(input integer canonical_position);
    begin
      case (canonical_position)
        7'd0: location_element = 7'h05;
        7'd1: location_element = 7'h0a;
        7'd2: location_element = 7'h14;
        7'd3: location_element = 7'h28;
        7'd4: location_element = 7'h50;
        7'd5: location_element = 7'h23;
        7'd6: location_element = 7'h46;
        7'd7: location_element = 7'h0f;
        7'd8: location_element = 7'h1e;
        7'd9: location_element = 7'h3c;
        7'd10: location_element = 7'h78;
        7'd11: location_element = 7'h73;
        7'd12: location_element = 7'h65;
        7'd13: location_element = 7'h49;
        7'd14: location_element = 7'h11;
        7'd15: location_element = 7'h22;
        7'd16: location_element = 7'h44;
        7'd17: location_element = 7'h0b;
        7'd18: location_element = 7'h16;
        7'd19: location_element = 7'h2c;
        7'd20: location_element = 7'h58;
        7'd21: location_element = 7'h33;
        7'd22: location_element = 7'h66;
        7'd23: location_element = 7'h4f;
        7'd24: location_element = 7'h1d;
        7'd25: location_element = 7'h3a;
        7'd26: location_element = 7'h74;
        7'd27: location_element = 7'h6b;
        7'd28: location_element = 7'h55;
        7'd29: location_element = 7'h29;
        7'd30: location_element = 7'h52;
        7'd31: location_element = 7'h27;
        7'd32: location_element = 7'h4e;
        7'd33: location_element = 7'h1f;
        7'd34: location_element = 7'h3e;
        7'd35: location_element = 7'h7c;
        7'd36: location_element = 7'h7b;
        7'd37: location_element = 7'h75;
        7'd38: location_element = 7'h69;
        7'd39: location_element = 7'h51;
        7'd40: location_element = 7'h21;
        7'd41: location_element = 7'h42;
        7'd42: location_element = 7'h07;
        7'd43: location_element = 7'h0e;
        7'd44: location_element = 7'h1c;
        7'd45: location_element = 7'h38;
        7'd46: location_element = 7'h70;
        7'd47: location_element = 7'h63;
        7'd48: location_element = 7'h45;
        7'd49: location_element = 7'h09;
        7'd50: location_element = 7'h12;
        7'd51: location_element = 7'h24;
        7'd52: location_element = 7'h48;
        7'd53: location_element = 7'h13;
        7'd54: location_element = 7'h26;
        7'd55: location_element = 7'h4c;
        7'd56: location_element = 7'h1b;
        7'd57: location_element = 7'h36;
        7'd58: location_element = 7'h6c;
        7'd59: location_element = 7'h5b;
        7'd60: location_element = 7'h35;
        7'd61: location_element = 7'h6a;
        7'd62: location_element = 7'h57;
        7'd63: location_element = 7'h2d;
        7'd64: location_element = 7'h01;
        7'd65: location_element = 7'h02;
        7'd66: location_element = 7'h04;
        7'd67: location_element = 7'h08;
        7'd68: location_element = 7'h10;
        7'd69: location_element = 7'h20;
        7'd70: location_element = 7'h40;
        7'd71: location_element = 7'h03;
        7'd72: location_element = 7'h06;
        7'd73: location_element = 7'h0c;
        7'd74: location_element = 7'h18;
        7'd75: location_element = 7'h30;
        7'd76: location_element = 7'h60;
        7'd77: location_element = 7'h43;
        default: location_element = 7'd0;
      endcase
    end
  endfunction

  function automatic logic [27:0] calculate_syndrome(input logic [77:0] word);
    logic [27:0] packed_syndrome;
    integer coordinate;
    begin
      packed_syndrome = '0;
      for (coordinate = 0; coordinate < 78; coordinate = coordinate + 1)
        if (word[coordinate])
          packed_syndrome = packed_syndrome ^ coordinate_syndrome(coordinate);
      calculate_syndrome = packed_syndrome;
    end
  endfunction

  // The decoder depends only on its received word.  An explicit sensitivity
  // list avoids simulator-specific always_comb re-entry on loop temporaries.
  always @(codeword_i) begin
    received_syndrome = calculate_syndrome(codeword_i);
    syndrome_o = received_syndrome;
    s1 = received_syndrome[6:0];
    s3 = received_syndrome[20:14];
    s1_squared = gf_mul(s1, s1);
    s1_cubed = gf_mul(s1_squared, s1);
    sigma2 = gf_mul(s3 ^ s1_cubed, gf_inverse(s1));

    candidate_mask = '0;
    root_count = 0;
    position = 0;
    location_value = '0;
    locator_value = '0;
    if ((received_syndrome != '0) && (s1 != '0)) begin
      for (position = 0; position < 78; position = position + 1) begin
        location_value = location_element(position);
        locator_value = gf_mul(location_value, location_value)
          ^ gf_mul(s1, location_value) ^ sigma2;
        if (locator_value == 0) begin
          candidate_mask[position] = 1'b1;
          root_count = root_count + 1;
        end
      end
    end

    candidate_codeword = codeword_i ^ candidate_mask;
    corrected_syndrome = calculate_syndrome(candidate_codeword);

    correction_mask_o = '0;
    corrected_codeword_o = codeword_i;
    data_o = codeword_i[63:0];
    err_detected_o = received_syndrome != '0;
    err_corrected_o = 1'b0;
    err_uncorrectable_o = 1'b0;

    if (received_syndrome != '0) begin
      if ((s1 != '0) && ((root_count == 1) || (root_count == 2))
          && (corrected_syndrome == '0)) begin
        correction_mask_o = candidate_mask;
        corrected_codeword_o = candidate_codeword;
        data_o = candidate_codeword[63:0];
        err_corrected_o = 1'b1;
      end else begin
        err_uncorrectable_o = 1'b1;
      end
    end
  end
endmodule
