export DESIGN_NAME = gate04_boundary_ref_78_64
export PLATFORM = sky130hd
export VERILOG_FILES = /gate04-repo/scripts/gate04/rtl/gate04_boundaries.sv
export SDC_FILE = /gate04-repo/scripts/gate04/configs/gate04.sdc
export ADDER_MAP_FILE :=
export CORE_UTILIZATION = 35
export CORE_ASPECT_RATIO = 1
export CORE_MARGIN = 10
export PLACE_DENSITY = 0.55
